// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AntivirusIdentify(arg1) {
  return window['go']['core']['Tools']['AntivirusIdentify'](arg1);
}

export function ConnectAndExecute(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['core']['Tools']['ConnectAndExecute'](arg1, arg2, arg3, arg4, arg5);
}

export function FormatOutput(arg1) {
  return window['go']['core']['Tools']['FormatOutput'](arg1);
}

export function FscanToGraph(arg1) {
  return window['go']['core']['Tools']['FscanToGraph'](arg1);
}

export function GenerateDict(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['core']['Tools']['GenerateDict'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function PatchIdentify(arg1) {
  return window['go']['core']['Tools']['PatchIdentify'](arg1);
}
