// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AntivirusIdentify(arg1) {
  return window['go']['core']['Tools']['AntivirusIdentify'](arg1);
}

export function ConnectAndExecute(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['core']['Tools']['ConnectAndExecute'](arg1, arg2, arg3, arg4, arg5);
}

export function ExtractAlibabaDruidWebSession(arg1) {
  return window['go']['core']['Tools']['ExtractAlibabaDruidWebSession'](arg1);
}

export function ExtractAlibabaDruidWebURI(arg1) {
  return window['go']['core']['Tools']['ExtractAlibabaDruidWebURI'](arg1);
}

export function ExtractIP(arg1) {
  return window['go']['core']['Tools']['ExtractIP'](arg1);
}

export function ExtractURLs(arg1) {
  return window['go']['core']['Tools']['ExtractURLs'](arg1);
}

export function FormatOutput(arg1) {
  return window['go']['core']['Tools']['FormatOutput'](arg1);
}

export function GOOS() {
  return window['go']['core']['Tools']['GOOS']();
}

export function GetToken(arg1, arg2, arg3) {
  return window['go']['core']['Tools']['GetToken'](arg1, arg2, arg3);
}

export function IPParse(arg1) {
  return window['go']['core']['Tools']['IPParse'](arg1);
}

export function IsRoot() {
  return window['go']['core']['Tools']['IsRoot']();
}

export function NacosCategoriesExtract(arg1) {
  return window['go']['core']['Tools']['NacosCategoriesExtract'](arg1);
}

export function PatchIdentify(arg1) {
  return window['go']['core']['Tools']['PatchIdentify'](arg1);
}

export function PortParse(arg1) {
  return window['go']['core']['Tools']['PortParse'](arg1);
}
