id: CVE-2022-46463

info:
  name: GLPI htmLawedTest.php RCE
  author: Arm!tage
  severity: high
  verified: true
  description: |
    GLPI htmLawedTest.php 文件存在远程代码执行漏洞

rules:
  r0:
    request:
      method: GET
      path: /vendor/htmlawed/htmlawed/htmLawedTest.php
    expression: response.status != 200 && response.body.bcontains(b'htmLawed')
expression: r0()
