id: easygbs-userlist-infoleak

info:
  name: EasyGBS Userlist API Infoleak
  author: qwtd
  severity: high
  verified: true
  tags: unauth,easygbs

rules:
  r0:
    request:
      method: GET
      path: /api/v1/userlist?pageindex=0&pagesize=10
    expression: response.status == 200 && response.headers["content-type"].contains("application/json")
expression: r0()
