id: http-etcd-unauthenticated-api-data-leak

info:
  name: etcd Unauthenticated HTTP API Leak
  author: dhiyaneshDk
  severity: high
  reference:
    - https://hackerone.com/reports/1088429
  tags: misconfig,hackerone,unauth,etcd

rules:
  r0:
    request:
      method: GET
      path: /v2/auth/roles
    expression: response.status == 200 && response.body.bcontains(b'roles') && response.body.bcontains(b'permissions') && response.body.bcontains(b'role') && response.body.bcontains(b'kv') && (response.headers["content-type"].contains("application/json") || response.headers["content-type"].contains("text/plain"))
expression: r0()
