id: harbor-swaggerui-unauth

info:
  name: Harbor Swaggerui Unauth
  author: qwtd
  severity: low
  verified: true
  description: |
    Harbor 存在 swagger.json文件未授权访问。

rules:
  r0:
    request:
      method: GET
      path: /swagger.json
    expression: response.status == 200 && response.body.bcontains(b'Harbor API')
expression: r0()