id: jeecg-druid-unauth

info:
  name: jeecg-druid-unauth
  author: qwtd
  severity: medium
  description: 'fofa: loginController.do'
  verified: true

rules:
  r0:
    request:
      method: GET
      path: /webpage/system/druid/index.html
      follow_redirects: true
    expression: |
      response.status == 200
      &&
      (response.body.bcontains(b'Druid Stat Index'))
      &&
      (response.body.bcontains(b'DruidVersion'))
      &&
      (response.body.bcontains(b'DruidDrivers'))
      ||
      (response.body.ibcontains(b'<title>druid monitor</title>'))

expression: r0()