id: jeecg-jeecgFormDemoController-fileupload

info:
  name: Jeecg jeecgFormDemoController.do 任意文件上传漏洞
  author: qwtd
  severity: high
  verified: true
  description: |
    fofa: body: 'loginController.do'
    后台任意文件上传漏洞，前台仅测试该文件是否存在

rules:
  r0:
    request:
      method: GET
      path: /jeecgFormDemoController.do?saveFiles
    expression: response.status == 200 && response.body.bcontains(b'UnsatisfiedServletRequestParameterException')
expression: r0()