id: jeeplus-druid-unauth

info:
  name: jeeplus druid unauth
  author: qwtd
  severity: medium
  description: |
    hunter: web.body="We're sorry but Jeeplus doesn't work"
  verified: true

rules:
  r0:
    request:
      method: GET
      path: /jeeplus-vue/druid/index.html
      follow_redirects: true
    expression: |
      response.status == 200
      &&
      (response.body.bcontains(b'Druid Stat Index'))
      &&
      (response.body.bcontains(b'DruidVersion'))
      &&
      (response.body.bcontains(b'DruidDrivers'))
      ||
      (response.body.ibcontains(b'<title>druid monitor</title>'))

  r1:
    request:
      method: GET
      path: /jeeplus-v3/druid/index.html
      follow_redirects: true
    expression: |
      response.status == 200
      &&
      (response.body.bcontains(b'Druid Stat Index'))
      &&
      (response.body.bcontains(b'DruidVersion'))
      &&
      (response.body.bcontains(b'DruidDrivers'))
      ||
      (response.body.ibcontains(b'<title>druid monitor</title>'))

expression: r0() || r1()