id: jinher-oa-saveasotherformatservlet-upload

info:
  name: jinher OA saveAsOtherFormatServlet Upload
  author: ct
  severity: critical
  description: |
    攻击者可以通过上传任意文件然后控制服务器，该POC仅验证接口是否符合POC前置条件，上传内容自行构造
    fofa: app="金和网络-金和OA"
  created: 2023/10/26

rules:
  r0:
    request:
      method: GET
      path: /jc6/servlet/saveAsOtherFormatServlet?fileName=
    expression: response.status == 200 && response.body.bcontains(b'content type header is null')
expression: r0()