id: qiyuesuo-dzqz-upload

info:
  name: qiyuesuo dzqz upload
  author: qwtd
  severity: critical
  verified: true
  description: |
    契约锁电子签章系统 /login/%2e%2e/utask/upload 接口存在任意文件上传漏洞，攻击者可以通过该漏洞获取主机权限，该POC仅验证接口是否符合漏洞情况。
  solutions: 官方已发布更新补丁，请自行下载
  affected: 版本小于2023年8月之前
  create: 2023/10/26

rules:
  r0:
    request:
      method: POST
      path: /login/%2e%2e/utask/upload
    expression: response.status == 405
  r1:
    request:
      method: POST
      path: /callback/%2E%2E;/code/upload
    expression: |
      response.status == 200 && response.body.bcontains(b"\"code\": 1000000")
expression: r0() || r1()