id: zstack-swaggerui-unauth

info:
  name: ZStack Swaggerui Unauth
  author: qwtd
  severity: low
  verified: true
  description: |
    ZStack 存在 swagger.json文件未授权访问。

rules:
  r0:
    request:
      method: GET
      path: /docs/swagger.json
    expression: response.status == 200 && response.body.bcontains(b'swagger') && response.body.bcontains(b'description')
expression: r0()