id: CVE-2021-21972

info:
    name: VMware vCenter Unauthenticated RCE
    author: B1anda0(https://github.com/B1anda0)
    severity: critical
    verified: false
    description: |
        FOFA: app="vmware-vCenter"
    reference: 
        - https://mp.weixin.qq.com/s?__biz=MzkzODQzNTU2NA==&mid=2247484562&idx=1&sn=b0279899de3fdefb3bc8c9d054237628
        - https://github.com/horizon3ai/CVE-2021-21972
    tags: vmware,vcenter,rce,cve,cve2021
    created: 2023/07/12

rules:
    r0:
        request:
            method: GET
            path: /sdk/vimServiceVersions.xml
        expression: response.status == 200 && response.body.bcontains(b'<namespace>') && response.body.bcontains(b'<priorVersions>')
    r1:
        request:
            method: GET
            path: /ui/vropspluginui/rest/services/uploadova
        expression: response.status == 405
expression: r0() && r1()