id: CVE-2021-40859
info:
  name: Auerswald COMpact 5500R 7.8A and 8.0B Devices Backdoor
  author: pussycat0x
  severity: critical
  description: |
    Auerswald COMpact 5500R 7.8A and 8.0B devices contain an unauthenticated endpoint ("https://192.168.1[.]2/about_state"), enabling the bad actor to gain backdoor access to a web interface that allows for resetting the administrator password.
    FOFA: "auerswald"
  reference:
    - https://thehackernews.com/2021/12/secret-backdoors-found-in-german-made.html
    - https://nvd.nist.gov/vuln/detail/CVE-2021-40859
    - https://www.redteam-pentesting.de/en/advisories/-advisories-publicised-vulnerability-analyses
    - https://www.redteam-pentesting.de/en/advisories/rt-sa-2021-007/-auerswald-compact-multiple-backdoors
  tags: cve,cve2021,iot,unauth,voip,auerswald

rules:
  r0:
    request:
      method: GET
      path: /about_state
    expression: |
      response.status == 200 &&
      response.body.bcontains(b'"pbx"') &&
      response.body.bcontains(b'"dongleStatus":0') &&
      response.body.bcontains(b'"macaddr"')
expression: r0()