id: CVE-2021-35587

info:
  name: Oracle Access Manager - Remote Code Execution
  author: cckuailong
  severity: critical
  verified: true
  description: |
    The Oracle Access Manager  portion of Oracle Fusion Middleware (component: OpenSSO Agent) is vulnerable to remote code execution. Supported versions that are affected are 11.1.2.3.0, 12.2.1.3.0 and 12.2.1.4.0. This is an easily exploitable vulnerability that allows unauthenticated attackers with network access via HTTP to compromise Oracle Access Manager.
    FOFA: body="/oam/pages/css/login_page.css"
    SHODAN: http.title:"Oracle Access Management"
  reference:
    - https://testbnull.medium.com/oracle-access-manager-pre-auth-rce-cve-2021-35587-analysis-1302a4542316
    - https://nvd.nist.gov/vuln/detail/CVE-2021-35587
    - https://www.oracle.com/security-alerts/cpujan2022.html
  tags: cve,cve2021,oam,rce,java,unauth,oracle,kev

rules:
  r0:
    request:
      method: GET
      path: /oam/server/opensso/sessionservice
    expression: |
      response.status == 200 && 
      response.body.bcontains(b'/oam/pages/css/general.css') && 
      response.body.bcontains(b'login-footer-version') && 
      response.body.bcontains(b'Oracle Corporation') && 
      (response.raw_header.ibcontains(b'x-oracle-dms-ecid') || response.raw_header.ibcontains(b'x-oracle-dms-rid'))
expression: r0()