id: adminer-detect

info:
  name: Adminer Login Panel
  author: random_robbie,meme-lord
  severity: info
  verified: true
  description: |
    An Adminer login panel was detected.
    app="Adminer"
  reference:
    - https://blog.sorcery.ie/posts/adminer/

rules:
  r0:
    request:
      method: GET
      path: /adminer.php
      headers:
        Accept-Language: en-US,en;q=0.5
    expression: response.status == 200 && response.body.bcontains(b'Login - Adminer') && "<span class=\"version\">([0-9.]+)".bmatches(response.body)
  r1:
    request:
      method: GET
      path: /mysql.php
      headers:
        Accept-Language: en-US,en;q=0.5
    expression: response.status == 200 && response.body.bcontains(b'Login - Adminer') && "<span class=\"version\">([0-9.]+)".bmatches(response.body)
expression: r0() || r1()