id: Docker-And-Etcd-detect

info:
    name: Docker-And-Etcd Detect
    author: qwtd
    severity: info
    verified: true

rules:
    r0:
        request:
            method: GET
            path: /version
            follow_redirects: true
        expressions:
           - '"docker" != "" && response.status == 200 && response.body.bcontains(b"Docker Engine")'
           - '"etcd" != "" && response.status == 200 && response.body.bcontains(b"etcdserver") && response.body.bcontains(b"etcdcluster")'
           
expression: r0()