id: nacos-detect

info:
  name: Nacos Detect
  author: zan8in
  severity: info
  verified: true
  tags: nacos,panel
  created: 2023/07/27

rules:
  r0:
    request:
      method: GET
      path: /nacos/
      follow_redirects: true
    expression: response.status == 200 && response.body.ibcontains(b'<title>Nacos</title>')
expression: r0()