id: swagger-disclosure

info:
  name: Public Swagger API Desclosure
  author: pdteam
  severity: info
  verified: true

rules:
  r0:
    request:
      method: GET
      path: /swagger-ui.html
    expression: |
      response.status == 200 && 
      (response.body.bcontains(b'swagger:') ||
      response.body.bcontains(b'Swagger 2.0') ||
      response.body.bcontains(b"\"swagger\":") ||
      response.body.bcontains(b'Swagger UI') ||
      response.body.bcontains(b'**token**:'))

  r1:
    request:
      method: GET
      path: /api/docs/
    expression: |
      response.status == 200 && 
      (response.body.bcontains(b'swagger:') ||
      response.body.bcontains(b'Swagger 2.0') ||
      response.body.bcontains(b"\"swagger\":") ||
      response.body.bcontains(b'Swagger UI') ||
      response.body.bcontains(b'**token**:'))

  r2:
    request:
      method: GET
      path: /api/%20/swagger-ui.html
    expression: |
      response.status == 200 && 
      (response.body.bcontains(b'swagger:') ||
      response.body.bcontains(b'Swagger 2.0') ||
      response.body.bcontains(b"\"swagger\":") ||
      response.body.bcontains(b'Swagger UI') ||
      response.body.bcontains(b'**token**:'))

  r3:
    request:
      method: GET
      path: /v2/api-docs
    expression: |
      response.status == 200 && 
      response.body.bcontains(b'"info":') &&
      response.body.bcontains(b'"description":')  &&
      response.body.bcontains(b'"version":') &&
      response.body.bcontains(b'"title":')

  r4:
    request:
      method: GET
      path: /swagger/index.html
    expression: |
      response.status == 200 && 
      (response.body.bcontains(b'swagger:') ||
      response.body.bcontains(b'Swagger 2.0') ||
      response.body.bcontains(b"\"swagger\":") ||
      response.body.bcontains(b'Swagger UI') ||
      response.body.bcontains(b'**token**:'))
expression: r0() || r1() || r2() || r3() || r4()