id: dell-idrac-default-login

info:
  name: Dell iDRAC6/7/8 Default Login
  author: kophjager007
  severity: high
  description: Dell iDRAC6/7/8 default login information was discovered. The default iDRAC username and password are widely known, and any user with access to the server could change the default password.
  reference:
    - https://securityforeveryone.com/tools/dell-idrac6-7-8-default-login-scanner
  tags: dell,idrac,default-login
  created: 2023/06/24

set:
  host: request.url.host
rules:
  r0:
    request:
      method: POST
      path: /data/login
      headers:
        Referer: "{{host}}/login.html"
      body: user=root&password=calvin
    expression: response.status == 200 && response.body.bcontains(b'<authResult>0</authResult>')
expression: r0()