id: druid-default-login

info:
  name: Apache Druid Default Login
  author: pikpikcu
  severity: high
  verified: false
  description: |
    Apache Druid default login information (admin/admin) was discovered.
    FOFA: title="druid monitor"
  tags: druid,default-login
  created: 2023/06/23

set:
  username: admin
  password: admin
rules:
  r0:
    request:
      method: POST
      path: /druid/submitLogin
      body: loginUsername={{username}}&loginPassword={{password}}
    expression: 'response.status == 200 && "^success$".bmatches(response.body)'
  r1:
    request:
      method: POST
      path: /submitLogin
      body: loginUsername={{username}}&loginPassword={{password}}
    expression: 'response.status == 200 && "^success$".bmatches(response.body)'
expression: r0() || r1()