id: emqx-default-login

info:
  name: Emqx Default Admin Login
  author: For3stCo1d
  severity: high
  verifed: true
  description: |
    Emqx default admin credentials were discovered.
    SHODAN: http.favicon.hash:"-670975485"
    FOFA: icon_hash="-670975485"
  tags: emqx,default-login
  created: 2023/06/24

rules:
  r0:
    request:
      method: POST
      path: /api/v4/auth
      body: |
        {"username":"admin","password":"public"}
    expression: |
      response.status == 200 && 
      response.body == bytes("{\"code\":0}")
expression: r0()
