id: jenkins-default-pwd

info:
  name: Jenkins Default Password
  author: zan8in
  severity: high
  verified: true
  description: app="Jenkins"

rules:
    r1:
        request:
            method: POST
            path: /j_spring_security_check
            body: |
              j_username=jenkins&j_password=password&from=&Submit=Sign+in
        expression: |
          response.status == 302 && response.body.bcontains(b'<title>工作台 [Jenkins]</title>')
        stop_if_match: true
expression: r1() || r2()
