id: smartsense-default-login

info:
  name: HortonWorks SmartSense Default Login
  author: Techryptic (@Tech)
  severity: high
  verified: false
  description: HortonWorks SmartSense default admin login information was detected.
  reference:
    - https://docs.cloudera.com/HDPDocuments/SS1/SmartSense-1.2.2/bk_smartsense_admin/content/manual_server_login.html
  tags: hortonworks,smartsense,default-login
  created: 2023/06/24

set:
  admin: base64("admin:admin")
rules:
  r0:
    request:
      method: GET
      path: /apt/v1/context
      headers:
        Authorization: Basic {{admin}}
    expression: response.status == 200 && response.headers["set-cookie"].contains("SUPPORTSESSIONID")
expression: r0()
