id: tomcat-examples-login

info:
  name: Apache Tomcat - Default Login Discovery
  author: 0xelkomy & C0NQR0R
  severity: info
  verified: false
  description: Apache Tomcat 10.1.0-M1 to 10.1.0-M16, 10.0.0-M1 to 10.0.22, 9.0.30 to 9.0.64 and 8.5.50 to 8.5.81  default login credentials were successful.
  reference:
    - https://c0nqr0r.github.io/CVE-2022-34305/
  tags: default-login,tomcat
  created: 2023/06/23

rules:
  r0:
    request:
      method: POST
      path: /examples/jsp/security/protected/j_security_check
      body: j_username=tomcat&j_password=tomcat
      follow_redirects: true
    expression: response.body.bcontains(b'You are logged in as remote user')  && response.body.bcontains(b'tomcat')
expression: r0()
