id: arcgis-datastore-detect

info:
  name: ArcGIS Datastore Detect
  author: zan8in
  severity: info
  verifie: true
  tags: arcgis,datastore
  created: 2023/07/27

rules:
  r0:
    request:
      method: GET
      path: /arcgis/datastore
      follow_redirects: true
    expression: response.status == 200 && response.body.ibcontains(b'<title>ArcGIS Data Store</title>') 
expression: r0()