id: arcgis-sharing-rest-login

info:
  name: ArcGIS Sharing Rest Login Panel
  author: zan8in
  severity: info
  verifie: true
  tags: arcgis,login,panel
  created: 2023/07/27

rules:
  r0:
    request:
      method: GET
      path: /arcgis/sharing/rest/login
    expression: response.status == 200 && response.body.bcontains(b'<b>ArcGIS Portal Directory</b>') && response.body.bcontains(b'<a href="/arcgis/sharing/rest">Home</a>')
expression: r0()