id: avideo-install

info:
  name: AVideo Installer - Detect
  author: ritikchaddha
  severity: high
  verified: true
  description: |
    AVideo installer panel was detected.
    SHODAN: http.title:"AVideo"
    FOFA: "AVideo"
  tags: panel,install,avideo
  created: 2023/06/17

rules:
  r0:
    request:
      method: GET
      path: /install/index.php
    expression: response.status == 200 && response.body.ibcontains(b'<title>Install AVideo</title>')
expression: r0()