id: chinaunicom-modem-default-password

info:
  name: 中国联通 modem 默认密码
  author: daffainfo
  severity: high
  verified: false
  description: 中国联通 modem 默认密码
  tags: chinaunicom,default-login
  created: 2023/06/24
  
rules:
  r0:
    request:
      method: POST
      path: /cu.html
      body: frashnum=&action=login&Frm_Logintoken=1&Username=CUAdmin&Password=CUAdmin&Username=&Password=
    expression: response.status == 302 && response.raw_header.bcontains(b"/menu.gch")
expression: r0()

