id: ecology-filedownloadforoutdoc-sqli

info:
  name: 泛微 OA filedownloadforoutdoc - SQL injection
  author: zan8in
  severity: critical
  verified: true
  description: 泛微 OA filedownloadforoutdoc interface has SQL injection
  tags: ecology,sqli
  created: 2023/07/11

rules:
  r0:
    request:
      type: go
      data: ecology-filedownloadforoutdoc-sqli
    expression: |
      !response.raw.bcontains(b'No ecologyFiledownloadforoutdocSqli') 
expression: r0()