id: firewall-password-leak

info:
  name: 防火墙硬编码漏洞
  author: tangshoupu
  severity: high
  verified: false

rules:
  r0:
    request:
      method: GET
      path: /
      follow_redirects: true
    expression: |
      response.body.ibcontains(b"var dkey_verify = Get_Verify_Info(hex_md5") && response.body.ibcontains(b"get_dkey_passwd") && "\"name\":\"\\w+\",\"password\":\"\\w{15,33}\",\"lastpwdtime".bmatches(response.body)
expression: r0()