id: tidb-unauth

info:
  name: TiDB - Unauthenticated Access
  author: lu4nx
  severity: high
  description: |
    TiDB server was able to be accessed because no authentication was required.
    zoomeye-query: tidb +port:"4000"
  tags: network,tidb,unauth
  created: 2022/07/20

set:
  hostname: request.url.host
  host: request.url.domain
rules:
  r0:
    request:
      type: tcp
      host: "{{hostname}}"
      read-size: 1024
    expression: response.raw.bcontains(b'mysql_native_password') && response.raw.bcontains(b'TiDB')
  r1:
    request:
      type: tcp
      host: "{{host}}:4000"
      read-size: 1024
    expression: response.raw.bcontains(b'mysql_native_password') && response.raw.bcontains(b'TiDB')
expression: r0() || r1()