id: weaver-ecology-oa-plugin-checkserver-setting-sqli

info:
  name: 泛微 Ecology OA SQL 注入漏洞
  author: chaitin
  severity: high
  verified: false
  description: |
    泛微 Ecology OA 系统由于对用户传入的数据过滤处理不当，导致存在 SQL 注入漏洞，远程且未经过身份认证的攻击者可利用此漏洞进行 SQL 注入攻击，从而可窃取数据库敏感信息。长亭科技安全研究员经过分析后确认此漏洞同时影响 Ecology 9 和 8 两个版本系列，使用泛微 Ecology 的用户需尽快进行补丁更新升级。
    泛微 ecology 9.x 补丁版本号 <= v10.56
    泛微 ecology 8.x 补丁版本号 <= v10.56
    app="泛微-协同商务系统"
    app="泛微-协同办公OA"
  reference:
    - https://stack.chaitin.com/techblog/detail?id=81

rules:
  r0:
    request:
      method: GET
      path: /mobile/plugin/CheckServer.jsp?type=mobileSetting
    expression: response.status == 200 && response.body.bcontains(b'"error":"system error"') && response.headers["content-type"].contains("application/json") && !response.raw_header.bcontains(b"securityIntercept")
expression: r0()