FastUsr: 
  - fast.exe
SonicWALL: 
  - SWAGENT.exe
  - SWDOCTOR.exe
Avast Anti-virus: 
  - ASHSERV.exe
EUNIVERSE INC: 
  - keenvalue.exe
Integrated Search Technologies: 
  - powerscan.exe
Spyware Doctor: 
  - SDHELP.exe
ESET NOD32: 
  - egui.exe
  - ekrn.exe
  - eguiProxy.exe
  - NOD32.exe
  - EShaSrv.exe
Avira(小红伞): 
  - avcenter.exe
  - avguard.exe
  - avgnt.exe
  - sched.exe
BullGuard: 
  - mgui.exe
System Soap Pro: 
  - soap.exe
Ewido Security Suite: 
  - EWIDOCTRL.exe
VIRUSfighter杀毒: 
  - AVWatchService.exe
Silicon Integrated Systems Corporation: 
  - htpatch.exe
CBlaster: 
  - blss.exe
MicroSmarts Enterprise Component : 
  - showbehind.exe
eTrust: 
  - vettray.exe
  - INOCIT.exe
  - INORPC.exe
  - INORT.exe
  - INOTASK.exe
  - INOUPTNG.exe
  - ISAFE.exe
Real-time Virus Scanner: 
  - RTVSCN95.exe
熊猫卫士: 
  - remupd.exe
  - APVXDWIN.exe
  - AVCIMAN.exe
  - AVENGINE.exe
  - PAVFIRES.exe
  - PAVFNSVR.exe
  - PAVKRE.exe
  - PAVPROT.exe
  - PAVPROXY.exe
  - PAVPRSRV.exe
  - PAVSRV51.exe
  - PAVSS.exe
  - PREVSRV.exe
Kaspersky Anti-Virus: 
  - avp32.exe
Prizesurfer: 
  - prizesurfer.exe
Immunet杀毒: 
  - iptray.exe
nProtect杀毒: 
  - nspupsvc.exe
天网防火墙: 
  - pfw.exe
Kerio MailServer: 
  - AVSERVER.exe
NortonAntiVirus: 
  - poproxy.exe
Total Velocity: 
  - tvtmd.exe
ewido: 
  - guard.exe
  - guarddog.exe
Shield Antivirus杀毒: 
  - CKSoftShiedAntivirus4.exe
MyFreeInternetUpdate: 
  - mfin32.exe
  - mfw2en.exe
  - mfweng3.02d30.exe
NeoWatch: 
  - NEOWATCHLOG.exe
  - NEOWATCHTRAY.exe
Ikarus: 
  - PESTPATROL.exe
Msviewparasite: 
  - infwin.exe
Alwil: 
  - ASHMAISV.exe
Sysmantec: 
  - SYMSPORT.exe
  - SYMWSC.exe
  - SYNMGR.exe
飞塔: 
  - FortiTray.exe
AVG: 
  - aAvgApi.exe
  - avgcc32.exe
  - avgctrl.exe
  - avgemc.exe
  - avgrsx.exe
  - avgserv.exe
  - avgserv9.exe
  - avgw.exe
  - AVGAM.exe
  - AVGCC.exe
  - AVGCHSVX.exe
  - AVGCSRVX
  - AVGNSX.exe
  - AVGCC32.exe
  - AVGCTRL.exe
  - AVGEMC.exe
  - AVGFWSRV.exe
  - AVGNTMGR.exe
  - AVGSERV.exe
  - AVGTRAY.exe
  - AVGUPSVC.exe
F-PROT Antivirus: 
  - FPROTTRAY.exe
Anti-Virus: 
  - TNBUTIL.exe
OpiStat: 
  - prmt.exe
网游保镖: 
  - GUARDGUI.exe
木马猎手: 
  - TrojanHunter.exe
超级巡警: 
  - AST.exe
AshampooSoftware: 
  - firewall.exe
  - FIREWALL.exe
Application Request Route: 
  - arr.exe
Panda Software Aplication: 
  - avltmain.exe
TitanHide: 
  - titanin.exe
Spybot : 
  - SPYBOTSD.exe
AntiVirus AutoUpdater: 
  - autodown.exe
Norton AntiVirus: 
  - alertsvc.exe
  - navapsvc.exe
  - navapw32.exe
  - ADVCHK.exe
  - ALERTSVC.exe
  - cfgwiz.exe
  - defwatch.exe
  - navw32.exe
  - sbserv.exe
  - DEFWATCH.exe
  - NAVW32.exe
G DATA SOFTWARE AG: 
  - avkpop.exe
  - avkserv.exe
  - avkservice.exe
  - avkwctl9.exe
windows流氓软件清理大师: 
  - clean.exe
  - cleaner.exe
  - cleaner3.exe
  - cleanpc.exe
亚信防火墙: 
  - patch.exe
  - pcscan.exe
  - PCCPFW.exe
  - PCCTLCOM.exe
  - TMLISTEN.exe
  - TMNTSRV.exe
  - TMPROXY.exe
  - TmSSClient.exe
  - PccNT.exe
  - pop3trap.exe
  - PCCGUIDE.exe
  - PCCIOMON.exe
  - PCCNTMON.exe
PC-cillin趋势反病毒:
  - TMBMSRV.exe
  - ntrtscan.exe
Command AntiVirus for NT Server: 
  - AVINITNT.exe
Coranti2012杀毒: 
  - CorantiControlCenter32.exe
Avast网络安全: 
  - ashDisp.exe
WurldMediaInc: 
  - mostat.exe
诺顿磁盘医生: 
  - ndd32.exe
360安全卫士-主程序: 
  - 360safe.exe
360主机卫士:
  - 360WebSafe.exe
  - QHSrv.exe
  - QHWebshellGuard.exe
360 total security国际版:
  - 360webshield.exe
Mustek: 
  - atwatch.exe
CyberLink Corp.: 
  - cdp.exe
RationalClearCase: 
  - ethereal.exe
Dr.Web: 
  - DRWADINS.exe
  - DRWEB.exe
  - SPIDERCPL.exe
  - SPIDERML.exe
  - SPIDERUI.exe
Windows Defender: 
  - MsMpEng.exe
  - NisSrv.exe
  - MsSense.exe
  - MpCmdRun.exe
  - mssecess.exe
  - MSASCui.exe
  - MSASCuiL.exe
  - SecurityHealthService.exe
  - smartscreen.exe
风云防火墙: 
  - FYFireWall.exe
Alset Inc: 
  - emsw.exe
F-Secure: 
  - fameh32.exe
  - fch32.exe
  - fih32.exe
  - findviru.exe
  - fnrb32.exe
  - fsaa.exe
  - fsav.exe
  - fsav32.exe
  - fsav530stbyb.exe
  - fsav530wtbyb.exe
  - fsav95.exe
  - fsgk32.exe
  - fsm32.exe
  - fsma32.exe
  - fsmb32.exe
  - FSAV32.exe
  - FSDFWD.exe
  - FSGK32.exe
  - FSGK32ST.exe
  - FSMA32.exe
  - FSMB32.exe
  - FSSM32.exe
Windows Trojans Inspector: 
  - ldscan.exe
TimeCalende: 
  - tc.exe
百度卫士: 
  - bddownloader.exe
  - baiduSafeTray.exe
Grokster: 
  - bpc.exe
Avira AntiVir Security Service: 
  - AVESVC.exe
IKARUS: 
  - GUARDNT.exe
百度杀毒-主程序: 
  - BaiduSd.exe
卡巴斯基: 
  - _avp32.exe
  - _avpcc.exe
  - _avpm.exe
HAURI: 
  - VRMONNT.exe
  - VRMONSVC.exe
Norton Internet Security: 
  - ccevtmgr.exe
  - qserver.exe
AirDefense: 
  - AIRDEFENSE.exe
360安全卫士-实时保护: 
  - 360tray.exe
DrWeb CureIT: 
  - CUREIT.exe
RapidBlaster: 
  - rb32.exe
Sophos杀毒: 
  - SavProgress.exe
  - SophosUI.exe
  - SophosFS.exe
  - SophosHealth.exe
  - SophosSafestore64.exe
  - SophosCleanM.exe
  - SAVADMINSERVICE.exe
  - SAVMAIN.exe
  - SAVSCAN.exe
  - 
Intercort Systems: 
  - launcher.exe
McAfee VirusScan: 
  - alogserv.exe
贝壳云安全: 
  - beikesan.exe
Sophos: 
  - SWNETSUP.exe
EzulaInc: 
  - mmod.exe
护卫神·入侵防护系统: 
  - HwsPanel.exe
  - hws_ui.exe
  - hws.exe
  - hwsd.exe
Exact Advertising: 
  - brasil.exe
Panda Antivirus Module: 
  - iface.exe
BitDefender Module: 
  - BDSWITCH.exe
Verizon: 
  - FPWIN.exe
PSafe杀毒: 
  - PSafeSysTray.exe
微点主动防御: 
  - MPMon.exe
Reuters Limited: 
  - nav.exe
Tiny Personal Firewall: 
  - persfw.exe
  - AMON.exe
  - PERSFW.exe
墨者安全专家: 
  - ananwidget.exe
H+BEDV Datentechnik GmbH: 
  - avnt.exe
D盾: 
  - D_Safe_Manage.exe
  - d_manage.exe
K7杀毒: 
  - K7TSecurity.exe
Zone Alarm: 
  - vsmon.exe
  - zapro.exe
  - zonealarm.exe
  - MINILOG.exe
  - ZONEALARM.exe
Norton AntiVirus Quarantine Console: 
  - qconsole.exe
Avira Antivir: 
  - avgaurd.exe
NSIS: 
  - au.exe
PanicWare: 
  - dpps2.exe
Total Velocity Spyware: 
  - msmgt.exe
W32/Datom-A: 
  - msvxd.exe
PSafe Tecnologia: 
  - safeweb.exe
AVZ: 
  - AVZ.exe
a-squared杀毒: 
  - a2guard.exe
Lavasoft杀毒: 
  - ad-watch.exe
H+BEDV: 
  - AVSCHED32.exe
  - AVWUPSRV.exe
  - avwin.exe
PC Tools AntiVirus: 
  - PCTAV.exe
AVAST!VirusCleaner: 
  - ASHSIMPL.exe
VIPRE: 
  - SBAMSvc.exe
Real-time virus scanner : 
  - rtvscn95.exe
小红伞杀毒: 
  - AVIRA.exe
瑞星防火墙: 
  - rfwmain.exe
Sysinternals: 
  - processmonitor.exe
Infus Dialer: 
  - infus.exe
Anti-Trojan Elite: 
  - anti-trojan.exe
Realmon : 
  - realmon.exe
a-squared free: 
  - A2SERVICE.exe
Avast Antivirus: 
  - afwServ.exe
金山网镖: 
  - kpfwtray.exe
PrizeSurfer: 
  - rcsync.exe
360杀毒: 
  - 360sd.exe
  - scrscan.exe
  - 360rp.exe
  - safeboxTray.exe
  - 360safebox.exe
  - 360rps.exe
Norton杀毒软件: 
  - NPFMntor.exe
  - ccRegVfy.exe
GData安全防护软件: 
  - AVK.exe
  - GDScan.exe
  - AVKWCtl.exe
  - AVKCl.exe
  - AVKProxy.exe
  - AVKBackupService.exe
百度卫士-主进程: 
  - baiduansvx.exe
Emsisoft Anti-Malware: 
  - A2CMD.exe
UnThreat杀毒: 
  - UnThreat.exe
比特梵德: 
  - vsserv.exe
OdysseusMarketingInc: 
  - mscman.exe
eScorcher反病毒: 
  - supporter5.exe
安天防线: 
  - AGB.exe
  - AHPROCMONSERVER.exe
F-secure: 
  - FSBWSYS.exe
木马克星: 
  - parmor.exe
  - Iparmor.exe.exe
Avast!5主程序: 
  - AvastUI.exe
Norton: 
  - lucomserver.exe
  - nisserv.exe
  - nisum.exe
  - nmain.exe
  - npscheck.exe
  - npssvc.exe
  - NAVAPSVC.exe
  - NAVAPW32.exe
  - NAVLU32.exe
  - NISSERV.exe
  - NISUM.exe
  - NMAIN.exe
  - NSMDTR.exe
OutpostFirewall: 
  - OP_MON.exe
绿鹰安全精灵: 
  - adam.exe
AVG杀毒: 
  - avg.exe
  - avgwdsvc.exe
腾讯电脑管家: 
  - QQPCRTP.exe
  - QQProtect.exe
  - QQPCTray.exe
  - QQPCNetFlow.exe
  - QQPCRealTimeSpeedup.exe
云锁: 
  - yunsuo_agent_service.exe
  - yunsuo_agent_daemon.exe
  - PC.exe
GovDefence(网防G01):
  - gov_defence_service.exe
  - gov_defence_daemon.exe
SPHINX防火墙: 
  - SPHINX.exe
Outpost: 
  - outpostinstall.exe
卡巴斯基互联网安全套装: 
  - rescue32.exe
ClamAV: 
  - FRESHCLAM.exe
The Cleaner杀毒: 
  - cleaner8.exe
Bkav杀毒: 
  - BKavService.exe
Motive Communications: 
  - cfd.exe
ClamWin Portable: 
  - CLAMWIN.exe
VirusChaser: 
  - VCRMON.exe
QUICK HEAL杀毒: 
  - QUHLPSVC.exe
安全狗: 
  - safedog.exe
  - safedogupdatecenter.exe
  - safedogguardcenter.exe
  - SafeDogSiteIIS.exe
  - SafeDogTray.exe
  - SafeDogServerUI.exe
  - CloudHelper.exe
  - SafeDogSiteApache.exe
  - SafeDogServerUI.exe
已知杀软进程,名称暂未收录: 
  - ackwin32.exe
  - atupdater.exe
  - auto-protect.nav80try.exe
  - claw95.exe
  - claw95cf.exe
  - ctrl.exe
  - cv.exe
  - doors.exe
  - dpf.exe
  - ecengine.exe
  - ent.exe
  - espwatch.exe
  - exe.avxw.exe
  - expert.exe
  - f-prot95.exe
  - gbmenu.exe
  - htlog.exe
  - hwpe.exe
  - intren.exe
  - jammer.exe
  - ldpro.exe
  - localnet.exe
  - mwatch.exe
  - neowatchlog.exe
  - netutils.exe
  - norton_internet_secu_3.0_407.exe
  - notstart.exe
  - nui.exe
  - otfix.exe
  - pavw.exe
  - pdsetup.exe
  - pingscan.exe
  - platin.exe
  - popscan.exe
  - ppinupdt.exe
  - pptbc.exe
  - ppvstop.exe
  - proport.exe
  - pspf.exe
  - purge.exe
  - rescue.exe
  - rshell.exe
  - sofi.exe
  - sperm.exe
  - vir-help.exe
  - vnpc3000.exe
  - wfindv32.exe
  - ANTIVIR.exe
  - AVEVL32.exe
  - ONLINENT.exe
  - PERVAC.exe
  - VBA32ECM.exe
  - VBA32IFS.exe
  - VBA32PP3.exe
Zone Labs Inc: 
  - minilog.exe
ProtectX: 
  - protectx.exe
ShadowDefender: 
  - DEFENDERDAEMON.exe
360安全卫士-主动防御: 
  - ZhuDongFangYu.exe
F-Secure杀毒: 
  - fsavgui.exe
Integrated Search Technologies Spyware: 
  - mscache.exe
PromulGate SpyWare: 
  - pgmonitr.exe
McAfee(麦咖啡): 
  - Mcshield.exe
  - Tbmon.exe
  - Frameworkservice.exe
  - firesvc.exe
  - firetray.exe
  - hipsvc.exe
  - mfevtps.exe
  - mcafeefire.exe
  - scan32.exe
  - shstat.exe
  - vstskmgr.exe
  - engineserver.exe
  - mfeann.exe
  - mcscript.exe
  - updaterui.exe
  - udaterui.exe
  - naprdmgr.exe
  - cleanup.exe
  - cmdagent.exe
  - frminst.exe
  - mcscript_inuse.exe
  - mctray.exe
  - avconsol.exe
  - avsynmgr.exe
  - cpd.exe
  - mcagent.exe
  - mcmnhdlr.exe
  - mctool.exe
  - mcupdate.exe
  - mcvsrte.exe
  - mcvsshld.exe
  - mgavrtcl.exe
  - mgavrte.exe
  - mghtml.exe
  - mpfagent.exe
  - mpfservice.exe
  - mpftray.exe
  - vshwin32.exe
  - vsmain.exe
  - vsstat.exe
  - AVCONSOL.exe
  - AVSYNMGR.exe
  - MCAGENT.exe
  - MCMNHDLR.exe
  - MCREGWIZ.exe
  - MCUPDATE.exe
  - MCVSSHLD.exe
  - MYAGTSVC.exe
  - MYAGTTRY.exe
  - SHSTAT.exe
  - VSHWIN32.exe
  - VSSTAT.exe
Dr.web: 
  - spidernt.exe
Adtomi: 
  - prmvr.exe
可牛杀毒: 
  - knsdtray.exe
SymantecNorton: 
  - ccapp.exe
金山网盾: 
  - KSWebShield.exe
Kaspersky(卡巴斯基): 
  - avpcc.exe
  - avpdos32.exe
  - avpm.exe
  - avptc32.exe
  - avpupd.exe
  - avp.exe
  - AVPM.exe
  - AVPCC.exe
  - KAV.exe
  - KAVMM.exe
  - KAVPF.exe
  - KAVPFW.exe
  - KAVSTART.exe
  - KAVSVC.exe
  - KAVSVCUI.exe
  - kavfs.exe
  - klnagent.exe
  - kavtray.exe
  - kavfswp.exe
F-Prot Antivirus OnDemand: 
  - fp-win.exe
ESET Smart Security: 
  - nod32.exe
EMET: 
  - emet_agent.exe
  - emet_service.exe
Symantec(赛门铁克): 
  - aupdate.exe
  - bootwarn.exe
  - defalert.exe
  - defscangui.exe
  - iamapp.exe
  - iamserv.exe
  - iamstats.exe
  - luall.exe
  - luau.exe
  - nprotect.exe
  - symproxysvc.exe
  - symtray.exe
  - vpc32.exe
  - vpc42.exe
  - CCEVTMGR.exe
  - IAMAPP.exe
  - NPROTECT.exe
  - SYMPROXYSVC.exe
  - ccSetMgr.exe
  - ccsvchst.exe
  - rtvscan.exe
  - smc.exe
  - smcGui.exe
  - snac.exe
  - SymCorpUI.exe
Broderbund: 
  - dssagent.exe
金山毒霸: 
  - kxetray.exe
  - KMAILMON.exe
  - KSafeTray.exe
  - KSafeSvc.exe
  - KWatch.exe
  - kxescore.exe
  - kupdata.exe
  - kwsprotect64.exe
百度杀毒-托盘进程: 
  - BaiduSdTray.exe
Exact Advertising SpyWare: 
  - bargains.exe
Avast: 
  - beagle.exe
  - ASHWEBSV.exe
  - ASWUPDSV.exe
  - ASWSCAN.exe
PAL PC Spy: 
  - run32dll.exe
System file checker: 
  - sfc.exe
ThunderBYTE: 
  - tbscan.exe
百度杀毒-服务进程: 
  - BaiduSdSvc.exe
火绒: 
  - hipstray.exe
  - wsctrl.exe
  - usysdiag.exe
  - HipsDaemon.exe
  - HipsLog.exe
  - HipsMain.exe
瑞星杀毒: 
  - RavMonD.exe
AntiVir: 
  - atguard.exe
Norton(诺顿杀毒): 
  - rtvscan.exe
  - ccSvcHst.exe
  - ns.exe
  - ccapp.exe
BlackICE: 
  - blackd.exe
  - blackice.exe
  - rapapp.exe
  - BLACKD.exe
Inet Delivery: 
  - intdel.exe
e-Trust Antivirus: 
  - EZANTIVIRUSREGISTRATIONCHECK.exe
OfficeScanNT: 
  - OFCPFWSVC.exe
F-Prot AntiVirus: 
  - F-PROT.exe
江民杀毒: 
  - KvMonXP.exe
MKS Toolkit for Win3: 
  - sh.exe
Norman个人防火墙: 
  - NPFMSG.exe
BitDefender: 
  - XCOMMSVR.exe
Comodo: 
  - cpf.exe
Kapersky: 
  - kavpf.exe
  - kazza.exe
micromedia: 
  - blink.exe
Urlblaze.com: 
  - iedriver.exe
COMODO: 
  - CFP.exe
CMC杀毒: 
  - CMCTrayIcon.exe
巨盾网游安全盾: 
  - GG.exe
SpywareTerminator反间谍软件: 
  - SpywareTerminatorShield.exe
McAfee User Interface: 
  - rulaunch.exe
vb32杀毒: 
  - vba32lder.exe
Mongoosa杀毒: 
  - MongoosaGUI.exe
金山卫士: 
  - ksafe.exe
a-squared Free: 
  - A2FREE.exe
ArcaVir杀毒: 
  - ArcaTasksService.exe
冰岛: 
  - f-secure.exe
阿里云盾:
  - AliYunDun.exe
  - AliHips.exe
  - AliYunDunUpdate.exe
  - aliyun_assist_service.exe
  - AliYunDunMonitor.exe
  - AliNetFilter.exe
阿里云检测程序:
  - AliDetect.exe
奇安信天擎:
  - QaxEngManager.exe
泰合安全管理平台(TSOC):
  - TSocSensor.exe
深信服 EDR 设备:
  - edr_monitor.exe
  - edr_agent.exe
景云防病毒:
  - JingYunMonSvr.exe
  - JingyunSdMainSvr.exe
  - JingyunSdSvr.exe
  - JingyunSdTray.exe
腾讯云镜:
  - YDService.exe
  - YDLive.exe
  - QCloudService.exe
  - sgagent.exe
  - YDEdr.exe
天眼云镜:
  - TitanAgent.exe
  - TitanMonitor.exe
阿里云骑士监控:
  - AliSecGuard.exe
天融信安全产品:
  - topsecusysdiag.exe
360更新程序:
  - LiveUpdate360.exe
360天擎终端安全管理系统:
  - 360skylarsvc.exe
  - 360Entclient.exe
Malwarebytes杀毒:
  - mbam.exe
  - mbamtray.exe
  - MBAMService.exe
ClemWin Free Antivirus:
  - ClamTray.exe
  - clamscan.exe
Ahnlab安博士杀毒:
  - patray.exe
  - V3Svc.exe
BitDefender杀毒:
  - secenter.exe
ALYac韩国胶囊杀毒:
  - AYAgent.exe
Norton病毒防火墙-盾牌图标程序:
  - vptray.exe
Symantec Shared诺顿邮件防火墙软件:
  - SNDSrvc.exe
  - SPBBCSVC.exe
  - SYMLCSVC.exe
U盘杀毒专家:
  - USBKiller.exe
百度云管家:
  - YunDetectService.exe
启明星辰天珣EDR Agent:
  - ESCCControl.exe
  - ESCC.exe
  - ESAV.exe
  - ESCCIndex.exe
网络病毒克星:
  - WEBSCANX.EXE
Outpost防火墙:
  - acs.exe
  - outpost.exe
SunloginClient(向日葵客户端):
  - SunloginClient.exe
MobaXterm 终端程序:
  - MobaXterm.exe
ToDesk 远程控制软件:
  - ToDesk.exe
  - ToDesk_Lite.exe
终端模拟软件 Xshell:
  - Xshell.exe
远端X窗口工具 Xmanager:
  - Xmanager.exe
SecureCRT:
  - SecureCRT.exe
内网穿透工具NPS客户端:
  - npc.exe
  - nps.exe
内网穿透工具FRP客户端:
  - frpc.exe
  - frps.exe
VMware虚拟机:
  - vmware.exe