id: heapdump-detect

info:
  name: Spring heapdump Detect
  author: dogasantos
  severity: high
  verified: true
  description: heapdump detection

rules:
  r0:
    request:
      method: GET
      path: /heapdump
    expression: response.status == 200 && response.headers["content-type"].contains("application/octet-stream")
  r1:
    request:
      method: GET
      path: /actuator/heapdump
    expression: response.status == 200 && response.headers["content-type"].contains("application/octet-stream")
expression: r0() || r1()