// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {structs} from '../models';
import {dirsearch} from '../models';
import {context} from '../models';
import {space} from '../models';

export function AnalyzeAPI(arg1:string,arg2:string,arg3:Array<string>,arg4:{[key: string]: string},arg5:{[key: string]: string},arg6:Array<string>,arg7:Array<string>):Promise<void>;

export function Callgologger(arg1:string,arg2:string):Promise<void>;

export function CyberChefLocalServer():Promise<void>;

export function DownloadCyberChef(arg1:string):Promise<void>;

export function EnrichCompanyWithMiit(arg1:structs.CompanyInfo,arg2:string):Promise<void>;

export function ExitScanner(arg1:string):Promise<void>;

export function ExtractAllJSLink(arg1:string):Promise<Array<string>>;

export function FaviconMd5(arg1:string):Promise<string>;

export function FetchCompanyInfo(arg1:string,arg2:number,arg3:structs.DataSource,arg4:number):Promise<structs.CompanyInfo>;

export function FingerprintList():Promise<Array<string>>;

export function FofaSearch(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean,arg8:boolean):Promise<structs.FofaSearchResult>;

export function FofaTips(arg1:string):Promise<structs.TipsResult>;

export function GetFingerPocMap():Promise<{[key: string]: Array<string>}>;

export function GitDorks(arg1:string,arg2:string,arg3:string):Promise<structs.ISICollectionResult>;

export function GoFetch(arg1:string,arg2:string,arg3:any,arg4:{[key: string]: string},arg5:number,arg6:string):Promise<structs.Response>;

export function GoogleHackerBingSearch(arg1:string):Promise<structs.ISICollectionResult>;

export function HostAlive(arg1:Array<string>,arg2:boolean):Promise<Array<string>>;

export function HunterSearch(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:boolean):Promise<structs.HunterResult>;

export function HunterTips(arg1:string):Promise<structs.HunterTips>;

export function IconHash(arg1:string):Promise<string>;

export function InitRule(arg1:string):Promise<boolean>;

export function IpLocation(arg1:string):Promise<string>;

export function JSFind(arg1:string,arg2:string,arg3:Array<string>,arg4:Array<string>):Promise<structs.FindSomething>;

export function LoadDirsearchDict(arg1:Array<string>,arg2:Array<string>):Promise<Array<string>>;

export function NetDial(arg1:string):Promise<boolean>;

export function NewCrackScanenr(arg1:string,arg2:string,arg3:Array<string>,arg4:Array<string>):Promise<void>;

export function NewDSStoreEngine(arg1:string):Promise<Array<string>>;

export function NewDirsearchScanner(arg1:dirsearch.Options):Promise<void>;

export function NewTcpScanner(arg1:string,arg2:Array<string>,arg3:Array<string>,arg4:Array<number>,arg5:number,arg6:number,arg7:string):Promise<void>;

export function NewWebScanner(arg1:string,arg2:structs.WebscanOptions,arg3:string,arg4:boolean):Promise<void>;

export function QuakeSearch(arg1:Array<string>,arg2:string,arg3:number,arg4:number,arg5:boolean,arg6:boolean,arg7:boolean,arg8:boolean,arg9:string,arg10:string):Promise<structs.QuakeResult>;

export function QuakeTips(arg1:string):Promise<structs.QuakeTipsResult>;

export function ResumeAfterHumanCheck():Promise<void>;

export function SendRequest(arg1:string,arg2:boolean,arg3:boolean,arg4:string):Promise<structs.RawResponse>;

export function Socks5Conn(arg1:string,arg2:number,arg3:number,arg4:string,arg5:string,arg6:string):Promise<boolean>;

export function SpaceGetPort(arg1:string):Promise<Array<number>>;

export function Startup(arg1:context.Context):Promise<void>;

export function Subdomain(arg1:structs.SubdomainOption):Promise<void>;

export function UncoverSearch(arg1:string,arg2:string,arg3:structs.SpaceOption):Promise<Array<space.Result>>;

export function WriteCompanyInfoToJson(arg1:structs.CompanyInfo):Promise<boolean>;
