// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dirsearch} from '../models';
import {structs} from '../models';
import {isic} from '../models';
import {clients} from '../models';
import {context} from '../models';
import {space} from '../models';

export function AnalyzeAPI(arg1:string,arg2:string,arg3:Array<string>,arg4:{[key: string]: string},arg5:Array<string>):Promise<void>;

export function Callgologger(arg1:string,arg2:string):Promise<void>;

export function CheckCdn(arg1:string):Promise<string>;

export function CyberChefLocalServer():Promise<void>;

export function DirScan(arg1:dirsearch.Options):Promise<void>;

export function DownloadCyberChef(arg1:string):Promise<void>;

export function ExitScanner(arg1:string):Promise<void>;

export function ExtractAllJSLink(arg1:string):Promise<Array<string>>;

export function FaviconMd5(arg1:string):Promise<string>;

export function FingerprintList():Promise<Array<string>>;

export function FofaSearch(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean,arg8:boolean):Promise<structs.FofaSearchResult>;

export function FofaTips(arg1:string):Promise<structs.TipsResult>;

export function GetAllFinger():Promise<Array<string>>;

export function GetFingerPocMap():Promise<{[key: string]: Array<string>}>;

export function GitDorks(arg1:string,arg2:string,arg3:string):Promise<isic.GithubResult>;

export function GoFetch(arg1:string,arg2:string,arg3:any,arg4:{[key: string]: string},arg5:number,arg6:clients.Proxy):Promise<structs.Response>;

export function HostAlive(arg1:Array<string>,arg2:boolean):Promise<Array<string>>;

export function HunterSearch(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean):Promise<structs.HunterResult>;

export function HunterTips(arg1:string):Promise<structs.HunterTips>;

export function ICPInfo(arg1:string):Promise<string>;

export function IconHash(arg1:string):Promise<string>;

export function InitRule(arg1:string):Promise<boolean>;

export function Ip138IpHistory(arg1:string):Promise<string>;

export function Ip138Subdomain(arg1:string):Promise<string>;

export function IpLocation(arg1:string):Promise<string>;

export function JSFind(arg1:string,arg2:string,arg3:Array<string>):Promise<structs.FindSomething>;

export function LoadDirsearchDict(arg1:Array<string>,arg2:Array<string>):Promise<Array<string>>;

export function NetDial(arg1:string):Promise<boolean>;

export function NewDSStoreEngine(arg1:string):Promise<Array<string>>;

export function NewTcpScanner(arg1:Array<string>,arg2:Array<string>,arg3:Array<number>,arg4:number,arg5:number,arg6:clients.Proxy):Promise<void>;

export function NewThreadSafeWebScanner(arg1:structs.WebscanOptions,arg2:clients.Proxy):Promise<void>;

export function NewWebScanner(arg1:structs.WebscanOptions,arg2:clients.Proxy):Promise<void>;

export function PortBrute(arg1:string,arg2:Array<string>,arg3:Array<string>):Promise<void>;

export function QuakeSearch(arg1:Array<string>,arg2:string,arg3:number,arg4:number,arg5:boolean,arg6:boolean,arg7:boolean,arg8:boolean,arg9:string,arg10:string):Promise<structs.QuakeResult>;

export function QuakeTips(arg1:string):Promise<structs.QuakeTipsResult>;

export function Socks5Conn(arg1:string,arg2:number,arg3:number,arg4:string,arg5:string,arg6:string):Promise<boolean>;

export function SpaceGetPort(arg1:string):Promise<Array<number>>;

export function Startup(arg1:context.Context):Promise<void>;

export function Subdomain(arg1:structs.SubdomainOption):Promise<void>;

export function SubsidiariesAndDomains(arg1:string,arg2:number,arg3:number,arg4:boolean,arg5:string):Promise<Array<structs.CompanyInfo>>;

export function TycCheckLogin(arg1:string):Promise<boolean>;

export function UncoverSearch(arg1:string,arg2:string,arg3:structs.SpaceOption):Promise<Array<space.Result>>;

export function ViewPictrue(arg1:string):Promise<string>;

export function WechatOfficial(arg1:string):Promise<Array<structs.WechatReulst>>;
