// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeAPI(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['services']['App']['AnalyzeAPI'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function Callgologger(arg1, arg2) {
  return window['go']['services']['App']['Callgologger'](arg1, arg2);
}

export function CheckCdn(arg1) {
  return window['go']['services']['App']['CheckCdn'](arg1);
}

export function CyberChefLocalServer() {
  return window['go']['services']['App']['CyberChefLocalServer']();
}

export function DirScan(arg1) {
  return window['go']['services']['App']['DirScan'](arg1);
}

export function DownloadCyberChef(arg1) {
  return window['go']['services']['App']['DownloadCyberChef'](arg1);
}

export function ExitScanner(arg1) {
  return window['go']['services']['App']['ExitScanner'](arg1);
}

export function ExtractAllJSLink(arg1) {
  return window['go']['services']['App']['ExtractAllJSLink'](arg1);
}

export function FaviconMd5(arg1) {
  return window['go']['services']['App']['FaviconMd5'](arg1);
}

export function FingerprintList() {
  return window['go']['services']['App']['FingerprintList']();
}

export function FofaSearch(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['services']['App']['FofaSearch'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function FofaTips(arg1) {
  return window['go']['services']['App']['FofaTips'](arg1);
}

export function GetFingerPocMap() {
  return window['go']['services']['App']['GetFingerPocMap']();
}

export function GitDorks(arg1, arg2, arg3) {
  return window['go']['services']['App']['GitDorks'](arg1, arg2, arg3);
}

export function GoFetch(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['services']['App']['GoFetch'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function HostAlive(arg1, arg2) {
  return window['go']['services']['App']['HostAlive'](arg1, arg2);
}

export function HunterSearch(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['services']['App']['HunterSearch'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function HunterTips(arg1) {
  return window['go']['services']['App']['HunterTips'](arg1);
}

export function ICPInfo(arg1) {
  return window['go']['services']['App']['ICPInfo'](arg1);
}

export function IconHash(arg1) {
  return window['go']['services']['App']['IconHash'](arg1);
}

export function InitRule(arg1) {
  return window['go']['services']['App']['InitRule'](arg1);
}

export function Ip138IpHistory(arg1) {
  return window['go']['services']['App']['Ip138IpHistory'](arg1);
}

export function Ip138Subdomain(arg1) {
  return window['go']['services']['App']['Ip138Subdomain'](arg1);
}

export function IpLocation(arg1) {
  return window['go']['services']['App']['IpLocation'](arg1);
}

export function JSFind(arg1, arg2, arg3) {
  return window['go']['services']['App']['JSFind'](arg1, arg2, arg3);
}

export function LoadDirsearchDict(arg1, arg2) {
  return window['go']['services']['App']['LoadDirsearchDict'](arg1, arg2);
}

export function NetDial(arg1) {
  return window['go']['services']['App']['NetDial'](arg1);
}

export function NewDSStoreEngine(arg1) {
  return window['go']['services']['App']['NewDSStoreEngine'](arg1);
}

export function NewTcpScanner(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['services']['App']['NewTcpScanner'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function NewWebScanner(arg1, arg2, arg3, arg4) {
  return window['go']['services']['App']['NewWebScanner'](arg1, arg2, arg3, arg4);
}

export function PortBrute(arg1, arg2, arg3, arg4) {
  return window['go']['services']['App']['PortBrute'](arg1, arg2, arg3, arg4);
}

export function QuakeSearch(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['services']['App']['QuakeSearch'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function QuakeTips(arg1) {
  return window['go']['services']['App']['QuakeTips'](arg1);
}

export function Socks5Conn(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['services']['App']['Socks5Conn'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SpaceGetPort(arg1) {
  return window['go']['services']['App']['SpaceGetPort'](arg1);
}

export function Startup(arg1) {
  return window['go']['services']['App']['Startup'](arg1);
}

export function Subdomain(arg1) {
  return window['go']['services']['App']['Subdomain'](arg1);
}

export function SubsidiariesAndDomains(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['App']['SubsidiariesAndDomains'](arg1, arg2, arg3, arg4, arg5);
}

export function TycCheckLogin(arg1) {
  return window['go']['services']['App']['TycCheckLogin'](arg1);
}

export function UncoverSearch(arg1, arg2, arg3) {
  return window['go']['services']['App']['UncoverSearch'](arg1, arg2, arg3);
}

export function WechatOfficial(arg1) {
  return window['go']['services']['App']['WechatOfficial'](arg1);
}
