// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnection(arg1) {
  return window['go']['services']['Database']['AddConnection'](arg1);
}

export function AddFingerscanResult(arg1, arg2) {
  return window['go']['services']['Database']['AddFingerscanResult'](arg1, arg2);
}

export function AddPocscanResult(arg1, arg2) {
  return window['go']['services']['Database']['AddPocscanResult'](arg1, arg2);
}

export function AddScanTask(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['Database']['AddScanTask'](arg1, arg2, arg3, arg4, arg5);
}

export function ConnectDatabase(arg1) {
  return window['go']['services']['Database']['ConnectDatabase'](arg1);
}

export function ConnectMongodb(arg1, arg2, arg3) {
  return window['go']['services']['Database']['ConnectMongodb'](arg1, arg2, arg3);
}

export function CreateTable() {
  return window['go']['services']['Database']['CreateTable']();
}

export function DisconnectDatabase(arg1) {
  return window['go']['services']['Database']['DisconnectDatabase'](arg1);
}

export function ExecSqlStatement(arg1, arg2) {
  return window['go']['services']['Database']['ExecSqlStatement'](arg1, arg2);
}

export function ExportWebReportWithHtml(arg1, arg2) {
  return window['go']['services']['Database']['ExportWebReportWithHtml'](arg1, arg2);
}

export function ExportWebReportWithJson(arg1, arg2) {
  return window['go']['services']['Database']['ExportWebReportWithJson'](arg1, arg2);
}

export function FetchDatabaseInfoFromOracle() {
  return window['go']['services']['Database']['FetchDatabaseInfoFromOracle']();
}

export function FetchDatabaseInfoFromPostgres(arg1) {
  return window['go']['services']['Database']['FetchDatabaseInfoFromPostgres'](arg1);
}

export function FetchDatabaseinfoFromMongodb() {
  return window['go']['services']['Database']['FetchDatabaseinfoFromMongodb']();
}

export function FetchDatabaseinfoFromMysql() {
  return window['go']['services']['Database']['FetchDatabaseinfoFromMysql']();
}

export function FetchDatabaseinfoFromSqlServer() {
  return window['go']['services']['Database']['FetchDatabaseinfoFromSqlServer']();
}

export function FetchTableInfoFromMysql(arg1, arg2) {
  return window['go']['services']['Database']['FetchTableInfoFromMysql'](arg1, arg2);
}

export function FetchTableInfoFromOracle(arg1, arg2) {
  return window['go']['services']['Database']['FetchTableInfoFromOracle'](arg1, arg2);
}

export function FetchTableInfoFromPostgres(arg1, arg2) {
  return window['go']['services']['Database']['FetchTableInfoFromPostgres'](arg1, arg2);
}

export function FetchTableInfoFromSqlServer(arg1, arg2) {
  return window['go']['services']['Database']['FetchTableInfoFromSqlServer'](arg1, arg2);
}

export function GetAllDatabaseConnections() {
  return window['go']['services']['Database']['GetAllDatabaseConnections']();
}

export function GetAllPathsAndTimes() {
  return window['go']['services']['Database']['GetAllPathsAndTimes']();
}

export function InsertFavGrammarFiled(arg1, arg2, arg3) {
  return window['go']['services']['Database']['InsertFavGrammarFiled'](arg1, arg2, arg3);
}

export function ReadWebReportWithJson(arg1) {
  return window['go']['services']['Database']['ReadWebReportWithJson'](arg1);
}

export function RemoveConnection(arg1) {
  return window['go']['services']['Database']['RemoveConnection'](arg1);
}

export function RemoveFavGrammarFiled(arg1, arg2, arg3) {
  return window['go']['services']['Database']['RemoveFavGrammarFiled'](arg1, arg2, arg3);
}

export function RemovePocscanResult(arg1, arg2, arg3) {
  return window['go']['services']['Database']['RemovePocscanResult'](arg1, arg2, arg3);
}

export function RemoveScanTask(arg1) {
  return window['go']['services']['Database']['RemoveScanTask'](arg1);
}

export function RenameScanTask(arg1, arg2) {
  return window['go']['services']['Database']['RenameScanTask'](arg1, arg2);
}

export function RetrieveAllScanTasks() {
  return window['go']['services']['Database']['RetrieveAllScanTasks']();
}

export function RetrieveFingerscanResults(arg1) {
  return window['go']['services']['Database']['RetrieveFingerscanResults'](arg1);
}

export function RetrievePocscanResults(arg1) {
  return window['go']['services']['Database']['RetrievePocscanResults'](arg1);
}

export function SearchAgentPool() {
  return window['go']['services']['Database']['SearchAgentPool']();
}

export function SelectAllSyntax(arg1) {
  return window['go']['services']['Database']['SelectAllSyntax'](arg1);
}

export function Startup(arg1) {
  return window['go']['services']['Database']['Startup'](arg1);
}

export function UpdateConnection(arg1) {
  return window['go']['services']['Database']['UpdateConnection'](arg1);
}

export function UpdateOrInsertPath(arg1) {
  return window['go']['services']['Database']['UpdateOrInsertPath'](arg1);
}

export function UpdateScanTaskWithResults(arg1, arg2, arg3) {
  return window['go']['services']['Database']['UpdateScanTaskWithResults'](arg1, arg2, arg3);
}
