// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnection(arg1) {
  return window['go']['services']['Database']['AddConnection'](arg1);
}

export function ConnectDatabase(arg1) {
  return window['go']['services']['Database']['ConnectDatabase'](arg1);
}

export function ConnectMongodb(arg1, arg2, arg3) {
  return window['go']['services']['Database']['ConnectMongodb'](arg1, arg2, arg3);
}

export function CreateTable() {
  return window['go']['services']['Database']['CreateTable']();
}

export function DeletePocscanResult(arg1, arg2, arg3) {
  return window['go']['services']['Database']['DeletePocscanResult'](arg1, arg2, arg3);
}

export function DeleteScanTask(arg1) {
  return window['go']['services']['Database']['DeleteScanTask'](arg1);
}

export function DisconnectDatabase(arg1) {
  return window['go']['services']['Database']['DisconnectDatabase'](arg1);
}

export function ExecSqlStatement(arg1, arg2) {
  return window['go']['services']['Database']['ExecSqlStatement'](arg1, arg2);
}

export function ExportWebReportWithHtml(arg1, arg2) {
  return window['go']['services']['Database']['ExportWebReportWithHtml'](arg1, arg2);
}

export function ExportWebReportWithJson(arg1, arg2) {
  return window['go']['services']['Database']['ExportWebReportWithJson'](arg1, arg2);
}

export function FetchDatabaseInfoFromOracle() {
  return window['go']['services']['Database']['FetchDatabaseInfoFromOracle']();
}

export function FetchDatabaseInfoFromPostgres() {
  return window['go']['services']['Database']['FetchDatabaseInfoFromPostgres']();
}

export function FetchDatabaseinfoFromMongodb() {
  return window['go']['services']['Database']['FetchDatabaseinfoFromMongodb']();
}

export function FetchDatabaseinfoFromMysql() {
  return window['go']['services']['Database']['FetchDatabaseinfoFromMysql']();
}

export function FetchDatabaseinfoFromSqlServer() {
  return window['go']['services']['Database']['FetchDatabaseinfoFromSqlServer']();
}

export function FetchTableInfoFromMysql(arg1, arg2) {
  return window['go']['services']['Database']['FetchTableInfoFromMysql'](arg1, arg2);
}

export function FetchTableInfoFromOracle(arg1, arg2) {
  return window['go']['services']['Database']['FetchTableInfoFromOracle'](arg1, arg2);
}

export function FetchTableInfoFromPostgres(arg1, arg2) {
  return window['go']['services']['Database']['FetchTableInfoFromPostgres'](arg1, arg2);
}

export function FetchTableInfoFromSqlServer(arg1, arg2) {
  return window['go']['services']['Database']['FetchTableInfoFromSqlServer'](arg1, arg2);
}

export function GetAllDatabaseConnections() {
  return window['go']['services']['Database']['GetAllDatabaseConnections']();
}

export function GetAllPathsAndTimes() {
  return window['go']['services']['Database']['GetAllPathsAndTimes']();
}

export function GetAllScanTask() {
  return window['go']['services']['Database']['GetAllScanTask']();
}

export function InsertFavGrammarFiled(arg1, arg2, arg3) {
  return window['go']['services']['Database']['InsertFavGrammarFiled'](arg1, arg2, arg3);
}

export function InsertFingerscanResult(arg1, arg2) {
  return window['go']['services']['Database']['InsertFingerscanResult'](arg1, arg2);
}

export function InsertPocscanResult(arg1, arg2) {
  return window['go']['services']['Database']['InsertPocscanResult'](arg1, arg2);
}

export function InsertScanTask(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['Database']['InsertScanTask'](arg1, arg2, arg3, arg4, arg5);
}

export function ReadWebReportWithJson(arg1) {
  return window['go']['services']['Database']['ReadWebReportWithJson'](arg1);
}

export function RemoveConnection(arg1) {
  return window['go']['services']['Database']['RemoveConnection'](arg1);
}

export function RemoveFavGrammarFiled(arg1, arg2, arg3) {
  return window['go']['services']['Database']['RemoveFavGrammarFiled'](arg1, arg2, arg3);
}

export function RenameScanTask(arg1, arg2) {
  return window['go']['services']['Database']['RenameScanTask'](arg1, arg2);
}

export function SearchAgentPool() {
  return window['go']['services']['Database']['SearchAgentPool']();
}

export function SelectAllSyntax(arg1) {
  return window['go']['services']['Database']['SelectAllSyntax'](arg1);
}

export function SelectFingerscanResult(arg1) {
  return window['go']['services']['Database']['SelectFingerscanResult'](arg1);
}

export function SelectPocscanResult(arg1) {
  return window['go']['services']['Database']['SelectPocscanResult'](arg1);
}

export function Startup(arg1) {
  return window['go']['services']['Database']['Startup'](arg1);
}

export function UpdateConnection(arg1) {
  return window['go']['services']['Database']['UpdateConnection'](arg1);
}

export function UpdateOrInsertPath(arg1) {
  return window['go']['services']['Database']['UpdateOrInsertPath'](arg1);
}

export function UpdateScanWithResult(arg1, arg2, arg3) {
  return window['go']['services']['Database']['UpdateScanWithResult'](arg1, arg2, arg3);
}
