// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {clients} from '../models';
import {context} from '../models';

export function CVE_2017_7921(arg1:string,arg2:clients.Proxy):Promise<string>;

export function CVE_2021_29441_AddUser(arg1:string,arg2:string,arg3:string,arg4:clients.Proxy):Promise<string>;

export function CVE_2021_29441_DelUser(arg1:string,arg2:string,arg3:clients.Proxy):Promise<string>;

export function CVE_2021_29442(arg1:string,arg2:clients.Proxy):Promise<string>;

export function CVE_2021_36260(arg1:string,arg2:string,arg3:clients.Proxy):Promise<string>;

export function CameraCrackPassword(arg1:string,arg2:string,arg3:Array<string>):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;
