// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function CVE_2017_7921(arg1:string,arg2:string):Promise<string>;

export function CVE_2021_29441_AddUser(arg1:string,arg2:{[key: string]: string},arg3:string,arg4:string,arg5:string):Promise<string>;

export function CVE_2021_29441_DelUser(arg1:string,arg2:{[key: string]: string},arg3:string,arg4:string):Promise<string>;

export function CVE_2021_29442(arg1:string,arg2:{[key: string]: string},arg3:string):Promise<string>;

export function CVE_2021_36260(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CameraCrackPassword(arg1:string,arg2:string,arg3:Array<string>):Promise<string>;

export function FineReportChannelDeserialize(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;
