// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoGenerateFavicon(arg1) {
  return window['go']['services']['File']['AutoGenerateFavicon'](arg1);
}

export function BuildTree(arg1, arg2, arg3) {
  return window['go']['services']['File']['BuildTree'](arg1, arg2, arg3);
}

export function CheckFileStat(arg1) {
  return window['go']['services']['File']['CheckFileStat'](arg1);
}

export function DirectoryDialog() {
  return window['go']['services']['File']['DirectoryDialog']();
}

export function DownloadLastestClient() {
  return window['go']['services']['File']['DownloadLastestClient']();
}

export function FileDialog(arg1) {
  return window['go']['services']['File']['FileDialog'](arg1);
}

export function FilepathJoin(arg1) {
  return window['go']['services']['File']['FilepathJoin'](arg1);
}

export function GenerateFaviconBase64(arg1) {
  return window['go']['services']['File']['GenerateFaviconBase64'](arg1);
}

export function GenerateFaviconBase64WithOnline(arg1) {
  return window['go']['services']['File']['GenerateFaviconBase64WithOnline'](arg1);
}

export function GetLocalNaConfig() {
  return window['go']['services']['File']['GetLocalNaConfig']();
}

export function InitConfig() {
  return window['go']['services']['File']['InitConfig']();
}

export function InitMemo(arg1, arg2) {
  return window['go']['services']['File']['InitMemo'](arg1, arg2);
}

export function InsetGroupNavigation(arg1) {
  return window['go']['services']['File']['InsetGroupNavigation'](arg1);
}

export function InsetItemNavigation(arg1, arg2) {
  return window['go']['services']['File']['InsetItemNavigation'](arg1, arg2);
}

export function IsMacOS() {
  return window['go']['services']['File']['IsMacOS']();
}

export function List(arg1) {
  return window['go']['services']['File']['List'](arg1);
}

export function ListDir(arg1) {
  return window['go']['services']['File']['ListDir'](arg1);
}

export function NetworkCardInfo() {
  return window['go']['services']['File']['NetworkCardInfo']();
}

export function OpenFolder(arg1) {
  return window['go']['services']['File']['OpenFolder'](arg1);
}

export function OpenTerminal(arg1) {
  return window['go']['services']['File']['OpenTerminal'](arg1);
}

export function Path(arg1) {
  return window['go']['services']['File']['Path'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['services']['File']['ReadFile'](arg1);
}

export function ReadLocalStore() {
  return window['go']['services']['File']['ReadLocalStore']();
}

export function ReadMemo(arg1) {
  return window['go']['services']['File']['ReadMemo'](arg1);
}

export function RemoveFile(arg1) {
  return window['go']['services']['File']['RemoveFile'](arg1);
}

export function RemoveOldClient() {
  return window['go']['services']['File']['RemoveOldClient']();
}

export function RemoveOldConfig() {
  return window['go']['services']['File']['RemoveOldConfig']();
}

export function Restart() {
  return window['go']['services']['File']['Restart']();
}

export function RunApp(arg1) {
  return window['go']['services']['File']['RunApp'](arg1);
}

export function SaveDataToFile(arg1) {
  return window['go']['services']['File']['SaveDataToFile'](arg1);
}

export function SaveFileDialog(arg1) {
  return window['go']['services']['File']['SaveFileDialog'](arg1);
}

export function SaveNavigation(arg1) {
  return window['go']['services']['File']['SaveNavigation'](arg1);
}

export function SaveToTempFile(arg1) {
  return window['go']['services']['File']['SaveToTempFile'](arg1);
}

export function SnippetCommandLine(arg1) {
  return window['go']['services']['File']['SnippetCommandLine'](arg1);
}

export function Startup(arg1) {
  return window['go']['services']['File']['Startup'](arg1);
}

export function UpdatePocFile(arg1) {
  return window['go']['services']['File']['UpdatePocFile'](arg1);
}

export function UserHomeDir() {
  return window['go']['services']['File']['UserHomeDir']();
}

export function WriteFile(arg1, arg2, arg3) {
  return window['go']['services']['File']['WriteFile'](arg1, arg2, arg3);
}
