id: CVE-2011-2523

info:
  name: VSFTPD 2.3.4 - Backdoor Command Execution
  author: pussycat0x
  severity: critical
  description: |
    VSFTPD v2.3.4 had a serious backdoor vulnerability allowing attackers to execute arbitrary commands on the server with root-level access. The backdoor was triggered by a specific string of characters in a user login request, which allowed attackers to execute any command they wanted.
    shodan-query: product:"vsftpd"
  reference: 
    - https://www.rapid7.com/db/modules/exploit/unix/ftp/vsftpd_234_backdoor/
    - https://www.exploit-db.com/exploits/49757
  tags: cve,cve2011,network,vsftpd,ftp,backdoor
  created: 2023/5/22

rules:
  r0:
    request:
      type: go
      data: cve-2011-2523
    expression: '"root:.*?:[0-9]*:[0-9]*:".bmatches(response.body)'
expression: r0()

      