id: go-demo

info:
  name: Go Demo
  author: zan8in
  severity: high
  verified: true
  description: Go Demo

rules:
  r0:
    request:
      type: go
      data: demo
    expression: response.raw.bcontains(b'hello')
expression: r0()