id: CVE-2023-25157

info:
  name: GeoServer OGC Filter - SQL Injection
  author: zan8in
  severity: critical
  verified: true
  description: |
    GeoServer is an open source software server written in Java that allows users to share and edit geospatial data. GeoServer includes support for the OGC Filter expression language and the OGC Common Query Language (CQL) as part of the Web Feature Service (WFS) and Web Map Service (WMS) protocols. CQL is also supported through the Web Coverage Service (WCS) protocol for ImageMosaic coverages. Users are advised to upgrade to either version 2.21.4, or version 2.22.2 to resolve this issue. Users unable to upgrade should disable the PostGIS Datastore *encode functions* setting to mitigate ``strEndsWith``, ``strStartsWith`` and ``PropertyIsLike `` misuse and enable the PostGIS DataStore *preparedStatements* setting to mitigate the ``FeatureId`` misuse.
    fofa-query: app="GeoServer"
    shodan-query: /geoserver/
  reference:
    - https://github.com/drfabiocastro/geoserver/
    - https://mp.weixin.qq.com/s/GzwxQ6LXSDD2TeVc8NrOSg
  created: 2023/06/14

rules:
  r0:
    request:
      type: go
      data: CVE-2023-25157
    expression: response.raw.bcontains(b'SQL SELECT')
expression: r0()