// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActiveFingerScan(arg1, arg2) {
  return window['go']['main']['App']['ActiveFingerScan'](arg1, arg2);
}

export function AlibabaNacos(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['AlibabaNacos'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function AssetHunter(arg1, arg2, arg3) {
  return window['go']['main']['App']['AssetHunter'](arg1, arg2, arg3);
}

export function Callgologger(arg1, arg2) {
  return window['go']['main']['App']['Callgologger'](arg1, arg2);
}

export function CheckCdn(arg1) {
  return window['go']['main']['App']['CheckCdn'](arg1);
}

export function CheckTarget(arg1, arg2) {
  return window['go']['main']['App']['CheckTarget'](arg1, arg2);
}

export function CyberChefLocalServer() {
  return window['go']['main']['App']['CyberChefLocalServer']();
}

export function DirScan(arg1) {
  return window['go']['main']['App']['DirScan'](arg1);
}

export function DownloadCyberChef(arg1) {
  return window['go']['main']['App']['DownloadCyberChef'](arg1);
}

export function ExtractIP(arg1) {
  return window['go']['main']['App']['ExtractIP'](arg1);
}

export function FaviconMd5(arg1) {
  return window['go']['main']['App']['FaviconMd5'](arg1);
}

export function FingerScan(arg1, arg2) {
  return window['go']['main']['App']['FingerScan'](arg1, arg2);
}

export function FingerprintList() {
  return window['go']['main']['App']['FingerprintList']();
}

export function FofaSearch(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['FofaSearch'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function FofaTips(arg1) {
  return window['go']['main']['App']['FofaTips'](arg1);
}

export function Fscan2Txt(arg1) {
  return window['go']['main']['App']['Fscan2Txt'](arg1);
}

export function GetFingerPocMap() {
  return window['go']['main']['App']['GetFingerPocMap']();
}

export function GitDorks(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitDorks'](arg1, arg2, arg3);
}

export function GoFetch(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GoFetch'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function HikvsionCamera(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['HikvsionCamera'](arg1, arg2, arg3, arg4, arg5);
}

export function HostAlive(arg1, arg2) {
  return window['go']['main']['App']['HostAlive'](arg1, arg2);
}

export function HunterSearch(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['HunterSearch'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function HunterTips(arg1) {
  return window['go']['main']['App']['HunterTips'](arg1);
}

export function ICPInfo(arg1) {
  return window['go']['main']['App']['ICPInfo'](arg1);
}

export function IPParse(arg1) {
  return window['go']['main']['App']['IPParse'](arg1);
}

export function IconHash(arg1) {
  return window['go']['main']['App']['IconHash'](arg1);
}

export function InitRule() {
  return window['go']['main']['App']['InitRule']();
}

export function InitTycHeader(arg1) {
  return window['go']['main']['App']['InitTycHeader'](arg1);
}

export function Ip138IpHistory(arg1) {
  return window['go']['main']['App']['Ip138IpHistory'](arg1);
}

export function Ip138Subdomain(arg1) {
  return window['go']['main']['App']['Ip138Subdomain'](arg1);
}

export function IpLocation(arg1) {
  return window['go']['main']['App']['IpLocation'](arg1);
}

export function IsRoot() {
  return window['go']['main']['App']['IsRoot']();
}

export function JSFind(arg1, arg2) {
  return window['go']['main']['App']['JSFind'](arg1, arg2);
}

export function Kill(arg1) {
  return window['go']['main']['App']['Kill'](arg1);
}

export function LoadDirsearchDict(arg1, arg2) {
  return window['go']['main']['App']['LoadDirsearchDict'](arg1, arg2);
}

export function NewSynScanner(arg1, arg2, arg3) {
  return window['go']['main']['App']['NewSynScanner'](arg1, arg2, arg3);
}

export function NewTcpScanner(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['NewTcpScanner'](arg1, arg2, arg3, arg4, arg5);
}

export function NucleiEnabled(arg1) {
  return window['go']['main']['App']['NucleiEnabled'](arg1);
}

export function NucleiScanner(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['NucleiScanner'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function PortBrute(arg1, arg2, arg3) {
  return window['go']['main']['App']['PortBrute'](arg1, arg2, arg3);
}

export function PortParse(arg1) {
  return window['go']['main']['App']['PortParse'](arg1);
}

export function QuakeSearch(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['QuakeSearch'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function QuakeTips(arg1) {
  return window['go']['main']['App']['QuakeTips'](arg1);
}

export function Sock5Connect(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Sock5Connect'](arg1, arg2, arg3, arg4, arg5);
}

export function StopDirScan() {
  return window['go']['main']['App']['StopDirScan']();
}

export function StopPortScan() {
  return window['go']['main']['App']['StopPortScan']();
}

export function StopSubdomain() {
  return window['go']['main']['App']['StopSubdomain']();
}

export function Subdomain(arg1) {
  return window['go']['main']['App']['Subdomain'](arg1);
}

export function SubsidiariesAndDomains(arg1, arg2, arg3) {
  return window['go']['main']['App']['SubsidiariesAndDomains'](arg1, arg2, arg3);
}

export function System(arg1, arg2) {
  return window['go']['main']['App']['System'](arg1, arg2);
}

export function ThinkDict(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['ThinkDict'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function UncoverSearch(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UncoverSearch'](arg1, arg2, arg3, arg4);
}

export function WechatOfficial(arg1) {
  return window['go']['main']['App']['WechatOfficial'](arg1);
}
