// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssetHunter(arg1, arg2, arg3) {
  return window['go']['main']['App']['AssetHunter'](arg1, arg2, arg3);
}

export function AssetSubcompany(arg1, arg2) {
  return window['go']['main']['App']['AssetSubcompany'](arg1, arg2);
}

export function AssetWechat(arg1) {
  return window['go']['main']['App']['AssetWechat'](arg1);
}

export function CheckCdn(arg1, arg2, arg3) {
  return window['go']['main']['App']['CheckCdn'](arg1, arg2, arg3);
}

export function CheckFileStat(arg1) {
  return window['go']['main']['App']['CheckFileStat'](arg1);
}

export function CheckTarget(arg1, arg2) {
  return window['go']['main']['App']['CheckTarget'](arg1, arg2);
}

export function DefaultOpenURL(arg1) {
  return window['go']['main']['App']['DefaultOpenURL'](arg1);
}

export function DomainInfo(arg1) {
  return window['go']['main']['App']['DomainInfo'](arg1);
}

export function ExtractIP(arg1) {
  return window['go']['main']['App']['ExtractIP'](arg1);
}

export function FingerScan(arg1, arg2, arg3) {
  return window['go']['main']['App']['FingerScan'](arg1, arg2, arg3);
}

export function FofaSearch(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['FofaSearch'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function FofaTips(arg1) {
  return window['go']['main']['App']['FofaTips'](arg1);
}

export function Fscan2Txt(arg1) {
  return window['go']['main']['App']['Fscan2Txt'](arg1);
}

export function GetFileContent(arg1) {
  return window['go']['main']['App']['GetFileContent'](arg1);
}

export function GetFingerPoc(arg1) {
  return window['go']['main']['App']['GetFingerPoc'](arg1);
}

export function GoSimpleFetch(arg1) {
  return window['go']['main']['App']['GoSimpleFetch'](arg1);
}

export function HostAlive(arg1, arg2) {
  return window['go']['main']['App']['HostAlive'](arg1, arg2);
}

export function HunterTips(arg1) {
  return window['go']['main']['App']['HunterTips'](arg1);
}

export function IPParse(arg1) {
  return window['go']['main']['App']['IPParse'](arg1);
}

export function IconHash(arg1) {
  return window['go']['main']['App']['IconHash'](arg1);
}

export function InitDict(arg1) {
  return window['go']['main']['App']['InitDict'](arg1);
}

export function InitIPResolved() {
  return window['go']['main']['App']['InitIPResolved']();
}

export function InitRule() {
  return window['go']['main']['App']['InitRule']();
}

export function InitTycHeader(arg1) {
  return window['go']['main']['App']['InitTycHeader'](arg1);
}

export function LocalWalkFiles(arg1) {
  return window['go']['main']['App']['LocalWalkFiles'](arg1);
}

export function Minimise() {
  return window['go']['main']['App']['Minimise']();
}

export function PathRequest(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PathRequest'](arg1, arg2, arg3, arg4);
}

export function PocNums(arg1, arg2) {
  return window['go']['main']['App']['PocNums'](arg1, arg2);
}

export function PortBrute(arg1, arg2, arg3) {
  return window['go']['main']['App']['PortBrute'](arg1, arg2, arg3);
}

export function PortCheck(arg1, arg2, arg3) {
  return window['go']['main']['App']['PortCheck'](arg1, arg2, arg3);
}

export function PortParse(arg1) {
  return window['go']['main']['App']['PortParse'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReadPocDetail(arg1) {
  return window['go']['main']['App']['ReadPocDetail'](arg1);
}

export function Restart() {
  return window['go']['main']['App']['Restart']();
}

export function Subdomain(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Subdomain'](arg1, arg2, arg3, arg4);
}

export function System(arg1, arg2) {
  return window['go']['main']['App']['System'](arg1, arg2);
}

export function TestTarget(arg1) {
  return window['go']['main']['App']['TestTarget'](arg1);
}

export function ThinkDict(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ThinkDict'](arg1, arg2, arg3, arg4, arg5);
}

export function ToggleMaximise() {
  return window['go']['main']['App']['ToggleMaximise']();
}

export function Transcoding(arg1, arg2, arg3) {
  return window['go']['main']['App']['Transcoding'](arg1, arg2, arg3);
}

export function UpdateClinetFile(arg1) {
  return window['go']['main']['App']['UpdateClinetFile'](arg1);
}

export function UpdatePocFile(arg1) {
  return window['go']['main']['App']['UpdatePocFile'](arg1);
}

export function Webscan(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Webscan'](arg1, arg2, arg3, arg4, arg5);
}

export function WechatAppid(arg1, arg2) {
  return window['go']['main']['App']['WechatAppid'](arg1, arg2);
}
