// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnection(arg1) {
  return window['go']['main']['Database']['AddConnection'](arg1);
}

export function Check() {
  return window['go']['main']['Database']['Check']();
}

export function ConnectDatabase(arg1) {
  return window['go']['main']['Database']['ConnectDatabase'](arg1);
}

export function ConnectMongodb(arg1, arg2, arg3) {
  return window['go']['main']['Database']['ConnectMongodb'](arg1, arg2, arg3);
}

export function CreateTable() {
  return window['go']['main']['Database']['CreateTable']();
}

export function DisconnectDatabase(arg1) {
  return window['go']['main']['Database']['DisconnectDatabase'](arg1);
}

export function ExecSqlStatement(arg1, arg2) {
  return window['go']['main']['Database']['ExecSqlStatement'](arg1, arg2);
}

export function FetchDatabaseinfoFromMongodb() {
  return window['go']['main']['Database']['FetchDatabaseinfoFromMongodb']();
}

export function FetchDatabaseinfoFromMysql() {
  return window['go']['main']['Database']['FetchDatabaseinfoFromMysql']();
}

export function FetchTableInfoFromMysql(arg1, arg2) {
  return window['go']['main']['Database']['FetchTableInfoFromMysql'](arg1, arg2);
}

export function GetAllDatabaseConnections() {
  return window['go']['main']['Database']['GetAllDatabaseConnections']();
}

export function GetAllPathsAndTimes() {
  return window['go']['main']['Database']['GetAllPathsAndTimes']();
}

export function InsertFavGrammarFiled(arg1, arg2, arg3) {
  return window['go']['main']['Database']['InsertFavGrammarFiled'](arg1, arg2, arg3);
}

export function RemoveConnection(arg1) {
  return window['go']['main']['Database']['RemoveConnection'](arg1);
}

export function RemoveFavGrammarFiled(arg1, arg2, arg3) {
  return window['go']['main']['Database']['RemoveFavGrammarFiled'](arg1, arg2, arg3);
}

export function SearchAgentPool() {
  return window['go']['main']['Database']['SearchAgentPool']();
}

export function SelectAllSyntax(arg1) {
  return window['go']['main']['Database']['SelectAllSyntax'](arg1);
}

export function UpdateConnection(arg1) {
  return window['go']['main']['Database']['UpdateConnection'](arg1);
}

export function UpdateOrInsertPath(arg1) {
  return window['go']['main']['Database']['UpdateOrInsertPath'](arg1);
}
