// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Check() {
  return window['go']['main']['Database']['Check']();
}

export function CreateHunterSyntaxTable() {
  return window['go']['main']['Database']['CreateHunterSyntaxTable']();
}

export function CreateQuakeSyntaxTable() {
  return window['go']['main']['Database']['CreateQuakeSyntaxTable']();
}

export function CreateTable() {
  return window['go']['main']['Database']['CreateTable']();
}

export function DeleteAgentPoolField(arg1) {
  return window['go']['main']['Database']['DeleteAgentPoolField'](arg1);
}

export function DeleteAllField(arg1) {
  return window['go']['main']['Database']['DeleteAllField'](arg1);
}

export function DeleteHunterSyntax(arg1, arg2) {
  return window['go']['main']['Database']['DeleteHunterSyntax'](arg1, arg2);
}

export function DeleteQuakeSyntax(arg1, arg2) {
  return window['go']['main']['Database']['DeleteQuakeSyntax'](arg1, arg2);
}

export function InsertAgentPool(arg1) {
  return window['go']['main']['Database']['InsertAgentPool'](arg1);
}

export function InsertHunterSyntax(arg1, arg2) {
  return window['go']['main']['Database']['InsertHunterSyntax'](arg1, arg2);
}

export function InsertQuakeSyntax(arg1, arg2) {
  return window['go']['main']['Database']['InsertQuakeSyntax'](arg1, arg2);
}

export function SearchAgentPool() {
  return window['go']['main']['Database']['SearchAgentPool']();
}

export function SelectAllHunterSyntax() {
  return window['go']['main']['Database']['SelectAllHunterSyntax']();
}

export function SelectAllQuakeSyntax() {
  return window['go']['main']['Database']['SelectAllQuakeSyntax']();
}
