// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {structs} from '../models';
import {mongo} from '../models';
import {main} from '../models';

export function AddConnection(arg1:structs.DatabaseConnection):Promise<boolean>;

export function Check():Promise<boolean>;

export function ConnectDatabase(arg1:structs.DatabaseConnection):Promise<boolean>;

export function ConnectMongodb(arg1:string,arg2:string,arg3:string):Promise<mongo.Client>;

export function CreateTable():Promise<boolean>;

export function DisconnectDatabase(arg1:string):Promise<boolean>;

export function ExecSqlStatement(arg1:string,arg2:Array<any>):Promise<boolean>;

export function FetchDatabaseInfoFromOracle():Promise<{[key: string]: Array<string>}>;

export function FetchDatabaseInfoFromPostgres():Promise<{[key: string]: Array<string>}>;

export function FetchDatabaseinfoFromMongodb():Promise<{[key: string]: Array<string>}>;

export function FetchDatabaseinfoFromMysql():Promise<{[key: string]: Array<string>}>;

export function FetchDatabaseinfoFromSqlServer():Promise<{[key: string]: Array<string>}>;

export function FetchTableInfoFromMysql(arg1:string,arg2:string):Promise<structs.RowData>;

export function FetchTableInfoFromOracle(arg1:string,arg2:string):Promise<structs.RowData>;

export function FetchTableInfoFromPostgres(arg1:string,arg2:string):Promise<structs.RowData>;

export function FetchTableInfoFromSqlServer(arg1:string,arg2:string):Promise<structs.RowData>;

export function GetAllDatabaseConnections():Promise<Array<structs.DatabaseConnection>>;

export function GetAllPathsAndTimes():Promise<Array<main.pathTimes>>;

export function InsertFavGrammarFiled(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function RemoveConnection(arg1:string):Promise<boolean>;

export function RemoveFavGrammarFiled(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function SearchAgentPool():Promise<Array<string>>;

export function SelectAllSyntax(arg1:string):Promise<Array<main.Syntax>>;

export function UpdateConnection(arg1:structs.DatabaseConnection):Promise<boolean>;

export function UpdateOrInsertPath(arg1:string):Promise<boolean>;
