// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Check():Promise<boolean>;

export function CreateTable():Promise<boolean>;

export function DeleteAgentPoolField(arg1:string):Promise<boolean>;

export function DeleteAllField(arg1:string):Promise<boolean>;

export function InsertAgentPool(arg1:string):Promise<boolean>;

export function SearchAgentPool():Promise<Array<string>>;
