// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Check():Promise<boolean>;

export function CreateTable():Promise<boolean>;

export function DeleteAgentPoolField(arg1:string):Promise<boolean>;

export function DeleteAllField(arg1:string):Promise<boolean>;

export function InsertAgentPool(arg1:string):Promise<boolean>;

export function InsertFavGrammarFiled(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function RemoveFavGrammarFiled(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function SearchAgentPool():Promise<Array<string>>;

export function SelectAllSyntax(arg1:string):Promise<Array<main.Syntax>>;
