// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFileStat(arg1:string):Promise<boolean>;

export function ExecutionPath():Promise<string>;

export function GetFileContent(arg1:string):Promise<string>;

export function OpenFolder(arg1:string):Promise<string>;

export function Restart():Promise<void>;

export function UpdateClinetFile(arg1:string):Promise<string>;

export function UpdatePocFile(arg1:string):Promise<string>;
