// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFileStat(arg1) {
  return window['go']['main']['File']['CheckFileStat'](arg1);
}

export function DownloadLastestClient() {
  return window['go']['main']['File']['DownloadLastestClient']();
}

export function FileDialog(arg1) {
  return window['go']['main']['File']['FileDialog'](arg1);
}

export function GetLocalNaConfig() {
  return window['go']['main']['File']['GetLocalNaConfig']();
}

export function InitConfig() {
  return window['go']['main']['File']['InitConfig']();
}

export function InitMemo(arg1, arg2) {
  return window['go']['main']['File']['InitMemo'](arg1, arg2);
}

export function InsetGroupNavigation(arg1) {
  return window['go']['main']['File']['InsetGroupNavigation'](arg1);
}

export function InsetItemNavigation(arg1, arg2) {
  return window['go']['main']['File']['InsetItemNavigation'](arg1, arg2);
}

export function Mkdir(arg1) {
  return window['go']['main']['File']['Mkdir'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['File']['OpenFolder'](arg1);
}

export function Path(arg1) {
  return window['go']['main']['File']['Path'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['File']['ReadFile'](arg1);
}

export function ReadMemo(arg1) {
  return window['go']['main']['File']['ReadMemo'](arg1);
}

export function RemoveOldConfig() {
  return window['go']['main']['File']['RemoveOldConfig']();
}

export function Restart() {
  return window['go']['main']['File']['Restart']();
}

export function RunApp(arg1, arg2, arg3) {
  return window['go']['main']['File']['RunApp'](arg1, arg2, arg3);
}

export function SaveFile(arg1) {
  return window['go']['main']['File']['SaveFile'](arg1);
}

export function SaveJsonFile(arg1) {
  return window['go']['main']['File']['SaveJsonFile'](arg1);
}

export function SaveNavigation(arg1) {
  return window['go']['main']['File']['SaveNavigation'](arg1);
}

export function UpdateClinetFile(arg1) {
  return window['go']['main']['File']['UpdateClinetFile'](arg1);
}

export function UpdatePocFile() {
  return window['go']['main']['File']['UpdatePocFile']();
}

export function UserHomeDir() {
  return window['go']['main']['File']['UserHomeDir']();
}

export function WriteFile(arg1, arg2, arg3) {
  return window['go']['main']['File']['WriteFile'](arg1, arg2, arg3);
}
