// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFileStat(arg1:string):Promise<boolean>;

export function GetFileContent(arg1:string):Promise<string>;

export function InitConfig():Promise<boolean>;

export function InitMemo(arg1:string,arg2:string):Promise<boolean>;

export function Mkdir(arg1:string):Promise<boolean>;

export function OpenFolder(arg1:string):Promise<string>;

export function PathBase(arg1:string):Promise<string>;

export function ReadMemo(arg1:string):Promise<{[key: string]: string}>;

export function UpdatePocFile():Promise<string>;

export function UserHomeDir():Promise<string>;

export function WriteFile(arg1:string,arg2:string,arg3:string):Promise<boolean>;
