// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFileStat(arg1) {
  return window['go']['main']['File']['CheckFileStat'](arg1);
}

export function CreateTable() {
  return window['go']['main']['File']['CreateTable']();
}

export function GetFileContent(arg1) {
  return window['go']['main']['File']['GetFileContent'](arg1);
}

export function InitConfig() {
  return window['go']['main']['File']['InitConfig']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['File']['OpenFolder'](arg1);
}

export function PathBase(arg1) {
  return window['go']['main']['File']['PathBase'](arg1);
}

export function Restart() {
  return window['go']['main']['File']['Restart']();
}

export function UpdateClinetFile(arg1) {
  return window['go']['main']['File']['UpdateClinetFile'](arg1);
}

export function UpdatePocFile() {
  return window['go']['main']['File']['UpdatePocFile']();
}

export function UserHomeDir() {
  return window['go']['main']['File']['UserHomeDir']();
}
